### ISSUE TITLE
User group functionality

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1042]
TODO:

- [x] Implement views to support group UI functionalities (Pabitra)
   - [x] create group
   - [x] update group
   - [x] Inactive group (Phase-2)
   - [x] share group with user (adding a user to group)
   - [x] unshare group with user (removing a user from a group)
   - [x] share resource with a group
   - [x] unshare resource with a group
   - [x] make request to join a group
   - [x] accept/decline request to join group
- [x] Extend group model to have additional data fields (Description, Purpose, Date Created)(Pabitra)
- [x] Implement invitation/request to join group (Pabitra)
   - [x] email notification (on user request email is sent to all owners, on owner invitation, email is sent to the specific user, on user acceptance of invitation, email is sent to the owner who invited, on owner acceptance, email is sent to user)
- [ ] Group Profile Page (Mauriel)
- [ ] Group Sharing of Resources (Changes to Manage Access UI) (Mauriel)

**Comment by pkdash** [comment]
@mauriel133 Can you list (as part of this issue) all the UI level functionalities related to user groups that you plan to implement? That would help me in backend implementation.

**Comment by mauriel133** [comment]
These are initial use cases I think we could start with (need to confirm with @horsburgh ):
- Create group
- Delete group
- Request join group
- Invite user to group
- Leave group
- Promote member to owner
- Demote owner to member (only creators and other owners can do this)
- Share a resource with a group
- Unshare a resource with a group
- Get list of resources shared with a group
- Start a discussion
- Get list of discussions

Group membership: a user can be Creator, Owner or Member
- Creator: has all explicit privileges. Can not be demoted by other users.
- Owner: can invite and accept join requests. Can demote other owners to members. Can promote members to owners.
- Member: has no explicit privileges.


Groups can be public or private
- Private: only owners and creators can invite  other members or accept requests to join.
- Public: anyone in the group can invite other members or accept requests to join.

**Comment by mauriel133** [comment]
I have posted the list now after confirming with Jeff.

*Maurier Ramírez*
Computer Scientist
Utah Water Research Laboratory
Utah State University
8200 Old Main Hill
Logan, UT 84322-8200
Phone: (435) 932-0727

**Comment by pkdash** [comment]
@horsburgh Here @mauriel133 has specified that only group owners can invite users to join group.

**Comment by dtarb** [comment]
Please refer to the access control design document at https://docs.google.com/document/d/1JMvn9-p6aLm9wTEnbakCwYGQHwuaP1uzma_6C_eiBhM/edit

It says the following about groups (on about page 4)

- View privilege for a group makes a user a member but they can not invite other members
- Change privilege for a group makes a user a member with the ability to add and remove members
- Owner privilege gives all privileges, including the ability to delete a group.

So there is a concept of deletion.  It may be OK to implement this as deactivation, but we need clarity on what is presented to users and what this actually means about functionality shown to users.

@alvacouch may want to comment 

There is also a social functionality document that was originally written by @gantian127 that may be useful.

https://docs.google.com/document/d/1hVevqBDLK-Jx2-T_uimfPjj8shcBe2LHPxoSHXsGo18/edit

**Comment by horsburgh** [comment]
@pkdash, @mauriel133, and @alvacouch  - is it possible now with our current access control implementation for group members to have one of 3 roles:

**Owner**:  Access to all group functionality, including inactivating a group (Dave's "Owner" privilege above)
**Editor**:  Access to editing group details, inviting new members, and accepting invitations along with all Member privileges (Dave's "change" privilege above) - but NOT inactivating a group
**Member**: Access to view group details, view and access group resources (Dave's "View" privilege above) - NOT inviting or accepting other members and not inactivating a group

**Comment by pkdash** [comment]
@horsburgh 

> Owner: Access to all group functionality, including inactivating a group (Dave's "Owner" privilege above)

Yes

> Member: Access to view group details, view and access group resources (Dave's "View" privilege above) - NOT inviting or accepting other members and not inactivating a group

Yes

> Editor: Access to editing group details, inviting new members, and accepting invitations along with all Member privileges (Dave's "change" privilege above) - but NOT inactivating a group

Yes from access control point of view. However, I have not implemented as part of the group functionality to allow editors to invite or accept requests to join groups. This can be added easily as long as we allow user to join group with 'view' privilege only. Once a user joins a group, his/her privilege can be upgraded.

**Comment by horsburgh** [comment]
@pkdash - I think I'm OK with this:

> This can be added easily as long as we allow user to join group with 'view' privilege only. Once a user joins a group, his/her privilege can be upgraded.

But, I'm also OK with having only two roles - Owner, and Member.  The only permission reserved for Owner that Editor would not have is the ability to deactivate the group.

@dtarb - do we really need three roles, or can we go with just Owner and Member?

**Comment by dtarb** [comment]
I am OK with just owner and member (assuming multiple owners as was demoed).  I just want to make sure deviations from the original thinking are deliberate rather than oversights.  So if you have reasons (and I can see simplification as a reason) for just owner and member, then I am fine with that.  It may also be worthwhile looking at how other systems handle groups.

**Comment by pkdash** [comment]
Access control already has implementation to support these 3 roles. It will be more work if we change it 2 roles.

**Comment by horsburgh** [comment]
@pkdash - maybe I misunderstood.  For some reason I thought you were going to have to do additional work to support the 3 roles.  

2 roles or 3 - do whatever is easiest.  I think both models will work.  But, it seems a little silly to add an additional role just to differentiate between who can deactivate a group and who can't.  If you trust someone to edit all of the group details and membership, why not just make them an owner?

I looked at ArcGIS Online this morning and I think they only have 2 roles - Owner and Member.  And, I think there can only be one owner. There is also a group-wide setting that specifies whether members can contribute content or not. We are handling this in a slightly different way by allowing any user to share any content with a group.  I will work on writing down the rules for groups...

**Comment by pkdash** [comment]
@horsburgh I think there is more difference between an owner and an editor of a group than just who can set the 'active' flag. The difference is very similar to that of an owner and editor of a resource.

**Comment by horsburgh** [comment]
@pkdash - what are the other differences?

**Comment by pkdash** [comment]
@horsburgh Here are the differences:

1. Owner can set resource flags(active, shareable, public). Editor can't
2. Owner can delete a group. Editor can't
3. Owner can remove member from the group. Editor can't. 
4. Owner can grant user all level of access privilege. Editor can grant user maximum 'Edit' permission.
5. Owner can change access permission to any privilege of any member. Editor can't downgrade permission that was originally granted by someone else.
6. Owner can add members when group is not shareable. Editor can't.

**Comment by mauriel133** [comment]
Pabitra, after discussing with @horsburgh we agree that we should go with an approach of two types of group members: Owners and Members. It is more intuitive from a user point of view. That means the person that creates the group will also have the same privileges as someone that has been granted Owner status. 

Also, a group must have at least one Owner at all times.

**Comment by horsburgh** [comment]
@pkdash - thanks for sending the list of differences.  In looking through them, the difference between an "owner" and "editor" are somewhat subtle. There's some complexity there that @mauriel133 and I didn't feel was needed.  If people have really strong feelings that we should keep the 3 roles, we can change the front end to support that, but we would like to simplify to have two roles - Owner and Member.

**Comment by alvacouch** [comment]
@pkdash @mauriel133 @horsburgh 
It is rather trivial to simply leave the editor role unused. I can delete it from access control later.

**Comment by pkdash** [comment]
I agree with @alvacouch suggestion. At this point we will not make any changes to access control. However, will make changes to view functions so that 'editor role' is not exposed to UI.

**Comment by horsburgh** [comment]
I was just thinking about this earlier today.  If we can leave it unused for now, we could see what users want and we would have the option to implement the third role later.  Let's implement the two roles on the front end (as it is now already nearly complete).

**Comment by mauriel133** [comment]
Here is an update on what has been accomplished and where we are going:

# HydroShare Groups Implementation

**Phase I**

- [x] Create group
- [X] Edit group
- [x] Request join group
- [x] Accept join request (only creators and owners can do this)
- [x] Invite user to group
- [x] Leave group
- [x] Promote member to owner (only owners and creators can do this)
- [x] Demote owner to member (only creators and other owners can do this)
- [x] Share a resource with a group
- [x] Unshare a resource with a group
- [x] Get list of resources shared with a group

Group membership: a user can be Owner or Member
- [x] Owner: can invite and accept join requests. Can demote other owners to members. Can promote members to owners. Can edit the group information.
- [x] Member: has no explicit privileges.

- [x] _Note: a group most have at least one Owner at all times._


Groups can be public, private or discoverable. Only owners and creators can invite and accept requests to join. Users can request to join a group (if they can find it).
- [x] Private:  group can not be found by users outside of it.
- [x] Discoverable: group can be found by users outside of it, but metadata is hidden.
- [x] Public: group can be found, metadata is public.

**Phase II**
- [ ] Start a discussion (Phase-2)
- [ ] Delete a discussion (Phase-2)
- [ ] Comment on a recent activity or discussion.
- [ ] Get recent activity list (additional items): comments, discussion posts, user joined the group.
- [ ] Dynamic/on demand loading in Find Groups and Recent Activity.
- [ ] Ability for members outside of a group to share resources with it.
- [ ] Add labeling/favorite functionality to resource listing of Group page.

**Comment by pkdash** [comment]
Refer to issue #1260 for phase-2

**Comment by pkdash** [comment]
Closing as this feature has already deployed.
