### ISSUE TITLE
Alpha release suggestions

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#106]
- [x] \(**merged into develop**) When signing in, the sign in page header says, "LOG IN" it should say "SIGN IN".
- [x] \(**merged into develop**) When signing in, I enter my user name and password and there is a large green button that says "Log in". It should say, "Sign in". 
- [x] \(**merged into develop**) [#111]Font of all editable text boxes on the resource landing page (in edit mode) is tiny. Looks like about 6 point font. Consider enlarging.
- [x] \(**merged into develop**) [#111]If you add metadata information that meets the requirements for minimal metadata, then the "Metadata Status" should automatically update - not require refreshing the screen.
- [x] \(**merged into develop**) [#111]Rights URL should be clickable.
- [x] \(**merged into develop**) [#111]Change "Citation" to "How to cite"
- [x] \(**merged into develop**) [#111] Reconsider showing creators email address on resource landing page.  DGT suggests do not show creators email address on resource landing page.  We want to avoid exposing email addresses to spam trollers.  Email should be visible to someone editing resource metadata (because an editor is more trusted) and is part of the resourcemetadata xml file, but should not be on the view only landing page.  Note that creator does not have to be a HydroShare user. 
- [x] \(**merged into develop**) [#111] \(v 1.3.0) Change "Metadata Status" "Complete" to "Sufficient for publication".  DGT suggests "Sufficient to make public".  PKDASH "Metadata Status" "Incomplete" to "Insufficient to make public". With this suggestion put this as a Maybe item.
- [x] \(**merged into develop**) [#111] Use placeholder for the 'Title' element on resource creation page
- [x] \(**merged into develop**) When signing in, the sign in page header says, "LOG IN" it should say "SIGN IN".
- [x] \(**merged into develop**) When signing in, I enter my user name and password and there is a large green button that says "Log in". It should say, "Sign in". 
- [x] \(**merged into develop**) [#111]Font of all editable text boxes on the resource landing page (in edit mode) is tiny. Looks like about 6 point font. Consider enlarging.
- [x] \(**merged into develop**) [#111]If you add metadata information that meets the requirements for minimal metadata, then the "Metadata Status" should automatically update - not require refreshing the screen.
- [x] \(**merged into develop**) [#111]Rights URL should be clickable.
- [x] \(**merged into develop**) [#111]Change "Citation" to "How to cite"
- [x] \(**merged into develop**) [#111] Reconsider showing creators email address on resource landing page.  DGT suggests do not show creators email address on resource landing page.  We want to avoid exposing email addresses to spam trollers.  Email should be visible to someone editing resource metadata (because an editor is more trusted) and is part of the resourcemetadata xml file, but should not be on the view only landing page.  Note that creator does not have to be a HydroShare user. 
- [x] \(**merged into develop**) [#111] \(v 1.3.0) Change "Metadata Status" "Complete" to "Sufficient for publication".  DGT suggests "Sufficient to make public".  PKDASH "Metadata Status" "Incomplete" to "Insufficient to make public". With this suggestion put this as a Maybe item.
- [x] \(**merged into develop**) [#111] Use placeholder for the 'Title' element on resource creation page

**Comment by mjstealey** [comment]
Modified Dan's list to be checkbox items that can reflect the state of completion
- [ ] unchecked - not yet done. If in progress add the issue [#106] reference
- [x] checked - has been completed and should have some reference to an issue [#106] or commit

**Comment by pkdash** [comment]
- [ ] Use placeholder for the 'Title' element on resource creation page

**Comment by dtarb** [comment]
I added comments tagged DGT to the list resolving items flagged as needing discussion.  I think that all items on this list should be implemented.  However ones that cannot be quickly and easily implemented should be deferred to next release.

**Comment by pkdash** [comment]
Can't reproduce item 5 and 6 from the above list.

**Comment by mjstealey** [comment]
@pkdash / @danames - For the time being I've put a try/except around the get_citation function on alpha. This is **NOT** in any of the branches, just on the alpha VM itself. It is gross error checking in that it passes or fails as a chunk, and does not validate at each attribute level of the citation, which is what should be done.

At present if it fails you get a "**something_bad_happened_here**" string as your citation instead of the whole resource erring out. This is obviously not what we want to go on production, but I wanted to at least encapsulate the error into a more manageable unit.

We can discuss a better way to handle this on the Wed call.

Reference: [http://alpha.hydroshare.org/resource/1fb43cab2b09411cacd45699236b9ce0/](http://alpha.hydroshare.org/resource/1fb43cab2b09411cacd45699236b9ce0/)

**Comment by danames** [comment]
I deleted all the un-done bullets on this list and I am moving them to a new issue for working on the next release.
