### ISSUE TITLE
Manual Pre-Deploy Check for 1.6.10

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1133]
This is the manual pre-deploy checklist for version 1.6.10.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://alpha.hydroshare.org

Please if you name is below check the box next to it when you have signed off on the functionality.

### Discovery
The discovery is the major new feature in this deploy.  I am therefore asking multiple team members to review and sign off on this.
- [ ] Alva @alvacouch 
- [x] David @dtarb Found issues #1135, #1136 
- [x] Ray @rayi113 Found issues #1192, #1194
- [x] Tian @gantian127 Found issue #1189 

### General functionality

- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
       Found these issues: #1147, #1146, #1145 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey 

#### Resources

- [x] Time Series  [Jeff H] @horsburgh (with the exception of issue #1151)
- [x] HIS time Series [BYU] @danames #1178 (hotfix merged)
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [ ] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [x] SWAT Model Instance [Purdue] @vmmerwade 
- [x] Web App [BYU] @danames #1138 #1155 (resolved on alpha)
- [x] Script [BYU] @danames found issue #1191 
- [x] Collection [BYU] @zhiyuli

**Comment by mohamedmorsy** [comment]
@Castronova @goodalljl @vmmerwade I tested the Model Program, Model Instance, and SWAT Model Instance resource types on https://alpha.hydroshare.org/, and they behave as expected except for issue #1140.

**Comment by mauriel133** [comment]
**Testing Profile**

**3.1**
3) Failed account sign up: when account sign up fails, I got redirected to a non styled page with the previous form.
![capture](https://cloud.githubusercontent.com/assets/2448568/14963837/cd1dfc68-1062-11e6-8a79-78b21e27499c.PNG)

**3.3**
Reset password: when resetting the password I was taken to the old profile edit page (not sure if this is intended). The password field here requires at least 6 characters, but this constraint didn't exist during account creation process.

**3.4**
1) When filling out metadata in order to make the resource public, "Sufficient to make public" message appears when all other required metadata, except content files, have been filled out. The buttons to change sharing status are also enabled, but they fail because of the content files constraint and an error message is shown: "Resource does not have required content files to be public".
3) 
- When resetting password from profile edit page, the 6 character constraint seen in 3.3 is not existent here.
- Under sign out status: personal information is only shown to logged in users. This is intended and it's working as intended. Need to correct Manual pre-deploy document.

**Testing Homepage**

**4.1**
4) Apps link does not open in new tab. 

**4.3**
1) Link triggers a Gmail (in my case) in the same tab. This should be changed to open in a new tab.
3) Report a bug link opens in same tab.

Site Map page needs to be restyled.

**Comment by mauriel133** [comment]
The issues I listed above do not block any of the new functionality and the exist in www right now. I will address them in the upcoming future, but they shouldn't hold the new release.

**Comment by mjstealey** [comment]
> issues I listed above do not block any of the new functionality and the exist in www right now

New issue(s) should be generated for these.
Can be a single checklist, or independent issue threads depending on how you plan to address them.
