### ISSUE TITLE
Manual Pre-Deploy Check for 1.6.11

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1225]
This is the manual pre-deploy checklist for version 1.6.11.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.
**Due Date May 31th, 2016**

### New Features and Enhancements

- [x]  #647 Key-Value pair extensible metadata [Pabitra]  @pkdash
- [x] #1203 Discovery shows blank page [David] @dtarb 
- [x]  #1207 Reference time series resource allows any wml url [Drew] @zhiyuli 
- [x]  #1209 Filter out inactive users and groups [Pabitra] @pkdash 
- [x] #1222 #1223 iRODs bag issues [Hong] @hyi 

### General functionality

- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey 

#### Resources

- [ ] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [ ] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade 
- [x] Web App [BYU] @danames 
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli

**Comment by mauriel133** [comment]
@dtarb, @horsburgh, @gantian127  We are hoping to have PR https://github.com/hydroshare/hydroshare/pull/1224 ready for this release. It contains the group functionality. It is being reviewed right now.

**Comment by gantian127** [comment]
@mauriel133 After #1224 is merged and deployed on Beta site, please add this new feature under "New features and enhancements" section and assign people to test it . Thanks~

**Comment by pkdash** [comment]
@mauriel133, @dtarb , @Horsburgh, @hyi PR #1224 is big. We may not have time to get it in the upcoming release.

**Comment by hyi** [comment]
@mauriel133 @pkdash While testing on beta, I found the recent change of simplifying Subject/keyword edit without clicking on "Save changes" button appears to have a couple of issues. First, after I click on "x" trying to remove the added subject, the subject does not seem to be removed, i.e., after I get to view mode, the keyword is still there. Second, the notification message regarding the resource being sufficient to make public does not seem to be displayed any more after I added a keyword (the raster resource already has content, and abstract). I was using google chrome on windows for testing. Can you confirm whether these are indeed regression issues?

**Comment by mauriel133** [comment]
@pkdash, @hyi  it seems there is a back end error when trying to remove the last keyword. This is the result object returned by the ajax call:

> "{"status": "error", "message": "Failed to create metadata element '{}'. {}."}"

This error also happens in www

@hyi, I fixed the notification issue and will be creating a PR for it soon.

**Comment by mauriel133** [comment]
Testing profile:
I noticed that phone numbers under contact information are shown to anonymous users. This seems wrong to me since we are not showing email addresses in this case. Is this what we want?

**Comment by hyi** [comment]
@pkdash Is there a reason why we don't allow the last keyword to be removed?

**Comment by pkdash** [comment]
@hyi Since the keyword is a required element we don't allow deleting all keywords. It is similar to 'title' or 'abstract'.

**Comment by hyi** [comment]
@pkdash OK. I see, it sounds to me there is a little inconsistency since initially when a resource is created, no keyword is provided, so there is no keyword metadata element. After a user provides a keyword, a keyword metadata element is created, at which point, the user cannot delete that keyword any more if it is the only keyword provided. I guess the user can add another keyword if they want to remove the initial keyword, but it'd be more straightforward to delete the initial one first if they find that initial keyword is not appropriate. It makes total sense the keyword is required if a user wants to make a resource public, but for a private resource, this required restriction might be a bit too restrictive for the user. But I understand this is kind of implemented by design.

**Comment by pkdash** [comment]
@hyi It should be easy to change at the backend if we change the UI for keywords how we do the UI for 'Creators'. However, that won't be very intuitive for editing keywords.
