### ISSUE TITLE
Release 1.7.3 - Checklist

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1340]
This is the manual pre-deploy checklist for version 1.7.3.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.
**Please finish checking before July 20th, 2016**

### New Features and Enhancements

- [x]  #1238 Ref time series & REST API  [Drew] @zhiyuli 
- [ ]  #1253  Discovery page adjustments [Mauriel] @mauriel133 
- [x]  #1263 Collection resource coverage [Drew] @zhiyuli 
- [x]  #1274 Delete user functionality [Michael] @mjstealey (validated using known user, and then recreated using same name/email)
- [ ]  #1300  Adding resource to my resource bug fix [Mauriel] @mauriel133 
- [x]  #1317  Create point coverage from single point shapefile [Drew] @zhiyuli 
- [x]  #1319  Changes to coverage validation [Pabitra]  @pkdash
- [x]  #1328   REST API metadata support for resource creation [Pabitra]  @pkdash
                     (Did few tests using the RestFrameWork browsable web interface)
- [x]  #1337  Key/value pair metadata form layout adjustment [Pabitra]  @pkdash

### General functionality

- [ ] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey (validated)

#### Resources

- [ ] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames  issue#1344
- [x] Multidimensional (NetCDF) [Tian] @gantian127  Found issue #1346 
- [ ] Model Program [Tony] @Castronova 
- [ ] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade 
- [x] Web App [BYU] @danames 
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli
