### ISSUE TITLE
Release 1.7.4 - Checklist

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1378]
This is the manual pre-deploy checklist for version 1.7.4.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.
**Please finish checking before Aug 10th, 2016**

### New Features and Enhancements
- [x]  #1324 Support for multitimeseries [Pabitra]  @pkdash
- [x]  #1366 Ref time series download hotfix [Drew] @zhiyuli 
- [x]  #1365 Web app resource changes for NetCDF resource [Drew] @zhiyuli 
- [x]  #1346 NetCDF bug fix [Tian] @gantian127 
- [x]  #1370 Raster bug fix [Tian] @gantian127 

### General functionality

- [ ] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey

#### Resources

- [x] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [x] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade 
- [x] Web App [BYU] @danames  (issue #1379, hotfix merged and tested on beta)
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli

**Comment by pkdash** [comment]
@Horsburgh As part of testing the timeseries, you may want to delete the SQLite file for the one time series resource that you have and upload the file back to the same resource. However, this file may not be a valid file anymore if it does not contain CV terms data.

**Comment by zhiyuli** [comment]
@gantian127 will you please check this fix: #1365 Web app resource changes for NetCDF resource? thanks

**Comment by gantian127** [comment]
@zhiyuli I will test that. Thanks

**Comment by horsburgh** [comment]
@pkdash - In testing the time series, I found the following issues:

* [ ] CV term lists in drop downs should be alphabetized 
* [ ] Need to modify the text label to correct spacing at the top of the Resource Specific Metadata tab. It should read "Select a time series to see corresponding metadata (Number of time series: 1):"
* [ ] This one is more of an observation - Variable names in an ODM2 database that have commas in them get split into multiple keywords upon upload. For example, "Solids, total suspended" gets split into "Solids" and "total suspended".  I think this is something the user can fix after the fact.

I don't think any of these are deal killers for the current deployment, so I am going to check the box for time series.

**Comment by pkdash** [comment]
@Horsburgh I will fix the above issues in current phase-2 implementation.  I am getting a 403 error when I try to access your timeseries resource on beta.

**Comment by mjstealey** [comment]
> I am getting a 403 error when I try to access your timeseries resource on beta

Due to PRs beta was rebuilt this morning, so it's possible that the resource was destroyed if it were created prior to then.

**Comment by pkdash** [comment]
@Horsburgh Yes I can access it now.
