### ISSUE TITLE
Alpha testing feedback 

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#140]
- [ ] \(YES)[#110] Suggestion: Don't use concatenated words like "don't." For example on the log in/sign in page the text should read, "If you don't have an account you can join HydroShare now. You can also reset your password if you've forgotten it." Consider replacing "don't" and "you've" with "do not" and "you have".
- [ ] \(Maybe) DGT suggests after logging in to go directly to the Resources page. After logging in the message is shown "successfully logged in". This should say, "Successfully signed in." instead.
- [ ] \(YES) [#111] \(v 1.3.0) Clicked "Make Public" on my new resource (called "Software framework for inverse modeling...") and got a *hard crash* "String index out of range"
- [ ] \(YES) [#111] \(v 1.3.0) Tried adding a second "creator" and got a hard crash "IndexError string index out of range"
- [ ] \(Next Release) Ordering of authors is weird. At a minimum replace the text box with a drop down list.,
- [ ] \(NO) On resource editing page, there should be a single "Save all edits" button.
- [ ] \(Maybe) If we keep the email then make it a hyperlink.  DGT.  See above.
- [ ] \(Next Release) Select latitude and longitude from a map instead of typing it in
- [ ] \(Maybe - Creators not always HS users) Under "Creator" box, the user names should be links to their profile pages.  DGT.  Note that the HydroShare identifier URL provides a link to HydroShare user profiles for Creators that are HydroShare users.  This enhancement to be addressed as part of Style Changes Mauriel is doing. 
- [ ] \(Needs Disc) Consider removing "Science" from "Science Metadata".  DGT suggests remove the header altogether for this release.  The subheadings Title etc speak for themselves.  But really this should be addressed as part of the style changes Mauriel is working on. With this suggestion make this a next release item. 
- [ ] \(YES) [#110] On the bottom of the "About" page where you confirm your account and add your metadata about yourself, there is a sentence "Tell the Hydroshare community..." S should be upper case in HydroShare.
- [ ] \(YES - Please provide appropriate grammar) "The name of the organization you work for." This is wrong grammar.  DGT suggests remove the text altogether for this release.  "Organization" speaks for itself.
- [ ] \(YES)[#110] Phone 1 data should come before Phone 2 data. 
- [ ] \(Needs Disc) "Update Profile" button should say, "Save updated profile information".  DGT suggests go ahead and do this - as a YES or Maybe.  Dont need to discuss this.
- [ ] \(Maybe) Replace button on profile picture doesn't work.
- [ ] \(Maybe) Adding a picture to your profile makes a massive pic. 
- [ ] \(Maybe) Click the "replace photo" button then Removing a profile picture shows an error which doesn't make sense: "Please either submit a file or check the clear checkbox, not both."
- [ ] \(YES - Check with Dave)[#110] Replace "Go Social" with "CUAHSI Social Networks". "Go Social" doesn't really mean anything.  {02/06/15: DGT change this to: "Follow"}
- [ ] \(YES)[#110] Generic Hydroshare resource should have an uppercase "S" in HydroShare.
- [ ] \(Needs Disc - eg. Twitter?) Let's remove "web site" from the comment box. Why do we need to give a web site? Most people don't have a web site. DGT suggests no need to discuss.  Just remove it.  This has been a repeated suggestion.
- [ ] \(Needs Disc - mezzanine is a PITA) When adding a comment, you should not be able to edit your name or email address.  No need to discuss whether to do it.  This has been a repeated suggestion and we should just find the most effective way to do it.

**Comment by dtarb** [comment]
Closing.  Many of these issues have been addressed with beta and new alpha deployments.  Perhaps not all.  @danames feel free to re-raise items that are not addressed when reviewing the alpha 1.4 deployment.
