### ISSUE TITLE
1.7.5/1.8.0 - Release Checklist

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1402]
This is the manual pre-deploy checklist for version 1.7.5.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.
**Please finish checking before Sept. 7th, 2016**

### New Features and Enhancements
- [x]  #1343 IRODs bag creation async [Hong]  @hyi 
- [x]  #1393 HydroShare system level service account  [Michael] @mjstealey 
- [x]  #1395 Ref time series output log fix [Drew] @zhiyuli (verified by @mjstealey )

### General functionality

- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey

#### Resources

- [x] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [x] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade 
- [x] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli

**Comment by mohamedmorsy** [comment]
@hyi this issue #1140 still exists on this version.

**Comment by hyi** [comment]
@mohamedmorsy Have not got the chance to work on that issue #1140 yet, will try to fix it in the subsequent deployment.

**Comment by mohamedmorsy** [comment]
@hyi Thanks!

**Comment by mohamedmorsy** [comment]
@pkdash For the SWAT Model Instance resource edit mode view, The "Resource Specific" tab includes the ability to added extended metadata entry which should be included under the separate tab "Extended Metadata". 

![image](https://cloud.githubusercontent.com/assets/5543781/18319995/1d6ea558-74f6-11e6-9c99-f45e7dde4ccd.png)


The "Extended Metadata" tab content is exactly the same as "Resource Specific" tab content

![image](https://cloud.githubusercontent.com/assets/5543781/18320028/35e8aac0-74f6-11e6-9a4a-53cb5f847ba4.png)

**Comment by pkdash** [comment]
@mohamedmorsy Is this happening on beta? How does it look on www?

**Comment by mohamedmorsy** [comment]
@pkdash I can see this issue on www and beta. The other model resources look fine.

**Comment by pkdash** [comment]
@mohamedmorsy Then I will assume this is not a show stopper for release 1.7.5.  Create a GitHub issue and see if you can fix it.
