### ISSUE TITLE
Manual pre-deploy checklist for version 1.7.6

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1466]
This is the manual pre-deploy checklist for version 1.7.6.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.
**Please finish checking before Sept. 28th, 2016**

### New Features and Enhancements
- [x]  #1233 Constrained group description height [Mauriel] @mauriel133  
- [x]  #1403 Collection resource type enhancement [Drew] @zhiyuli 
- [x]  #1453 Make URLs in Resource abstract clickable [Hong] @hyi 
- [ ]  #1447 MODFLOW resource icon fix [Mohamed] @mohamedmorsy 
- [x]  #1458 NetCDF resource bug fix [Tian] @gantian127 

### General functionality

- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey
- [x] Resource creation from iRODS with a file larger than 1GB [Ray] @rayi113 

#### Resources

- [ ] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [x] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade 
- [x] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli

**Comment by mohamedmorsy** [comment]
@mjstealey I have only this issue #1469  and that for creating a new version of an existing resource types.

**Comment by mjstealey** [comment]
> @mjstealey I have only this issue #1469

@mohamedmorsy I looked at the files in iRODS and was confused by what is supposed to be going on there. Seems to be nested resource GUIDs in a somewhat unorthodox manner... Have left a comment with `ils` information in the issue itself.
