### ISSUE TITLE
Manual pre-deploy checklist for version 1.8.0

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1519]
This is the manual pre-deploy checklist for version 1.8.0.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.
**Please finish checking before Nov. 9th, 2016**
### New Features and Enhancements
- [x]  #977  File folder structure[Mauriel] @mauriel133
- [x] #1474  Resource download bug fix [Hong] @hyi   
- [x]  #1451  Collection resource type enhancement [Drew] @zhiyuli 
- [x]  #1465  Web App resource type enhancement [Drew] @zhiyuli  (Test passed on beta. Need to manually create webapp homepage url for each webapp resource on www once deployed)
- [x]  #1414  Geographic feature resource type bug fix [Drew] @zhiyuli 
- [x]  #1485  Model Instance bug fix  [Tony] @Castronova 
- [x]  #1371  SWAT Model Instance bug fix [Sadler] @jsadler2 
- [x]  #1471  MODFLOW Model Instance bug fix [Sadler] @jsadler2 
- [x]  #1407  Add missing term definition [Mohamed] @mohamedmorsy 
- [x]  #1425  REST API for resource map  [Pabitra] @pkdash 
   -  Did test the new REST endpoint from the web interface and seems to work. However, hs_restclient has not been tested. 
- [x]  #1389  REST API for key/value pair metadata creation [Tian] @gantian127 
### General functionality
- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey
- [x] Resource creation from iRODS with a file larger than 1GB [Ray] @rayi113 
#### Resources
- [x] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [x] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade 
- [ ] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli

**Comment by gantian127** [comment]
@mauriel133 I found an issue #1521 for the file upload of the raster resource type. Would you please have a look at it when you get time? Thanks.

**Comment by dtarb** [comment]
See #1526 related to buttons activating.

**Comment by dtarb** [comment]
I wanted to test whether our apps (such as HydroShare GIS) could find files that are in folders.  However I am unable to test this because when an resource in beta.hydroshare.org is opened with HydroShare GIS App (and perhaps others) it attempts to retrieve the resource from www.hydroshare.org where it may not exist (and if it does exist does not have folders). @danames @zhiyuli @shawncrawley is there a way to set up testing so that beta and other development machines act on appsdev for testing and www acts on apps, and that we coordinate deploys where needed.

**Comment by rayi113** [comment]
@dtarb Please try it now after refreshing your browser.  I changed Mezzanine "Pages" -> "Apps" to point to appsdev instead of apps on Beta.  Appears to work.  @danames @zhiyuli @shawncrawley @mjstealey

**Comment by dtarb** [comment]
@rayi113 that does not solve the problem.  This redirects the Apps tab at the top to Appsdev but does nothing to the app links in the Open with button on specific resources that draws content from the particular app instance resource for each app.  I can and did somewhat painstakingly recreate an app instance with settings the same as the app instance resource pointing to appsdev to try test this, but when I test this I still receive an error "resource does not exist on www.hydroshare.org".  The app is hardwired to look for its content on www.

**Comment by shawncrawley** [comment]
@dtarb I know that in order for the apps (such as HydroShare GIS) to act on resources located somewhere other than www (such as beta), the following steps must be followed:

1. Make sure Tethys Platform on appsdev is configured to point to beta by
changing file /usr/lib/tethys/src/tethys_services/backends/hydroshare.py to replace all occurrences of "www.hydroshare.org" with "beta.hydroshare.org" (should be 3 places).
2. Change all hard-coded "www" to "beta" in each tethys app's code on appsdev

I can write code to programatically detect which server my app is running on and then dynamically generate the appropriate endpoint (www or beta or whatever). However, this solution can only "pair" an app with one endpoint at a time per server. I cannot somehow tell my app on appsdev to work with beta, riverdev, and playground, for example. So if we could choose one main testing branch that we generally want paired with apps on appsdev then we can do that. If in a more rare case we want the apps to point to a random hydroshare test branch, then we'd have to go in and manually change that endpoint for all of the apps.

**Comment by rayi113** [comment]
@dtarb I understand the issue now better and changed Mezzanine "Pages" -> "Apps" back to point to apps and defer to @shawncrawley solution.

**Comment by shawncrawley** [comment]
@dtarb Additionally, each Web App Resource on the HydroShare test server would need to be manually edited to have its app URL endpoint directed at appsdev.

**Comment by mjstealey** [comment]
@dtarb, @rayi113, @shawncrawley - There is a deeper context to what is being discussed here and that is code hardening, testability, and robustness for arbitrary deployments. The assumptions made by the apps team have been spot-on thus far as research endeavors, but as we move closer to the end of this funding cycle we'll need to take a close look at what is necessary for a sustainable HydroShare and the core components such as Tethys that are vital to it. We could take an initial pass at this during the Monday call to better identify these components, and what ultimately needs to be in place prior to a CUAHSI handoff. We're fortunate to have active CUAHSI collaborators onboard this early in the game and should leverage it for everything it's worth.

Some items to kick-off the conversation:
- full stack CI / CD (including apps)
- failover
- load balancing
- internal SLA's for site maintenance and scheduled downtime

**Comment by dtarb** [comment]
I know that this apps testing is a hard problem, but it is something that the apps team needs to tackle.  I'll put the items Michael listed on the agenda for an upcoming call.  There are two strategies that I think should be considered in app testing.
1. Have an app use the name of the machine that makes a request to it to retrieve content.  This may make apps more robust as they would not have to depend on one hard coded machine.
2. Use appsdev as a testing site for all development machines and apps as the site for production.

I do not think we should wait for this for the current deploy, but would like @danames to coordinate a strategy for some level of apps testing for the AGU release.

**Comment by danames** [comment]
Optimally we would NOT Have appsbeta, appsplayground, apps* etc. because of
the huge maintenance effort involved. But rather we should just have 2 apps
deployments. apps and appsdev. We should have a global variable in appsdev
that can be changed to indicate which hydroshare to point at. Then when
someone is testing appsdev, they would send an announcement to the
developer list saying that they are changing the appsdev portal to use, for
example, beta.hydroshare.org for a certain period of testing. Then they
would be responsible to point it back at dev.hydroshare.org when done
testing. If this approach is acceptable then we will approach the tethys
developer team about how to make this a developer setting in our instance
of the tethys portal. -  Dan

**Comment by zhiyuli** [comment]
@dtarb @danames @rayi113 @mjstealey @shawncrawley 

We already have A and B set up. Do you want to set up C or D, or both?

A) production apps (apps server)  paired with production hydroshare (www)
final production

B) development apps (appsdev server) paired with production hydroshare (www)
test new features/changes of apps by assuming hydroshare is unchanged.

C) production apps (apps server) paired with development hydroshare (beta, dev, playground) ???
test new features/changes of hydroshare by assuming apps are unchanged.

D) development apps (appsdev server) paired with development hydroshare (beta, dev, playground) ???
test whether both the two changed factors still work together or not

Some thoughts:
1) We maintain two versions for each app, one on apps server (corresponding to A), one on appsdev sever (corresponding to B) respectively. They are all wired to www.hydroshare.org as we assumed www is always stable and trustable. So under this assumption, app itself is the only factor that is changing, which helps isolate issues.

2) OAuth login on both apps and appsdev are set to authenticate against www.hydroshare.org. After authentication, www gives a token to apps or appsdev, so apps or appdev can use this token to access resources stored on www on behalf of a certain www user. I am thinking (but I am not sure) apps may not be able to use this token returned by www to access resources store on beta or dev. (But I am sure token returned by hydroshare cannot be used in facebook...). So if we want to enable (C) and/or (D), we may need to add more OAuth login options and let user choose from: HydoShare-www, HydroShare-dev, HydroShare-beta and...

3) The metadata of webapp resource on hydroshare decides from where to launch an app. If you want to launch an app from appsdev server, you should create a new webapp resource and put "https://appsdev.hydroshare.org/apps/APP_NAME/" in its metadata.

4) if enable C, we would like to have a new tethys server for it because several apps are using db and geoserver hosted on apps server,  testing may mess up data in them and affect the use of A.

**Comment by danames** [comment]
Drew, for now let's just permenantly point appsdev at beta.hydroshare.org
resources.

**Comment by zhiyuli** [comment]
@danames 
OK. appsdev can authenticate against beta through OAuth now. 
![image](https://cloud.githubusercontent.com/assets/10070599/20126600/be69da62-a5f3-11e6-84bc-2b6599563c3b.png)

Next steps:
1) All apps are currently hard coded to read data from www regardless of OAuth sources. We need to make them aware of different OAuth sources from which users have logged in. If the user logs in Tethys from beta OAuth, they should retrieve data from beta in all following operations.

2) On beta, we need to create a 'twin' for each existing webapp resource, but their "app urls" should point to appsdev instead of apps. Since resources created on beta do not persist, we may need to create those "twin webapp resources" on www and then re-deploy beta using www data. So they can persist on all future beta deploys.

P.S. The reason I do not fully support this approach is that appsdev has development/unstable/experimental version of each app. But our initial purpose was to test changed hydroshare (beta) with unchanged apps.

**Comment by mohamedmorsy** [comment]
MODFLOW model instance does not have " open with JupyterHub" like the other model instances

**Comment by pkdash** [comment]
@dtarb and @alvacouch Not sure how I should be testing the issue#1424. Since the rest client has  not been updated to use this new endpoint, I can test the rest endpoint directly. If we can wait until this Friday, I am be able to update the rest client to test this.

**Comment by dtarb** [comment]
@pkdash did you mean #1425.  A REST call such as https://beta.hydroshare.org/resource/3927b13e68ae46188f620b0e7f331993/data/resourcemap.xml retrieves  the file, so this seems to be working.  Also a check on a private resource without being logged in results in a forbidden error which is correct, and a check with an incorrect GUID results in a not found error, also correct.  I think this is sufficient for "manual" checks.  It would be good to update the REST client asap, but the deploy does not have to wait for this.  The deploy should only be held up for restclient functions that may get broken by the deploy, not the need for new ones not there yet.

**Comment by pkdash** [comment]
@dtarb Direct REST call for retrieving resource map xml document:
https://beta.hydroshare.org/hsapi/resource/3927b13e68ae46188f620b0e7f331993/map

**Comment by dtarb** [comment]
@mohamedmorsy  the "Open with" functionality is not code related.  It is set by the owner of the web app resource.  In this case Dandong Yin owns the JupyterHub-NCSA resource https://beta.hydroshare.org/resource/80d9f3b4bc914628a2d1df4ebebcc3fd/ that can open raster and generic resources, and @Castronova owns JupyterHub-USU https://beta.hydroshare.org/resource/c14f0964c3d34449becda723f3ffa3a3/ set to open several supported resource types.  These owners would need to change the resource settings (on www not beta if they are to persist).  

But there is also a question as to whether you want Jupyterhub to open these model instance resources.  Can it do anything with these resources.

**Comment by Castronova** [comment]
@dtarb @mohamedmorsy @zhiyuli   The **MODFLOW** model instance is not listed as resource type that can be selected on the **WebAPP** edit page, see screenshot below from the *JupyterHub-USU [beta]* resource:

![image](https://cloud.githubusercontent.com/assets/4822372/20190493/a33bf150-a74f-11e6-891a-3e1f4e609585.png)

**Comment by mohamedmorsy** [comment]
I found a bug with the MODFLOW model instance resource related to the "Add Model Input" button  which also prevent from creating new version of the resource type. I will create an issue regarding this bug. This should not have any effect on this deployment.

**Comment by horsburgh** [comment]
@pkdash - In testing time series resources I found a couple of things that I think could be better. They shouldn't hold up this getting merged or deployed, but I'm noting them here as I think they could be easy fixes:

1. The message that pops up and states that the "SQLite file is out of sync with metadata changes" should read as follows:

"The SQLite file is out of sync with metadata changes. Access the "Resource Specific" metadata tab in editing mode to update the SQLite file with metadata changes you have made."

2. When I create a resource it tells me what is still required to make the resource public. Then, I go into edit mode and that list remains at the top of the screen, but turns yellow. Then, I add all of the necessary metadata elements and the green "Sufficient to make public or publish" message appears. But, the yellow notification at the top listing all of the elements I originally needed never disappears. I have to click to close it or go out of edit mode. It should probably disappear at the same time the metadata become sufficient to make the resource public.

**Comment by pkdash** [comment]
@horsburgh 

> When I create a resource it tells me what is still required to make the resource public. Then, I go into edit mode and that list remains at the top of the screen, but turns yellow. Then, I add all of the necessary metadata elements and the green "Sufficient to make public or publish" message appears. But, the yellow notification at the top listing all of the elements I originally needed never disappears. I have to click to close it or go out of edit mode. It should probably disappear at the same time the metadata become sufficient to make the resource public.

The above is general problem with any resource type. @mauriel133 Can easily fix it.

**Comment by mjstealey** [comment]
Remaining fixes should be added as new issues and assigned to [AGU milestone](https://github.com/hydroshare/hydroshare/milestone/14)

Reference to #1620 for follow up
