### ISSUE TITLE
1.9.0 AGU proposed items

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1543]
Edited by @dtarb to distill team requests to a prioritized list (11/10/16).  Original brainstorm list retained in first commend below.

#### Core
- [x] Label group deactivation delete #1462 (Pabitra)
- [x] User name issues #1514, #973 (Hong)
- [x] Web app launchable from own landing page (to support discovery of NWM apps) #1465 (Drew)
- [x] Author names to accommodate organizations #855 (Mohamed, Mauriel)
- [ ] Sundry small bugs  #1146, #1147, #697, #1061
#### Apps
- [ ] Jupyter Notebooks quality check #1567
- [ ] HydroShare GIS bug fixes  #1511, #1157
#### Documentation
- [ ] Help pages #1534 #1560 #1561 
- [ ] Quota policy stated on policies page in pages.hydroshare.org #1566

### If Possible
- [ ] REST client updated to sync with API (DGT lowered priority.  Do any AGU show items depend on this)
- [ ] Folders and the API functions to act on files in folders #1495 (Alva.  DGT lowered priority - Jeff do we need this for AGU)
- [ ] Function to create a copy of a resource #1029
- [ ] Composite resource with raster and generic logical file types #1126, #1034
- [ ] Reference time series #1570 
- [ ] Add reference time series logical file type to composite resource #1571
- [ ] Add geographic raster logical file type to composite resource #1477
- [ ] Add multidimensional logical file type to composite resource #1572
- [ ] Add time series logical file type to composite resource #1573
- [x] Ongoing improvements to discover map interface  #1544, #1517, #1479
- [ ] Email to groups #1362
- [ ] Quota policy implementation #1566
- [ ] Square up group icons layout #1568
- [ ] Square up apps icons layout #1569
- [ ] Modflow auto metadata extraction #1428
- [ ] Home page improvements #1554
- [x] Remove "map results" ambiguous button #1563
- [ ] Use tracking to be able to see what happens at AGU #1577

### If the above are all done look at issues on the 1.10.0 milestone list.
- [ ] Resource landing page appearance and layout improvements #1052 #1555 #518
- [ ] Sundry small bugs #1424

**Comment by dtarb** [comment]
Original brainstorm list


This release to focus on functionality for AGU 2016. 

Christina 
- [ ]  Wants to be able to invite non users to be owners of resources. (Issue #)  DGT.  Needs significant machinery.  Too much.
- [ ] Possibly add to manage access a get shareable link to send. (Issue #).  DGT.  Too major a change.  Defer.
- [ ] Through OAuth use Google accounts.  (Issue #).  DGT.  Too major a change for AGU.  
- [ ] Make groups icon layout equal height/width.  (Issue #).  Make an issue and put on 1.9.0 medium priority.

Dan.  
- [ ] Map Search. (Issue #).  Map and map results and discover are confusing.  How can we make this simple for users.
- [ ] Folders. (Issue #).  Current beta.  Will need to look at API and what Apps need.  Read files at an app level.
- [ ] HydroShare GIS.  (Issue #) 
- [ ] NWM data access. (Issue #).  Have apps.  Need to document what they do.  Jim also has plan for files in a folder.  

Drew.  
- [ ] Trying to finish dockerizing Tethys. (Issue #).  Benefit is maintenance.  Does not have to happen by AGU.

Hong.  
- [ ] iRODS Federation and unit tests. (Issue [#1292]).  Is there federation functionality that will be shown at AGU.  What is using federation.  
- [ ] Bugs. (Issue [#1514])

Jeff.  
- [ ] Make sure what we have got is good. (Issue #)  
- [ ] Help content. (Issue #)
- [ ] Usability. (Issue #)

Martin.  
- [ ] Jupyter notebooks - make sure are complete and functional.

Ray. 
- [ ] Clean up icon layout appearance of https://apps.hydroshare.org/apps/; e.g. make icon height/width more consistent. (Issue #)
- [ ] Can more apps from https://appsdev.hydroshare.org/apps/ be added to apps. (Issue #)

Tony.  
- [ ] Issues that will affect new users.  Hardening. (Issue #)  
- [ ] Bugs. (Issue #)

Jon/Mohamed. 
- [ ] Modflow auto metadata extraction.

Pabitra. 
- [ ] Geo Raster File type and Composite Resource type. (Issue #)

Zhaokun.  
- [ ] Discovery AGU. (Issue #)

Tian.  
- [ ] Some refining of Raster and netCDF. (Issue #)
- [ ] Help is important. (Issue #)

**Comment by danames** [comment]
I just added #1563 to essential list to help de-confuse our users.

**Comment by gantian127** [comment]
@mjstealey  I found the code for #1615 was merged by pull request #1621. But now it is not in develop branch and the bug shows up again.

**Comment by mjstealey** [comment]
> But now it is not in develop branch and the bug shows up again

Intersting is that your commits do not appear in the provenance of that file: https://github.com/hydroshare/hydroshare/commits/develop/hs_core/models.py 

What I suspect happened is that you and another developer worked on the same file and the changes you made were overwritten or reverted. This can occur if a developer doesn't pay close attention when resolving a conflict in the code. It is all to easy to simply bulk replace their changes over top of a more recent commit than what they have locally. Then on their commit they can essentially erase history...

Unfortunately the simplest fix would be to redo the work and make a new PR.

**Comment by mjstealey** [comment]
#1727 - for easy reference Release Notes for 1.10.0
