### ISSUE TITLE
Help Page Checklist for AGU 2016

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1693]
This is a list of help pages that need development before AGU (if possible).  Please see [Help  ](https://pages.hydroshare.org/) with the new landing page to orient yourself to the new organization.  I have suggested who will could manage the individual writing assignments, but you can remove yourself or reassign as you like.  **After proofreading, please check your box and @jphuong will upload to the website.** 

- [x] About -Ready, Christina needs to proofread this pile. 

- [x] Introduction to HydroShare - Ready, Christina to proofread

- [ ] Apps - @danames [This Introduction Page needs attention ](https://docs.google.com/document/d/11F8KVIZ35eFfEXXlF4AoyXsEcda7lRvVUz-mxzefZdY/edit)  Please review this [Github Issue 1650](https://github.com/hydroshare/hydroshare/issues/1650)

**List of App Help pages under the Apps Help icon:**

- [x] CUAHSI Time Series Viewer @Lizabrazil  - [this link is to the empty template](https://drive.google.com/open?id=17Bk72Qx2Bl6m_-lHrCw2jBSzsGX-Q_r3h8yF2gocw0U)

- [x] CyberGIS TauDEM App  @dtarb - [@dtarb checked the box to indicate that the template has been filled out, and is ready for proofreading and uploading](https://drive.google.com/open?id=1rAYrKc9A6cE4k9iNLyD6eQqR9lhzbVo40TaWfy3-LTQ)

- [x] Data Rods Explorer @Lizabrazil  - this is ready to go, just needs a proofread by you (please) and review of the demo steps that he outlined. [Here is the link.](https://docs.google.com/document/d/1XD8hyPMu8hGA2Ao3V-FeuiARqPFRCCAgMvfvAQm5Ass/edit)

- [ ] EPA Waters App @danames The credits section just needs to be updated. See comment.  @Lizabrazil  - do you want to proofread and check the demo steps? [Here is the link.](https://docs.google.com/document/d/1FBAm6uC6k31cgT1_w9Wc_tosezy7QRryNR2aaR4g9lA/edit)

- [ ] HydroShareGIS - @danames and @shawncrawley   Great start on this! [Here is the link. ](https://docs.google.com/document/d/1X9ZHO_X3gk49F9SzFl_t-LFHOvBvsHpeiVJp-IR-9Q0/edit) I suggest fewer steps and a few screen grabs that are easy to convert into a demo.  Can you let @Lizabrazil know when it is ready to review? 

- [x] National Water Model Data Explorer App - @Lizabrazil   - do you mind reviewing this so you are familiar with what it does? It will not be a demo, but it has specific steps for users to download the data from HydroShare (rather than just view it).  [Here is the link.](https://docs.google.com/document/d/1UWsURdUooVGOqKvWwsGhNb4yW7wWyEOz48AAfZkqsXc/edit)

- [x] National Water Model Forecast Viewer - @dtarb and @danames we are waiting for Jim Nelson and Christian Kesler to finish a deadline - but they also need to get added to Github to see this.  [There is a draft text here.](https://docs.google.com/document/d/14U6XHw1YN_d3dYfXPNsPNOjHSOI3qQuiAMYPzhgqDWM/edit)
[National Water Model Upload to HydroShare: Broken Apps #1626](https://github.com/hydroshare/hydroshare/issues/1626)

- [ ] Snow Inspector App - @danames  - @jphuong started populating this but you will need to take this one over please. [Thanks, here is the link. ](https://docs.google.com/document/d/1e3vgBj5XhV290-VEsHhELZM7G06ODcityinA1pLJFKw/edit)

- [x] USGS AHPS Gaugeviewer  @dtarb and @danames we are waiting for Jim Nelson and Christian Kesler to finish a deadline - but they also need to get added to Github to see this.  [There is a draft text here.] (https://docs.google.com/document/d/1FDq6mHGgcu-Tf88sCTeYzyXgyHA2ZmQGr6M4WCKVt-I/edit)   [Github Issue 1627](https://github.com/hydroshare/hydroshare/issues/1627)

**List of Model Help pages under the Model Help icon:**

- [x]  Model Introduction - @dtarb and @Castronova and @vmmerwade and @vmmerwade   -  do you mind taking a look at the Introduction Page? It needs help. [Here is the link.](https://docs.google.com/document/d/1U6EX_wzS6RVASy5tYn-eMkEUMMOGNtd3ZXt0T-lGdcA/edit)

- [ ] Modflow - @goodalljl and @mohamedmorsy 

- [x] SWAT - @vmmerwade 

- [ ] Landlab - Christina and @jphuong 

**Other pages that are not Apps or Models:**
- [ ] Make a New HydroShare Resource using a Python Notebook - @Castronova   

- [ ] @horsburgh  - do you have any requests for updates? or new content needed? We are managing regular updates and requests that Jim P. and Liza and I are going to manage. So if you want something noted, you can add it to this checklist, or we can add it on our Trello to do list for later.
