### ISSUE TITLE
Help Page Update -- Apps review checklist

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1752]
**List of App Help pages under the Apps Help icon:**

- [ ] EPA Waters App @danames The credits section just needs to be updated. See comment.  @Lizabrazil  - do you want to proofread and check the demo steps? [Here is the link.](https://docs.google.com/document/d/1FBAm6uC6k31cgT1_w9Wc_tosezy7QRryNR2aaR4g9lA/edit)

- [ ] HydroShareGIS - @danames and @shawncrawley   Great start on this! [Here is the link. ](https://docs.google.com/document/d/1X9ZHO_X3gk49F9SzFl_t-LFHOvBvsHpeiVJp-IR-9Q0/edit). **Example Uses** should be screen grabs and examples that summarize why this tool is useful.  **Step by Step Example** could be a following heading, and then we can convert these steps into a printable handout.   Can you let @Lizabrazil know when it is ready to review? 

- [ ] Snow Inspector App - @danames  - @jphuong started populating this but you will need to take this one over please. [Thanks, here is the link. ](https://docs.google.com/document/d/1e3vgBj5XhV290-VEsHhELZM7G06ODcityinA1pLJFKw/edit)

**Comment by danames** [comment]
I'm closing this issue because we are going to be changing our approach so that the apps are described in themselves, not in the general HydroShare help page.
