### ISSUE TITLE
Manual pre-deploy checklist for version 1.9.5

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1839]
[beta.hydroshare.org](https://beta.hydroshare.org) last updated on: **Feb, 15th, 2017**

This is the manual pre-deploy checklist for version 1.9.5.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.

**Please finish checking before Feb. 13th, 2017**

**Note:** Version 1.9.5 includes major code clean up (mostly dead code).  If you are responsible for testing a specific resource type, test that the existing resources of that type behave as expected. Then also test with creating a new resource of that type.  
### New Features and Enhancements
- [x]  #1800   Username lockout from update [Hong] @hyi 
- [x]  #1771   Raster resource creation using file from user zone [Hong] @hyi 
- [x]  #1807   requires.io badge [Michael] @mjstealey 
- [ ]  #1804   Get file type metadata ajax call error [Pabitra] @pkdash  
- [x]  #1824   Resource deletion issue [Hong] @hyi 
- [x]  #729   Resource edit permission check [Pabitra] @pkdash 
- [x]  #1797  robot.txt [Michael] @mjstealey  
- [x]  #1473 Help text for timeseries metadata editing [Pabitra] @pkdash 
- [x]  #1799   Remove use of pickle by celery [Hong] @hyi 
- [x]  #1691   Resource title with non-English characters [Pabitra] @pkdash 
- [x]  #1652   Version inconsistency [Hong] @hyi 
- [x]  #1788  Creator rules obey [Mark] @aphelionz 
- [x]  #1795  MODFLOW xml generation fix [Mohamed] @mohamedmorsy 
- [ ]  #1764   Icon for SQLite file [Mauriel] @mauriel133  
- [ ]  #1770   File browse button [Mauriel] @mauriel133 
- [x]  #1699   Better icon for manage access [Jeff] @jsadler2 
- [x]  #1786   Temp directory setting [Mark] @aphelionz 
- [x]  #1792   Resource publish error [Hong] @hyi
- [x]  #1777   Composite resource file copy and paste [Pabitra] @pkdash
- [x]  #1743   Keywords editing improvements [Pabitra] @pkdash
- [x] #1601   Versioning issue with SWAT and MODFLOW [Mohamed] @mohamedmorsy (WebApp checked )
- [x] #1852  Access control break/leak [Pabitra] @pkdash 
- [ ] #1052  Coverage map layout changes [Mauriel] @mauriel133 
- [x] #1822 Ref timeseries resource creation fix [Drew] @zhiyuli 
- [x] #1838 Resource cleanup in unit tests [Hong] @hyi - Note that unit tests are not run on beta or www production, so this PR should not affect functionalities on www, and has already been verified by Jenkins check.
- [x] #1862 Some unit tests are skipped by Jenkins [Pabitra] @pkdash

### General functionality
- [ ] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey
- [x] Resource creation from iRODS with a file larger than 1GB [Ray] @rayi113 
#### Resources
- [ ] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [ ] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [ ] Multidimensional (NetCDF) [Tian] @gantian127  
- [x] Model Program [Tony] @Castronova 
- [x] Model Instance [UVA] @goodalljl 
- [x] SWAT Model Instance [Purdue] @vmmerwade 
- [x] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli 
- [x] Composite [USU] @dtarb

**Comment by dtarb** [comment]
#1852 is a must fix before 1.9.5 deploy

**Comment by mjstealey** [comment]
1.9.5 deployed to production
