### ISSUE TITLE
Manual pre-deploy checklist for version 1.9.6

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1926]
This is the manual pre-deploy checklist for version 1.9.6.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.

**Please finish checking before Mar. 15th, 2017**
 
### New Features and Enhancements
- [x]  #1920 Replicate resource bag [Hong] @hyi 
- [x]  #1858 iRODS file size [Hong] @hyi @dtarb checked this. 
- [x]  #1906, #1830 authentication and security issues [Michael] @mjstealey 
- [x]  #1710 access control issues [Pabitra] @pkdash
         Resources are still not getting listed in my resources page if the user has access to the resource via group access. 
- [x]  #1855 Auto approve group member  [Pabitra] @pkdash  
- [x]  #1893, #1735 User tracking issues [Tony] @Castronova 
- [x]  #1921 NetCDF file icon [Mauriel] @mauriel133  
- [x]  #1323 Delete multiple resources [Mauriel] @mauriel133 
- [x]  #1671 Upload to subfolder  [Mauriel] @mauriel133
- [x]  #943 Changing author order  [Mauriel] @mauriel133
- [x]  #1871 GeoTrust REST Endpoint request [Mark] @aphelionz 
- [x]  #1894 Upload file to folder [Mark] @aphelionz 
- [x]  #1834 REST API for unzipping files [Mark] @aphelionz 
- [x] #1557 Add flexibility to MODFLOW model instance [Mohamed] @mohamedmorsy

### General functionality
- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey
- [x] Resource creation from iRODS with a file larger than 1GB [Ray] @rayi113 

#### Resources
- [x] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames 
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  
- [x] Model Program [Tony] @Castronova @goodalljl 
- [x] Model Instance [UVA] @goodalljl 
- [x] SWAT Model Instance [Purdue] @vmmerwade [apps]
- [x] SWAT Model Instance [UVA] @goodalljl [creation, update, and new versions] 
- [x] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli 
- [x] Composite [USU] @dtarb See #1928 for errors from testing composite resource. [I also found #1953, but I do not want that to delay deploy.]

**Comment by dtarb** [comment]
See #1927 for an error I received in testing.  This may relate to #1920.

**Comment by pkdash** [comment]
@alvacouch and @dtarb 

I am testing access control mainly the undo functionality. Here are the results. I am not sure if this is the expected behavior:

User *A* (resource owner) granted view permission to user *B* and edit permission to user *C*. Then *C* granted edit permission to *B*. Now when *C* tries to change permission for *B* back to view, system does not allow that and says   **'Non-owners can't decrease privilege of others'**.  If *C* tries to delete existing edit permission (click on X) of *B*, system says **'You don't have permission to remove this sharing setting'**. I was expecting it to go back to original view permission granted by user *A*

**Comment by dtarb** [comment]
I found the same behavior as @pkdash and agree that it is inconsistent with our policy.  Since C granted edit permission to B, C should be able to remove this and have the permission revert back to the view permission granted by A.

**Comment by pkdash** [comment]
@aphelionz Zipping of folder seems to be failing due to the same reason (attribute error on accessing ```request.data```)  as of renaming/moving of file or folder (issue #1928).

**Comment by aphelionz** [comment]
@pkdash @dtarb This is fixed in PR https://github.com/hydroshare/hydroshare/pull/1937. Waiting for jenkins and I will merge the approved pull request.

**Comment by aphelionz** [comment]
@dtarb tested my endpoints again - @hyi found a big but resolved it. However, that bug fix is in the quota PR. @hyi should we pull that fix out into its own PR so it can land in 1.9.6?

**Comment by horsburgh** [comment]
@mauriel133 - I've just started testing 1.9.6 on beta.hydroshare.org. When I make my window narrow, there's some weird stuff happening with the sign in link. It ends up on a new line and then the horizontal divider crowds the text below.

Testing in Chrome on my Mac:

![image](https://cloud.githubusercontent.com/assets/3485902/24013797/2faee0f6-0a48-11e7-9f30-6674423afe00.png)

**Comment by hyi** [comment]
@aphelionz I fixed a bug with REST test for deep unzipping in my quota PR. Is that what you meant by the bug I fixed? Since the fix is only for REST test, I am thinking it should not affect the actual endpoint functionality. Perhaps you meant something else?

**Comment by aphelionz** [comment]
@hyi Oh, ok. Thanks for the clarification. I guess I was confused. @dtarb All set here then.

**Comment by mjstealey** [comment]
deployed
