### ISSUE TITLE
Manual pre-deploy checklist for release 1.10.0

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2037]
This is the manual pre-deploy checklist for version 1.10.0.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.

**Please finish checking before May, 3rd, 2017**
 
### New Features and Enhancements
- [x]  #1955 Resource access control (undo permission) [Mauriel] @mauriel133  
- [x]  #74 Resource creation revamp [Mauriel] @mauriel133  
- [x]  #1988 File icon for Ref TS [Mauriel] @mauriel133
- [x]  #1996 Navigation Bar logo [Mauriel] @mauriel133 
- [x] #1900 Inline JS refactor [Mauriel] @mauriel133 
- [x] #1977 Composite resource type -default resource type [Mauriel] @mauriel133 
- [x]  #1976 File type keywords [Pabitra] @pkdash
- [x]  #1975 Message for missing file type metadata [Pabitra] @pkdash
- [x] #1687 Resource File API [Alva] @alvacouch 
- [x] #2000 Fix for bag flag [Alva] @alvacouch 
- [ ]  #2025 File URLs bug fix [Alva] @alvacouch 
- [ ]  #1999 Resource file API bug fix [Alva] @alvacouch 
- [x]  #1566 File quota [Hong] @hyi 
- [x]  #1815 Model program bug fix [Jeff S] @jsadler2 
- [x]  #1924 NetCDF metadata editing in file [Tian] @gantian127 (hotfix #2088)
- [x]  #1933 Web App Resource icon [BYU] @zhiyuli 
- [x]  #1947 Discovery of non-core meta [Zhaokun] @xuezhaokun 
- [x] #1871 REST endpoint for listing resources based on spatial coverage [Mark] @aphelionz 
- [x] #1998 Discovery suppress finding obsoleted resources where a new version exists @xuezhaokun 
- [ ] #1973 Add about to header and footer @mjstealey See also #2065

### Help documentation on pages.Hydroshare.org
- [ ] General spot check that documentation is consistent with functionality [Christina] @ChristinaB 
- [ ] Documentation for resource creation revamp per #74 [Liza] 
- [ ] Documentation for Access control undo per #1955 [Liza]
- [ ] Documentation for Multidimensional resource and file type metadata editing per #1924 [Liza]

### General functionality
- [x] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [ ] Signing up, signing in and signing out [Michael] @mjstealey
- [x] [Resource](https://beta.hydroshare.org/resource/13b8d83353d144998db2c293598771bd/) creation from iRODS with a file larger than 1GB [Ray] @rayi113 

#### Resources (Note: Due to #74 and #1900 each resource type creation and resource editing needs to be tested with bit more attention)
- [x] Time Series  [Jeff H] @horsburgh Tested, but discovered problems. See: #2070, #2069, #2068, #2067, #2066
- [x] HIS time Series [BYU] @danames 
       (Test that it is not possible to create HIS time series) --- HIS option is missing from creation page
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
       Pabitra: When testing geo feature resource I noticed this issue: #2106 
- [x] Multidimensional (NetCDF) [Tian] @gantian127  (issue #2087, #2086)
- [x] Model Program [Tony] @Castronova @goodalljl 
- [x] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [Purdue] @vmmerwade [apps]
- [x] SWAT Model Instance [UVA] @goodalljl [creation, update, and new versions] tested but discovered bug #2092. It's not critical so will be resolved for next release.
- [x] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli 
- [x] Composite [USU] @dtarb Tested but discovered problems. See #2059, #2064 5/4/17 these have been fixed.

**Comment by mauriel133** [comment]
Below are the issues I've found and will be addressing while doing this pre-deploy checklist.

- Found remains of merge conflicts
![image](https://cloud.githubusercontent.com/assets/2448568/25507099/4e10b76e-2b67-11e7-8d10-88332db57514.png)
- Quota holder text is unreadable
![image](https://cloud.githubusercontent.com/assets/2448568/25507145/98cc0470-2b67-11e7-81cf-0b6c352ac9bd.png)
- Change quota holder button style
![image](https://cloud.githubusercontent.com/assets/2448568/25507712/07d9afb8-2b6b-11e7-9538-e861aba56c1e.png)
- Use quota holder to render manage access interface state. In the example below, the remove buttons should be disabled for the quota holder item.
![image](https://cloud.githubusercontent.com/assets/2448568/25507725/279b7174-2b6b-11e7-8f8d-8ef82794a6e0.png)
- Unable to unshare resource with dynamically added group item
![image](https://cloud.githubusercontent.com/assets/2448568/25507837/8bd66a90-2b6b-11e7-868b-176819898422.png)

**Comment by horsburgh** [comment]
I posted some new issues as a result of my testing of Time Series.

See: #2069, #2068, #2067, #2066

**Comment by dtarb** [comment]
I posted the following issues testing composite resources 
 #2059, #2061, #2062, #2063, #2064

**Comment by mohamedmorsy** [comment]
In the new HydroShare resources list, it would be great if we can have the old arrangement of the model resources: Model Program, Model Instance, SWAT Model Instance, and MODFLOW Model Instance. Also, What about including the resource types categorization too?

![image](https://cloud.githubusercontent.com/assets/5543781/25664123/a9ebb01e-2fe7-11e7-8eac-8246d6496fa5.png)

**Comment by mauriel133** [comment]
Also related: https://github.com/hydroshare/hydroshare/issues/2086

@mohamedmorsy, @dtarb, @horsburgh any ideas for category name for the first section containing Collection, Composite, Generic and Web App?
  
![image](https://cloud.githubusercontent.com/assets/2448568/25667849/06910450-2fe2-11e7-90ab-409a2fee96d4.png)

**Comment by dtarb** [comment]
What about "General", but where is the category name used.

**Comment by aphelionz** [comment]
@dtarb @mjstealey Tested the coverage endpoints. There is a small bug where the subject search is case sensitive but i think we can fix that in the next release

**Comment by mauriel133** [comment]
@dtarb, see https://github.com/hydroshare/hydroshare/pull/2091 for discussion on this change.
