### ISSUE TITLE
Manual pre-deploy checklist for release 1.10.0  (version 2)

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2155]
This is the 2nd version of manual pre-deploy checklist for release 1.10.0.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.

**Please finish checking by the end of June 8th (Thur), 2017**
 
### New Features and Enhancements
- [ ]  #1955 Resource access control (undo permission) [Mauriel] @mauriel133  
- [ ]  #74 Resource creation revamp [Mauriel] @mauriel133  
- [ ]  #1988 File icon for Ref TS [Mauriel] @mauriel133
- [ ]  #1996 Navigation Bar logo [Mauriel] @mauriel133 
- [ ] #1900 Inline JS refactor [Mauriel] @mauriel133 
- [ ] #1977 Composite resource type -default resource type [Mauriel] @mauriel133 
- [x]  #1976 File type keywords [Pabitra] @pkdash
- [x]  #1975 Message for missing file type metadata [Pabitra] @pkdash
- [ ] #1687 Resource File API [Alva] @alvacouch 
- [ ] #2000 Fix for bag flag [Alva] @alvacouch 
- [ ]  #2025 File URLs bug fix [Alva] @alvacouch 
- [ ]  #1999 Resource file API bug fix [Alva] @alvacouch 
- [x]  #1566 File quota [Hong] @hyi 
- [ ]  #1815 Model program bug fix [Jeff S] @jsadler2 
- [x]  #1924 NetCDF metadata editing in file [Tian] @gantian127 
- [x]  #1933 Web App Resource icon [BYU] @zhiyuli 
- [ ]  #1947 Discovery of non-core meta [Zhaokun] @xuezhaokun 
- [ ] #1871 REST endpoint for listing resources based on spatial coverage [Mark] @aphelionz 
- [ ] #1998 Discovery suppress finding obsoleted resources where a new version exists @xuezhaokun 
- [x] #1973 Add about to header and footer @mjstealey (TODO: @mauriel133 on hs_pages side)

### Help documentation on pages.Hydroshare.org
- [x] General spot check that documentation is consistent with functionality [Christina] @ChristinaB 
- [x] Documentation for resource creation revamp per #74 [Liza] 
- [x] Documentation for Access control undo per #1955 [Liza]
- [x] Documentation for Multidimensional resource and file type metadata editing per #1924 [Liza]

### General functionality
- [ ] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey
- [x] Resource creation from iRODS with a file larger than 1GB [Ray] @rayi113 

#### Resources (Note: Due to #74 and #1900 each resource type creation and resource editing needs to be tested with bit more attention)
- [ ] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames (Creation of HIS RefTS is disabled)
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127 
- [ ] Model Program [Tony] @Castronova @goodalljl 
- [ ] Model Instance [UVA] @goodalljl 
- [ ] SWAT Model Instance [UVA] @goodalljl 
- [ ] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli 
- [x] Composite [USU] @dtarb

**Comment by rayi113** [comment]
1.10 released.
