### ISSUE TITLE
Consolidated Issue List

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2166]
# E&O Priority List

**Bugs**
- [ ] Clarify the purpose of Discover search #2215 -- [**Release 1.11**](/hydroshare/hydroshare/milestone/46) 
- [x] Case insensitive and partial word search function needed for all searches #2180 -- [**Release 1.11**](/hydroshare/hydroshare/milestone/46)
     _*Limits resource discovery*_
- [ ] Loading bug with HydroShare GIS #2144, #2185  -- [**Release 1.12**](/hydroshare/hydroshare/milestone/46)
       *GIS app should handle viewing multiple files at a time, instead it breaks- related to #2185* 
- [ ] Resource list needs metadata attribute null checks #2171
      *Corrupted resources break Admin scripts*
- [x] Bags don't download properly for selected resources #2056
      *Corrupted resources need to be fixed- related to #2171* 
- [ ] NWM App Fixes #1716
      *Bugs with clicking on canals, design improvements, and more-need to cut into separate issues.*
- [ ] Limit resource file change operations to one file operation per resource at a time #2122
      *As the system scales we want to prevent file system race conditions.*
---
**Feature Requests**
- [ ] Add Profile requirements to HydroShare new user steps #1915 -- [**Release 1.12**](/hydroshare/hydroshare/milestone/46)
       *Improve usage statistics.*
- [ ] implement automatic email to all new users #2135 -- [**Release 1.12**](/hydroshare/hydroshare/milestone/46)
       *Solicit feedback on system from new users. LBrazil will hash out survey content.* 
- [ ] Searching private resources broken #2214
- [ ] Making release documentation accurate at release time #1967
       *Need a staging site for Help Pages, so it stays in sync with releases.*
- [ ] Folder appearance of file types #1503
       *Add icons to be associated with all major file types that we support.*
---
**Discussion**
- [ ] Delete Published Resources. How do you remove a published (DOI) resource? #1607
      *Users formally publish resources by mistake. How do we prevent & make this more evident in the interface?*
- [ ] Help.HydroShare.org : why pages? #1661
      *Should read as "Help.HydroShare.org"*

## Governance / Documentation

- [ ] Clean up wiki #408
- [ ] Policy and strategy for supporting evolving browsers #473
- [ ] Migrate documentation to readthedocs #2039
- [ ] Help Page Update -- Resource Type: Time Series #1751
- [ ] Help Page Update -- Apps review checklist #1752
- [ ] Help Page Update -- Resource Types: Geographic Feature #1753
- [ ] Description of apps #1559
- [ ] Add functionality description of apps to help page #1560
- [ ] Help Page Update- Collection Resource Type #1758

## Metadata / Metadata Workflow

- [ ] resource specific metadata is missing from resourcemetadata.xml #2248
- [ ] Hydroshare metadata writing back to .nc file #400
- [ ] Hydroshare metadata elements "hsterms" capitlization format #608 -
- [ ] Refactor read_metadata_from_resource_bag() to use importlib instead of __import__ builtin #640
- [ ] Encode sequences in science metadata as sequences in the RDF+XML representation. #658
- [ ] Implement updateScienceMetadata REST end point #723
- [ ] When editing the spatial coverage information, the invalid value can be saved as metadata #733
- [ ] Handle OGC CSW discovery requests #1031
- [ ] File metadata for resources #1034
- [ ] inconsistency between resourcemap.xml and actual access URLs #1483
- [ ] Resolve discrepancies in coordinate system and projection metadata #1518
- [ ] Make it possible to upload and incorporate resourcemetadata.xml files created by others #1598
- [ ] folder deletion code does not delete type-specific resource metadata from Django #1629
- [ ] move file metadata to ResourceFile object #1762
- [ ] Discovery -- insufficient metadata to sort creators by last name #1774
- [ ] Discovery -- insufficient metadata to categorize spatial coverages by geographic region name #1775
- [ ] Creator metadata has insufficient disambiguation for people who are not HydroShare users #1787
- [ ] "Reifying" matters of opinion in RDF #1931
- [ ] Strategies for storage reduction for highly repetitive metadata, including metadata for CUAHSI HydroServer time series. #1987
- [ ] We need to understand how RDF is created from Django #1991
- [ ] Resource specific metadata should not be editable for Geographic feature resource type #2021

### REST API Specific
- [ ] Metadata strings updated through hs_restclient are parsed incorrectly #2247
- [ ] Update docstring in REST endpoint for resource listing #2238
- [ ] Add ability to sort Resources in REST API #2237
- [ ] REST endpoint for updating science metadata missing processing of 'relations' #2109
- [ ] REST API Enhancements to return additional metadata (optionally) #2112
- [ ] REST API for resource metadata update #1423
- [ ] File upload and delete work differently in REST API and UI #2177
- [x] Public endpoint for copying from iRODS user zone needed #2187
- [x] Flag syntax 't' parameter is confusing #2193
- [ ] REST API for resource specific metadata update #2217

## UI / UX Issues
- [ ] When creating new resources, author and owner middle initials are ignored #2276
- [ ] Non-human DOI vetting #2274
- [ ] Group membership request email message: more information needed #2275
- [ ] File Operations Slow, Buggy, and Inconsistent #2266
- [x] moving a public resource to discoverable is currently not working #2256
- [ ] Improve file download interface #2255
- [ ] BagIt creation failure #2253
- [ ] Add page to help on how to create and account #2245
- [ ] Required profile information inconsistency #2242
- [ ] Give HydroShare iRODS Host and User Zone in iRODS sign-in dialogue box #2236 -
- [ ] Have "Create your iRODS user account" on main profile page #2235
- [ ] Broken Resource: Can't download any files or the bag #2226
- [ ] Human in the loop for formal publication #2229
- [ ] For reference time series it is not possible to add users to access control. The interface element is missing #329
- [ ] Comment Reply Emails Unncessary for Your Own Replies #365
- [ ] Look at portal.lternet.edu for ideas on improving resource landing page #518
- [ ] Create "Model Package" button for Model Instance resource types #545
- [ ] Allowing Change of Email #695
- [ ] Profile page followup improvements #741
- [ ] My Resources Page: Limit the List of Resources to My Resources #765
- [ ] Discovery: Create Ability to Add a Discovered Resource to My Resources #767
- [ ] My Resources Page: Additional Toolbar Functionality #771
- [ ] My Resources Page: Enhancements to the Resource Listing #897
- [ ] Resource Metadata: Implement Credit Mapping #941
- [ ] Account Creation - Active/Pending workflow #966
- [ ] Improvements and optimizations on modal windows #967
- [ ] Enhance manage access to generate invitation to join HydroShare #974
- [ ] Add author and contributor to include capability identify existing HydroShare user and then automatically fill out content #975
- [ ] SEO: Include crawlable resource list in profile page w/o JS #981
- [ ] Sorting by owner. Should first or last name be used? #1021
- [ ] Add notifications capability #976
- [ ] Add content redirects away to landing page #1099
- [ ] Open with button to only show apps a user has selected #1161
- [ ] Comment editing desparately needed #1213
- [ ] Profile and Home Page follow up issues #1237
- [ ] Groups: Issue Invitation to Join a Group to a non-HydroShare User #1243
- [ ] User group functionality phase-2 #1260
- [ ] Show local times #1271
- [ ] Add "Log in with Google" functionality #1364
- [ ] Add capability to delete comments #1369
- [ ] Collections mapping and viewing resource relationships #1387
- [ ] Improve consistency in working with people and organizations #1399
- [ ] Resource Landing Page Edit Mode: Required Metadata Message Persists Too Long #1411
- [ ] Error msg should show up when uploading multiple shapefiles to create one Feature res #1414
- [ ] Bulk download of multiple resources #1416
- [ ] Discover map is slow and behavior awkward #1479
- [ ] Improve the relations tab content entry and display #1494
- [ ] Order recent activity in groups from last to first #1505
- [ ] Add capability for a user to delete their account #1565
- [ ] Square up app icon layout #1569
- [ ] Need a right click menu on files to launch apps #1609
- [ ] Refining group capabilities #1632
- [ ] Provide an embargo/rescission period for publication actions #1649
- [ ] User Workflow Feedback - orientation tutorial pop ups to the rescue? #1653
- [ ] Terms of use - Page revamp #1714
- [ ] Discovery improvements #1755
- [ ] Add setting to require agreement to license before manual downloading. #1756
- [ ] My resources filter facet counts #1759
- [ ] "Visualize" button on resource landing page #1776
- [ ] Notifying users of future service outages and changes #1831
- [ ] Improve formatting of reset password page. #1835
- [ ] MOTD - message of the day #1876
- [ ] Google map interface for editing coverage metadata for file types and timeseries resource #1966
- [ ] Add About to Header and Footer #1973
- [ ] Discover interface shows older versions of resources #1998
- [ ] Discovery filter by Resource Type breakpoint display #2016
- [ ] REST API doesn't respond to URLs that REST calls generate! #2030
- [ ] Change HydroShare New Account Message #2033
- [ ] REST endpoint for listing resources should not include obsoleted resources #2045
- [ ] Create resource messages repetative regarding irods #2061
- [ ] Sync up pages.hydroshare.org footer with www.hydroshare.org footer #2065
- [ ] user with EDIT access can undo PUBLIC access but cannot re-institute it. #2080
- [ ] Resource creation page: move the multidimensional resource type icon to the geospatial data type list #2086
- [ ] New Version of SWAT_MI error if dropdowns are blank #2092
- [ ] Add ABOUT to top of pages.hydroshare.org #2093
- [x] File icon needed for .shp file #2107
- [ ] Spatial coverage in composite resource problems #2110
- [ ] Show where (which zone) a resource is stored on resource landing page #2115
- [ ] Beta 1.10: Initial My Resources Page View Needs to Change #2116
- [ ] UI does not communicate errors to user from REST API #2120
- [ ] Timeout issue for large set of file display on resource landing page #2125
- [ ] Display a warning when user removes himself as owner #2127
- [ ] Create New Resource - Design Updates Needed #2136
- [ ] /user throws an error #2164
- [ ] Add error checking to the resource stats command #2189
- [ ] Add education field to user profile #2190
- [ ] Update Quota message text to be more understandable #2196
- [ ] Searching private resources broken #2214
- [ ] Clarify the purpose of Discover search #2215
- [ ] Uploading a file into a resource is not working - files disappear #2216
- [ ] Broken resource - exploded when a new file with existing name was added #2224

## Administration-Level Tickets

- [ ] Email All Email Addresses in HydroShare User Profiles #1867
- [ ] Admin panel to list resources by type #1863
- [ ] User foreign key field does not show up in Add User Quota dialog from admin panel #2131
- [ ] Write management command that allows to change resource GUID #2211

## Usage Tracking

- [ ] App tracking logs shouldn't contain spaces #2267 
- [ ] Scale up usagemetrics.hydroshare.org #2254
- [ ] Activity by location #1581
- [ ] Resource creation by user type #1579
- [ ] Downloaded resources by user type #1580
- [ ] Log app launches #2042
- [ ] User and Resource metrics cannot be filtered with time #2082
- [ ] Active users as default view in Kibana #2094
- [ ] Missing activity data #2151

## Resource File API / Data Bags

- [ ] Incomplete refactor of bag.url for new iRODS BagIt creation workflow #417
- [ ] Implement PUT on Resource Files #132 
- [ ] REST API: Add option to unpack uploaded zipfile on resource creation #485
- [ ] REST API: Add ability to ingest resource from fully formed BagIt archive #486
- [ ] Add REST API call to ingest file already in iRODS #684 
- [ ] Resource creation file validation peculiarity #707
- [ ] REST API needs to support iRODS federation zone for resource creation and adding files to resources #1276
- [ ] download all resources contained in one collection #1304
- [ ] Add Project/Organization Branding to Resource Pages #1555
- [ ] Implement file quota #1566
- [ ] Upload into folder places file at the top level #1671
- [ ] data/contents subpath does not belong in /hsapi/resource/{pk}/functions paths #1956
- [ ] New REST endpoint for setting file type #1993
- [ ] signals are not consistently raised in file/folder operations #2020
- [ ] File URLs incorrect in REST API after ResourceFile fix. #2025
- [ ] Got error when removing multiple folders from Composite resource #2029
- [ ] Completing implementation of logical files #2099
- [ ] Avoid embedding configuration into ResourceFile paths #2104
- [ ] Should be able to rename and/or move some kinds of files in composite resource #2124
- [ ] No resource file gets uploaded when creating a Composite Res through hs_restclient 1.2.8 #2137
- [ ] Allow unzipping of compressed file formats other than zip #2143
- [ ] Improve unzipping performance for zip file with large set of files and complicated folder structure #2153
- [ ] Add check to make sure new quota holder has enough quota #2160
- [ ] Management command to set default logical file for composite resource #2162

## Code-level improvements
- [ ] print names of resource objects #890
- [ ] subclassing QuerySet to integrate resources, access control, and labels #831
- [ ] REST interface to groups is outdated #920
- [ ] Remove Hydroshare Author Group #624
- [ ] Make bag replication to iRODS user zone to call create_bags_by_irods asynchronously #1404
- [ ] Allow using existing units for TimeSeries Result element editing #1472
- [ ] Updates to REST interface #1515
- [ ] Include current python-irodsclient in dev build configuration #1590
- [ ] Django constraints upon resource models are inadequate #1645
- [ ] Add optional author identifiers #1666
- [ ] Fail to share resource #1712
- [ ] django model constraints inadequate #1765
- [ ] Beta 1.10: Editing Site Elevation Throws Error if Decimal #2068
- [ ] debugging really complex user interfaces #2095
- [ ] Incorrect user logged as making automatic changes #2103
- [ ] Lack of REST API decorators causes uncaught exceptions in system log #2123

### Clean Up / Updates
- [ ] Evaluate code redundancy #958
- [ ] Update Django REST Framework to 3.5.3 #1589
- [ ] Multiple resource file endpoints should be consolidated #1548
- [ ] add autopep8 to dev environment #1634
- [ ] Update packages installed from requirements.txt #2017

### Security
- [ ] Update to defused XML packages #659
- [ ] Pass http/https status from nginx to django #1711
- [ ] Turn back on Security Features #2058
- [ ] Explore Default Deny / Default Permit attributes on API #1722
- [ ] Review CORS + CSP #1806
- [ ] Uploaded executable files should be scanned for viruses. #1709

### Testing
- [ ] Unit tests fails occassionally #1433
- [ ] Write unit tests for metadata xml for hs_core #1481
- [ ] Write unit tests for metadata xml for time series resource #1482
- [ ] unit test for post_metadata_update receiver implemented in model instance resources #1507
- [ ] It would really help if stacked build requests in Jenkins were automatically cancelled #1965
- [ ] Make selenium tests work in Firefox #2013
- [ ] Add selenium tests for user registration #2165 

## Resource type-specific issues

- [ ] Inconsistencies in Multidimensional resource type metadata reading #2251
- [ ] Reference Model Program resource to allow publication without content files #856
- [ ] River Geometry Resource Refinements #619
- [ ] Create Workflow Resource Type #748
- [ ] Model Program - Git support #923
- [ ] Script file extensions should not be limited to .r .py and .m only #1030
- [ ] Web App - Edit page enhancements #1093
- [ ] Web App - OAuth Clarification #1094
- [ ] Failed to create a new version for the Model Instance resource type when linked to a specific Model Program resource #1140
- [ ] Unexpected results when searching for Model Instance resource through "Filter by Resource Type" table #1142
- [ ] Lower the barrier for creating new specific Model Instance resource types #1216
- [ ] Query Model Program with the linked Model Instance #1249
- [ ] Feature Res Type: Extract metadata from xml file attached with ESRI shapefile #1421
- [ ] Modflow Model Instance Phase 2 #1428
- [ ] Auto-create WMS/WFS/WCS layer for Raster and GeographicFeature resources #1450
- [ ] Implement delete function for swat model instance #1500
- [ ] Create Geographic Feature Resource Fails #1547
- [ ] Reference time series rework #1570
- [ ] Add reference time series logical file type to composite resource #1571
- [ ] Add time series logical file type to composite resource #1573
- [ ] Update the App Resource Type to include Registering an App to a specific file extension #1610
- [ ] refine webapp resource metadata logic #1673
- [ ] SWAT REST API fails test in federated mode #1724
- [ ] Catalog CSDMS Models in Hydroshare #2019
- [ ] Bulk metadata update for Time Series Resource #2028
- [ ] Geographic feature file type #2036
- [ ] No information on Geographic Feature Resource type in terms page #2057
- [ ] NetCDF resource file validation error #2087
- [ ] Geo Feature Resource creation issues #2106

## Apps

- [ ] HydroShare GIS tiling is not loading #2270
- [ ] HydroShareGIS is not updating changes to attributes #2271
- [ ] HydroShareGIS App - needs polgyon transparent option #2272
- [ ] 
- [ ] Extend Hyrax OPeNDAP server/app to provide access to multidimensional file types in public composite resources #2250
- [ ] Suggested Improvements for EPA Waters App #2234
- [ ] HydroShare GIS app - more efficient way to access cumulative size of resource files #1294
- [ ] Improve the EPA WATERS Services HydroShare App #1315
- [ ] Need to hardwire beta.hydroshare.org to appsdev.hydroshare.org and vice versa #1545
- [ ] National Water Model Upload to HydroShare: Broken #1626
- [ ] Worldwater app directs to a website...not an app #1638
- [ ] National Water Model Data Explorer...is not technically an app #1640
- [ ] USGS and AHPS Gaugeviewer WML broken #1641
- [ ] Apps: Simple Styling Modifications #1642
- [ ] HydroShare GIS features that depend on hs_restclient functionality #1692
- [ ] weird username displayed on apps-tethys home page #1715
- [ ] Enable unlimited, bidirectional file transfer for apps #1842
- [ ] Release management and quality control for apps #1843
- [ ] App-HydroShare I/O consistency and best practices #1848
- [ ] Track app status #2023
- [ ] HydroShareGIS cannot open composite resources #2185
- [ ] NWM Viewer - Missing help for subsetting #2201
- [ ] NWM Viewer - Missing help button #2202
- [ ] NWM Viewer - Toolbar button positions change when screen is maximized #2203
- [ ] NWM Viewer - Subset Watershed button activated when no watershed has been loaded #2204
- [ ] NWM Viewer - Begin time should be constrained #2205
- [ ] NWM Viewer - Form titles revision #2206
- [ ] NWM Viewer - Documentation for Configuration #2207
- [ ] NWM Viewer - Improve Workflow #2208
- [ ] NWM Viewer - Zooms to Kansas Randomly #2209
- [ ] NWM Viewer - Remove Lat Lon coordinates #2210
- [ ] Data Rods Explorer App: Data retrieval is incurring errors from NASA web-services #2222

### SWATShare

- [ ] Implement functions that allow SWATShare users to import SWAT model instance resources from HydroShare #595
- [ ] Develop SWATShare component which can be launched using the Hydroshare app URL convention #597
- [ ] SWATshare model update - pending Error 'Downloading and Extracting the resource failed' #2167

## Candidates to be moved away from github issues

- [ ] JENKINS CI - Developer Deployment Usage #898

## JupyterHub Integration 

- [ ] Sync HydroShare irods userspace on JupyterHub notebook server #1368
- [ ] Jupyter notebook quality check #1567
- [ ] JupyterHub-NCSA app broken #1636
- [ ] Enable use of irsync for Jypyter notebooks manipulations of genericResource, compositeResource #2146

## Misc. External Integrations

- [ ] Integrate RHESSys model resource instance with new resource metadata model #178
- [ ] Fix Large File Subsetting in HydroShare Hyrax #2024
- [ ] Improving interoperability between Hydroservers and HydroShare #1984
- [ ] MOPEX needs #1963
- [ ] iRODS federation for expanded storage #1918 
- [ ] iRODS connectivity enhancements #1930
- [ ] Improvements to iRODS federation code #1657
- [ ] New Django REST call to issue iRODS read (and possibly write) tickets #2147
- [ ] How to access HydroShare iRODS hydroshareuserZone from Linux VM #2003 
- [ ] DataOne reference resource #1892
- [ ] DataONE Tier 1 (Read-Only) Compatible API REST API #129

**Comment by ChristinaB** [comment]
Hi Mark, you can add https://github.com/hydroshare/hydroshare/issues/2167    You may want to move down your list of SWATshare into the Apps section.  

Here is the  E&O priorities. Last week I went though and used the label 'user experience' for things that we have initiated or are tracking. 

1.    Caps searching - Discover should interpret Postcard and postcard the same way. (Alva may have made this an issue).  Christina
2.    Add profile requirements to HydroShare new user steps  Mark!!!  https://github.com/hydroshare/hydroshare/issues/1915
3.    Implement automatic email to new users with survey link Liza  -   onboarding/Welcome  https://github.com/hydroshare/hydroshare/issues/2135
4.    #1607 - new users getting DOIs because they click through without reading  10-20% click through without reading. Educate on the semantics of publish. Publish is the wrong word for the button.  Mark
5.    2122 &  2056    HydroShare deals poorly with concurrent operations and big data  and Broken resources *** This seems like a major issue (I’d put up there with #1 and #2 but it seems like a complicated solution so doubt will get fixed quickly?)    Chief Canary Herder - Christina   ‘no more limp and poisoned canaries in the HydroShare coalmine’.  Mark and Alva
7.    2144     Loading bug with multiple files/projects in HydroShare GIS App  Jon and Liza
8.    Help.HydroShare.org : why pages?   Change to Help #1661 - do we want to go from Pages to Help in the URL?  Move future issue to current issue. (links need redirects)   Mark  
9.    #1967 - Release- documentation timing   Liza
10.  #1503 - folder appearance - do we like it as is? Or do we want more done?  Jim
11.  Other App Bugs
Add Issue for New Release App printable demo testing by HydroInformatics conference (coordinate with Mark and Jon (white paper)).  
#1716 NWM is being updated now.    Christina

**Comment by aphelionz** [comment]
Thanks @ChristinaB! I've updated the list and put these issues right at the top.

**Comment by ChristinaB** [comment]
Hi Mark  - What process do you want to keep this updated and tracking priorities?  Here is the first update on the Caps searching for Discovery -- now has an issue assigned to Alva. 
https://github.com/hydroshare/hydroshare/issues/2180

**Comment by ChristinaB** [comment]
Hi @aphelionz 
There are two new App bugs which are intended to pass along App assessment to CUAHSI and developers.  They each contain links to the State of the App (SOTA) Report, link to help pages, link to demos/flyers on HydroShare, and link to documents on Google Drive.  

List of App related Github Issues WITH  SOTA report:
[Suggested Improvements for EPA Waters App #2234](https://github.com/hydroshare/hydroshare/issues/2234)
[Data Rods Explorer App: Data retrieval NASA web-service update needed #2222](https://github.com/hydroshare/hydroshare/issues/2222)

@jphuong and I will be adding a few more - these may need a special App section in this long list, up to you.  They are not on the E&O priority list, but they could be if determined by PIs and developers (those conversations should happen in Alabama).

**Comment by ChristinaB** [comment]
A full table of links for each App are currently on [Page 2 of the E&Outreach meeting notes. ](https://docs.google.com/document/d/14rPVmHvrRXeT5YVthK_ffoFUZ5zGxsP492k7h5AlZL8/edit)

**Comment by ChristinaB** [comment]
@aphelionz  - I was going to send this by Jon Pollack, but he does not drop down as a link on this repository.

**Comment by aphelionz** [comment]
Closing this in favor of another method of tracking
