### ISSUE TITLE
Manual pre-deploy checklist for release 1.11.0

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2221]
This is the manual pre-deploy checklist for release 1.11.0.  Refer to the [Google Doc](https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#) for items to check in each group. This deploy is staged on http://beta.hydroshare.org

Please if your name is below check the box next to it when you have signed off on the functionality.

**Please finish checking by the end of July 13th (Thur), 2017**
 
### New Features and Enhancements
- [x]  #1949 Bulk update of resource metadata [Pabitra] @pkdash
        Pabitra: This is an internal api implemented for use in REST api which can't be tested in this release.
- [x]  #2036 Geographic feature type [Pabitra] @pkdash
- [x]  #2043 uaccess attribute error [Pabitra] @pkdash
- [x]  #2110 spatial coverage issue in composite resource [Pabitra] @pkdash
- [x]  #2033 Hydroshare new user account message [Pabitra] @pkdash
- [x]  #2068 Time series bug fix [Pabitra] @pkdash
- [x]  #2045 REST end point [Hong] @hyi - tested by @pkdash
- [x]  #2153 Unzip performance [Hong] @hyi 
- [x]  #2092 SWAT MI bug fix [Jeff S] @jsadler2 
- [x]  #2087 NetCDF resource file validation fix [Tian] @gantian127 
- [ ]  #2015 Discovery issue fix [Zhaokun] @xuezhaokun  

### Help documentation on pages.Hydroshare.org
- [ ] General spot check that documentation is consistent with functionality [Christina] @ChristinaB 

### General functionality
- [ ] Profile and Homepage [Mauriel] @mauriel133 
- [x] Access control  [Pabitra] @pkdash 
- [x] iRODS connections [Hong] @hyi 
- [x] Signing up, signing in and signing out [Michael] @mjstealey
- [x] Resource creation from iRODS with a file larger than 1GB [Ray] @rayi113 

#### Resources
- [ ] Time Series  [Jeff H] @horsburgh 
- [x] HIS time Series [BYU] @danames (Creation of HIS RefTS is disabled)
- [x] Geographic Raster [Tian] @gantian127 
- [x] Geographic Feature [BYU] @danames 
- [x] Multidimensional (NetCDF) [Tian] @gantian127 
- [x] Model Program [Tony] @Castronova @goodalljl 
- [x] Model Instance [UVA] @goodalljl 
- [x] SWAT Model Instance [UVA] @goodalljl 
- [x] MODFLOW Model Instance [UVA] @goodalljl 
- [x] Web App [BYU] @danames  
- [x] Script [BYU] @danames 
- [x] Collection [BYU] @zhiyuli 
- [ ] Composite [USU] @dtarb 
       - new file type geo feature file type needs testing (drew tested)
