### ISSUE TITLE
Release 1.4.0 - Checklist

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#226]
High level checklist for issues that are required to be addressed prior to publishing Release 1.4.0 on beta.hydroshare.org

- [x] [#199] - Tian/Hong - Allow existing coverage metadata to be deleted/updated
- [x] [#194] [#193] [#188] [#187] [#9] - BYU - Reference Time Series Error handling
- [x] [#186] - Hong - Comments and Ratings Update
- [x] [#169] - Pabitra - XML for resource map is incorrect
- [x] [#232] - Pabitra - Client side file type validation for adding a file to an existing raster resource
- [x] [#152] [#124] - Mauriel - Resource landing page work
- [x] [#134] - Ray - Update content and links in Support/Help pages
- [x] [#40] [#6] - Hong - Geo Raster implementation, plus should only allow single file associated to resource at a time
- [x] [#29] - Hong - Resend email verification
- [x] Checklist items take the form of `- [x] [#issue_no] issue description`. If you questions please contact @mjstealey.

**Comment by pkdash** [comment]
@mjstealey We need a 'alpha release 1.4.0' branch to start working on these hot fixes.

**Comment by dtarb** [comment]
Based on testing and closing issues release 1.4 is ready to deploy.
