### ISSUE TITLE
Release 1.5.0 - Checklist

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#227]
High level checklist for issues that are required to be addressed prior to publishing Release 1.5.0 on beta.hydroshare.org

- [ ] [#201] - Mauriel - Manage Access: auto-complete text should be "[Name] - [Email]"
- [ ] [#171] - Pabitra - XML for science metadata is incorrect
- [ ] [#165] - Mauriel - Resource landing page work
- [x] [#90] - Pabitra - Remove references to old key/value dublin core metadata implementation
- [x] [#5] - Pabitra - Timeseries resource type phase-1
- [x] [#40] - Pabitra - Single file selection not working for Add File on resource landing page

**Comment by mjstealey** [comment]
Some elements moved to later release (NFIE or 1.6.0)
