### ISSUE TITLE
Release 1.12 Manual Pre-Deploy Checklist 

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2273]
Please review your corresponding contributions and check off that they are functional before we deploy. Thank you!

I apologize if some of these are in 1.11 as well, for now just check them off.

- [x] 1428 modflow mi phase 2 #2240 @jsadler2
- [x] Update contributing.rst #2269 @aphelionz
- [x] 2267 app log format #2268 @Castronova 
- [x] 2247 metadata string update #2263 @aphelionz
- [x] [2215] Text clarifications and helpful messages #2218 @Maurier 
- [x] [#2255] Double click to download files #2264 @Maurier 
- [x] App tracking logs shouldn't contain spaces #2267 @Castronova 
- [x] Fixing ability to set a public resource back to discoverable #2262 @aphelionz
- [x] Adding Coverages to Resource List View #2265 @aphelionz
- [x] Creating user/ endpoint #2260 @aphelionz
- [x] Passing through malformed coverages in the list endpoing #2258 @pkdash 
- [x] Docstring update for reslource listing endpoint #2239 @pkdash 

Also, @jsadler2 - can this issue be closed?
- https://github.com/hydroshare/hydroshare/issues/1428

Also @Castronova 
- [ ] Run test script that checks download of each resource

- [x] Ref time series file type in composite resource (@pkdash: I will try to do some testing. Someone else also needs to test it)
       - Pabitra: I am seeing an issue with the composite resource. When I set any file type, the file type gets set correctly. I see the success message. At that point the page reload should happen to present the user with information on the new file type. Page reload is not happening.This needs to be fixed as a hotfix. I will try to fix it this weekend.

**Comment by dtarb** [comment]
@aphelionz @Castronova I added a check off for the test script.

**Comment by pkdash** [comment]
@dtarb and @aphelionz I added a check off for testing ref time series file type

**Comment by aphelionz** [comment]
@pkdash Can you also verify #2258

**Comment by pkdash** [comment]
@aphelionz I am testing #2258. It seems to have fixed the issue as it is no more throwing exceptions when coverage parameters are passed and returning a list of resources. However, it is including resources that should not be included. The returned list includes some of the resources that have no coverage data. I used the hs_restclient to test this endpoint.

Here is an example:
```res_list = hs.getResourceList(coverage_type='box', north=39.4440, south=38.3151, east=113.8939, west=-114.9926)```

**Comment by aphelionz** [comment]
@pkdash let's make a new issue and I can take care of that in 1.13 or 1.14

**Comment by pkdash** [comment]
@aphelionz Sounds good.

**Comment by Maurier** [comment]
@aphelionz, the following checkpoint is not working in the current deployment at beta.hydroshare.org

> [#2255] Double click to download files #2264 @Maurier

The script being served is outdated. Here is the most recent one for comparison:
https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/hs_file_browser.js

**Comment by aphelionz** [comment]
@Maurier Thanks for checking on this. Can you create a hotfix to get the proper script in there? Not sure what happened in the RC cut.

**Comment by Maurier** [comment]
@aphelionz, I think this has happened before where the scripts in a deployment appear outdated. A simple collectstatic should fix it. Otherwise point the branch used in the deployment and I'll investigate further.

**Comment by aphelionz** [comment]
@cbcunc @mjstealey Can you confirm that a collectstatic can fix this?

**Comment by mjstealey** [comment]
Result from `collectstatic` on beta

```
$ docker exec -u hydro-service -ti hydroshare python manage.py collectstatic --noinput
...
Copying '/usr/local/lib/python2.7/site-packages/mezzanine/core/static/robots.txt'

1 static file copied to '/hydroshare/hydroshare/static', 1363 unmodified.
```

No new scripts based on the output...

**Comment by aphelionz** [comment]
@Maurier See above.

**Comment by Maurier** [comment]
@aphelionz, weird but it is working now.

**Comment by aphelionz** [comment]
alright! cool. I'll notify @phuongdm and @mjstealey

**Comment by mjstealey** [comment]
> @aphelionz, weird but it is working now

Cache issues perhaps?
Browsers can be annoyingly cache retentive...
