### ISSUE TITLE
[DOI Registration] Meta-Issue

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2298]
Stage 1:
- [x] [DOI Registration] "Publish This Resource" Button Updates #2291
- [x] [DOI Registration] Disable formal publication using the API #2292 
- [ ] Add reserve a DOI functionality #2558 

Stage 2:
- [ ] [DOI Registration] Pending Queue #2293
- [ ] [DOI Registration] Metadata Updates #2294
- [ ] [DOI Registration] User-side Updates and Appeals via Email #2295

Stage 3:
- [ ] [DOI Registration] Reminders #2296

Stage 4:
- [ ] [DOI Registration] Design Training Module #2297

Refer to [Google Document](https://docs.google.com/document/d/1TEWjijx-ZR6NR_Zy-1GIOjy9ZqGkFb64cE_2d-OevFY/edit) for Policy on this.

**Comment by cuahsimarko** [comment]
Moving to design document in google docs
