### ISSUE TITLE
Release 1.13 Issue Checklist

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2329]
Please review this list, check your work on http://beta.hydroshare.org, and check it off once the work is verified. Thank you!

- [x] finally got to the bottom of unicode in file name issue https://github.com/hydroshare/django_irods/pull/32 @hyi 
- [x] Include a link to contributing.rst in Readme.md #2315 @dtarb 
- [x] Fail to create resource when file names include unicode characters #2299 @hyi 
- [x] file level metadata not editable for ref timeseries file type @pkdash (#1571, #2304 )
- [x] File download agreement checkbox hotfix @pkdash  (which issues does this belong to?)
- [x] fixed unicode issue #2299 @hyi 
- [x] Fix for conditional check of published resources. #2288 @Maurier 
- [x] Normalizing University Data Set #2283 @aphelionz
- [x] Changed all hard-coded occurrences of pages.hydroshare.org @cbcunc #2277

**Comment by dtarb** [comment]
The file download agreement checkbox is issue #2302.  It was closed because it is working on www, but it is NOT working on the current release candidate, indicating that the www hotfix branch that fixed this does not appear to be merged with the RC branch that came from develop.

**Comment by aphelionz** [comment]
@dtarb @pkdash https://github.com/hydroshare/hydroshare/pull/2331

**Comment by dtarb** [comment]
@aphelionz please let me know when the beta deployment reflects the #2331 PR so I can verify it works and check the file download checkbox.

**Comment by dtarb** [comment]
I validated file level metadata for refts.

**Comment by dtarb** [comment]
In testing RC1.13 on beta I am unable to create an account because I am not getting account creation verification emails.

**Comment by cbcunc** [comment]
I found that in the local_settings, EMAIL_BACKEND was set to console instead of smtp. I confirmed this by also by adding a new user and finding the confirmation email for that new user in the gunicorn_supervisor log. So I changed local_settings to user the smtp backend and hsctl restarted beta. I created a new user again and got the confirmation email. We need to discuss on the conference cakk thius morning. I'm given to believe this is a deployment issue, not a code issue. We need to know how this should be addressed other than what I just did by hacking the local_settings postt-deployment.

**Comment by dtarb** [comment]
Thanks @cbcunc.  We also need to deploy the latest code that has PR #2331 in it to test.

**Comment by cbcunc** [comment]
#2331 deployed to beta.

**Comment by dtarb** [comment]
Closing - since deployed.
