### ISSUE TITLE
NWM View App issues compilation

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2439]
This is a compilation of NWM App issues reported by different sources after 2017 Alabama meeting (Aug 2017)

Rick:
- [ ] #2437 NWM Forecaster Viewer Suggestions

CUAHSI:
- [x] #2409 [NWM] Forecast starts an hour after initialized in Short Range Configuration
- [x] #2410 [NWM] Unclear units for time lag
- [ ] #2411 [NWM] Time Lag for Long Range allows for the selection of no or more than one time lag
- [x] #2412 [NWM] Members in Long Range Configuration are unclear
- [x] #2413 [NWM] When you pick the begin date to be the current date, it should state that the chart is projected values
- [x] #2417 [NWM] Snow-Cover Forecast Chart Units
- [x] #2420 [NWM] Medium Range Configuration, the variable "Soil Moisture" should have units in its chart but does not.
- [x] #2512[NWM Viewer] Failed to Subset Long Range outputs
- [ ] #2484 NWM Viewer - Fails to get long range data bug

Tim (UT Austin)
- [x] #2289 NWM Viewer app: implement "lateset" parameter to retrieve most recent data without specifying a date
- [x] #2307 NWM Viewer: handle polygon with holes
- [x] #2318 NMW viewer app: time step wrong for medium range grid output
- [x] #2319 NWM viewer app: merge all days into a single file for subsetted analysis_assim
- [x] #2327 NWM Viewer: add a new endpoint to return spatial query results

- [ ] #2312 NWM Explorer app failed to download files

Jim (BYU)
- [x] allow to subset AA data back to May 2017

App Implementation Review Google Doc
 https://docs.google.com/document/d/1aMQEiJ-QYUsIifOeZoj8Fm1l_LNfb8E5ibV0n1mwMFc/edit?usp=sharing

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#2
