### ISSUE TITLE
Release 1.14 Checklist

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2488]
- [x] Hyrax composite https://github.com/hydroshare/hydroshare/pull/2334 @hyi
- [x] Docker Compose Update 1: https://github.com/hydroshare/hydroshare/pull/2338 @aphelionz
- [x] Docker Compose Update 2: https://github.com/hydroshare/hydroshare/pull/2339 @aphelionz
- [x] pip install djangorestframework==3.6.4 prior to pip install d… https://github.com/hydroshare/hydroshare/pull/2342 @cbcunc
- [x] Map based spatial coverage editing for file metadata https://github.com/hydroshare/hydroshare/pull/2349 @Maurier
- [x] Fix email confirmation message https://github.com/hydroshare/hydroshare/pull/2350 @Maurier
- [x] Time Series File Type https://github.com/hydroshare/hydroshare/pull/2353 @pkdash
       Hotfix needed. See issue #2504 @pkdash
- [x] Discovery: Fix search box. https://github.com/hydroshare/hydroshare/pull/2355 @alvacouch
- [x] Discovery: Fix missing discovery results https://github.com/hydroshare/hydroshare/pull/2395 @alvacouch
- [x] Discovery: Temporary disabling of discovery sorting https://github.com/hydroshare/hydroshare/pull/2401 @aphelionz
- [x] Discovery: Performance improvement by avoiding hitting Django database https://github.com/hydroshare/hydroshare/pull/2467 @alvacouch
- [x] Changing maintenance email address https://github.com/hydroshare/hydroshare/pull/2360 @aphelionz
- [x] Add missing migration file https://github.com/hydroshare/hydroshare/pull/2358 @zhiyuli
- [x] My resources filter changes https://github.com/hydroshare/hydroshare/pull/2361 @alvacouch
- [x] Fix for URLs in abstract https://github.com/hydroshare/hydroshare/pull/2362 @Maurier
- [x] Resource creation constraints https://github.com/hydroshare/hydroshare/pull/2364 @Maurier
- [x] Expanding list of file icons https://github.com/hydroshare/hydroshare/pull/2371 @Maurier
- [x] Publish button update https://github.com/hydroshare/hydroshare/pull/2372 @Maurier
- [x] Modflow warning message for owners https://github.com/hydroshare/hydroshare/pull/2394 @jsadler
- [ ] Fix for sqlite metadata extraction bug https://github.com/hydroshare/hydroshare/pull/2402 @pkdash
- [x] Update django_irods SHA reference https://github.com/hydroshare/hydroshare/pull/2403 @hyi
- [x] Password Reset page https://github.com/hydroshare/hydroshare/pull/2415
- [x] Add unique constraints to webapp models https://github.com/hydroshare/hydroshare/pull/2416 @zhiyuli
- [x] Add to My Resources button issues https://github.com/hydroshare/hydroshare/pull/2438 @Maurier
- [x] Fix for missing logical file management command https://github.com/hydroshare/hydroshare/pull/2458 @pkdash
- [x] Removed help.html. https://github.com/hydroshare/hydroshare/pull/2468 @cbcunc
- [x] Make discover buttons work https://github.com/hydroshare/hydroshare/pull/2473 @alvacouch
- [x] Converting Organization Field to Tag Input https://github.com/hydroshare/hydroshare/pull/2310 @aphelionz
- [x] App page replacement https://github.com/hydroshare/hydroshare/pull/2322 @aphelionz
- [x] Open with to show apps user selected https://github.com/hydroshare/hydroshare/pull/2482 @zhiyuli
- [x] Fix bug in mapping due to missing short_id field. https://github.com/hydroshare/hydroshare/pull/2483 @alvacouch
- [x] Changing URL parsing method. https://github.com/hydroshare/hydroshare/pull/2485 @Maurier
- [x] Visual separator for Sources and Relations https://github.com/hydroshare/hydroshare/pull/2486 @Maurier

**Comment by aphelionz** [comment]
1.14 is UP on http://beta.hydroshare.org. Have at it, folks!

cc @hyi @cbcunc @Maurier @pkdash @alvacouch @jsadler2 @zhiyuli

**Comment by aphelionz** [comment]
I will update beta with CUAHSI-approved apps

**Comment by hyi** [comment]
@aphelionz 1.14 release RC branch does not point to the master SHA reference of the django_irods submodule, so my fix to issue https://github.com/hydroshare/hydroshare/issues/2354 is not included in 1.14 release RC branch. This merged PR https://github.com/hydroshare/hydroshare/pull/2403 updated django_irods SHA reference and merged into develop. Release 1.14 RC branch is based off develop, right? Not sure why the updated SHA reference to django_irods in develop is not reflected in the RC 1.14 branch. Do you have a quick way to fix it or we need to create a new PR just to update SHA reference to django_irods for this 1.14 RC branch?

**Comment by aphelionz** [comment]
@hyi Not sure why it wasn't included either as it came from develop. Can you make a new PR and point it to the `release-1.14RC` branch?

**Comment by hyi** [comment]
@aphelionz In fact, develop branch also points to an old SHA reference of django_irods submodule even though my PR merged into develop does update the SHA reference to the new one. I think some later merged PRs had an old reference to django_irods submodule, which override my updated SHA reference. I will have to make two PRs to fix this, one for release-1.14RC branch and the other for develop branch. Will ask you to review to have it merged.

**Comment by aphelionz** [comment]
@hyi thanks

**Comment by jsadler2** [comment]
It seems like no public resource will not load on beta. For example, when I go to this resource, https://beta.hydroshare.org/resource/da7973a47a0849798be5ae5a1110c1c0/, I get the following:
![image](https://user-images.githubusercontent.com/6943441/33436634-9e291006-d5b3-11e7-975c-4cdc3ac77197.png)

This happens for all other **public** resources that I have tried, but not ones that are private but accessible to me.

**Comment by zhiyuli** [comment]
Hmmm...This is related to the new code I added...Will look into it once I
get to office.

**Comment by zhiyuli** [comment]
@jsadler2 
I am not able to reproduce the error you saw. I can access that public resource on beta from my end.
Do you remember what other steps/actions you did that may be related? Thanks
![image](https://user-images.githubusercontent.com/10070599/33439232-254704da-d5aa-11e7-8ba4-c1fb33882b08.png)

**Comment by jsadler2** [comment]
@zhiyuli try accessing it without signing in. When I am signed in it works.

**Comment by zhiyuli** [comment]
@jsadler2 
Thanks. I am now able to reproduce the error without signing in

**Comment by aphelionz** [comment]
@zhiyuli Are you presently working on a fix? ETA?

**Comment by zhiyuli** [comment]
@aphelionz 
Yes. I am working on it. I think I have located the bug. A hotfix PR will be submitted in 1 or 2 hours

**Comment by zhiyuli** [comment]
@aphelionz 
Could you please go to Beta admin page and set some apps as "approved" (Like GIS app and Jupyter app). I know CUAHSI is still reviewing apps. So the "approved apps" on Beta are just for testing purpose, not affecting the final list of approved apps.

**Comment by aphelionz** [comment]
@zhiyuli Yes, @Castronova is on that as we speak

**Comment by zhiyuli** [comment]
@aphelionz  OK Thanks!

**Comment by aphelionz** [comment]
@zhiyuli Some are approved

**Comment by zhiyuli** [comment]
@aphelionz 
Great, Thanks!

**Comment by aphelionz** [comment]
@cbcunc Confirmed  djangorestframework==3.6.4  during deploy

**Comment by Maurier** [comment]
@hyi, @aphelionz Email is still not displayed in message as specified in #2333

**Comment by hyi** [comment]
@Maurier I checked the code in 1.14RC branch and made sure the updated code for addressing this issue is in the branch. Then I checked on beta, and verified the email is indeed included in the verification message after signing up. Can you elaborate a bit on the workflow so that I can see if I can reproduce it? According to my testing on beta, it works on beta.

**Comment by Maurier** [comment]
@hyi, Oh I see now. I tested this from the reset password link. If it doesn't apply for that case then we are good.

**Comment by hyi** [comment]
@Maurier Right, the fix to that issue only addresses email confirmation message after a user signs up. If @dtarb thinks we need to include email address in the confirmation message from the reset password link, another issue can be created and similar fix can be applied there too. @dtarb it is your call and feel free to create a new issue as needed. In the meantime, @dtarb can you close that issue #2333 now that both @Maurier and I have confirmed the new message works on beta?

**Comment by dtarb** [comment]
I closed #2333.  The behavior is I think now as intended:
- When a new user signs up they see on the screen the email that verification was sent to.  This is so they can see any typos they may have made, and then try again with the right email.
- For reset password we do not want to show the email address because reset password is for an account that already exists and we do not want to expose unnecessary information to someone trying to hijack an existing account.  If it is a legitimate user, with an email already verified, the user should get the email and be able to reset.  If it is a hijacker then they will not learn anything about the email associated with the account.

**Comment by aphelionz** [comment]
@pkdash @zhiyuli 3 checks left! Anything I can do to help?

**Comment by aphelionz** [comment]
Also, to @Maurier Can you test the password reset stuff?

**Comment by Maurier** [comment]
@aphelionz On it.

**Comment by Maurier** [comment]
@aphelionz In this deployment I'm not getting the reset email. I'm guessing we did not set it up in this VM.

Password reset through the Profile page is working as intended.

**Comment by aphelionz** [comment]
:+1:

**Comment by aphelionz** [comment]
@pkdash Please review when you can

**Comment by pkdash** [comment]
@aphelionz I have reviewed the ones I could. I was not able to review #2402 as I don;t have the required input file to test it. Either @Castronova or @horsburgh should be able to test it.

**Comment by horsburgh** [comment]
@Castronova - can you test this with the SQLite file you used to create this bug?
