### ISSUE TITLE
Composite resource Phase-2

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2502]
Phase-2 implementation of the composite resource will be based on the requirements outlined in the following google doc:

https://docs.google.com/document/d/1Hb18tUZyG7PHSwrclRHOmcYcEJvD0i9dQSmNdVckBUc/edit

The following issues and requirements have been implemented for phase-2 of composite resource. Remaining issues/requirements need to be implement in the next phase: 

- [x] Functionalities as per #2567 except the 'Open  with' feature. Also as it relates to aggregation download, aggregations that are in a folder works as part of the general folder zip functionality. However, if a single file aggregation is not inside a folder downloading of that single file will NOT download as a zip file containing the aggregation xml documents.
- [x] By default a physical file is not associated with any aggregation (recognized file type will be automatically associated with specific aggregation type when that functionality is implemented)(#2566)
- [x] Logical file type (aggregation) that consist of only a single file (physical file) will not be placed under a new folder
- [x] Aggregation type metadata can be viewed and edited by selecting the aggregation folder
- [x] Resource coverage is auto populated from aggregation if resource coverage is missing at the time of aggregation creation. User can edit resource level coverage. User can update resource level coverage based on the contained aggregations. Issue: #2577 
- [x] Aggregation naming rules (#2568 )
- [x] Generate aggregation metadata and aggregation resource map xml documents (#2565 )
- [x] Change UI references to 'Logical File' to 'Aggregation' (#2564 )
- [x] Internal API changes as per #2574

**Comment by danames** [comment]
I've added some notes. Primarily related to the new file extensions for
reference time series, ".refts.json" and sqlite files ".odm2.sqlite" that
are created by the CUAHSI Data Client and Resource Creator. Also, I still
think it is an extra and unnecessary burden to require the user to take the
extra step of right clicking on files to make HydroShare know what file
type they are. Dave has said many times that HydroShare is a cloud based
operating system. There is no other operating system that requires you to
tell it what your file types are. There was a clever solution to this that
was introduced about 40 years ago, it is called the file extension. ArcGIS
takes it further and looks not only for file extension but also for groups
of files with the right extensions. Please let's take care of this now
before we have to try to explain it to every confused user in every
training and every workshop. "Hey what's wrong with my resource?" "Well my
first guess is that you didn't right click on the files and tell HydroShare
what they are." Do we really want to be repeating that over and over again?
My two cents... - Dan

**Comment by pkdash** [comment]
I am not sure how HydroShare is any kind of operating system. It can be best described as some kind of a file management system only.

**Comment by danames** [comment]
I think Dave has been calling it a "type of operating system" with file
storage, management, and apps that run on files. But indeed, it is
certainly not an actual operating system... :)

**Comment by aphelionz** [comment]
@pkdash I have added the label 3 for large effort here. Let me know if you disagree

**Comment by horsburgh** [comment]
Definitely large effort. However, I think this work is largely complete.

**Comment by Lizabrazil** [comment]
I noticed the Set Time Series option is "Timeseries" but we call it Time Series everywhere else on the site. Also, I may be out of the loop on this but I see a "Reference Timeseries" option...I thought that was deprecated..?

**Comment by dtarb** [comment]
1.16 deploy
