### ISSUE TITLE
Composite Resource: Phase 2 Implementation

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2563]
This issue will be a checklist of all of the separate issues related to Phase 2 implementation of the composite resource. Any discussion for each of the following issues should be done on the issue's page (links provided). Aggregation types and general principles of Aggregations to be supported by Phase 2 follow the checklist in this issue.

* [x] #2564 Change any text references from "Logical File" to "Aggregation"
* [x] #2565 Implement writing of Aggregation metadata and Aggregation OAI-ORE resource map document to  the Aggregation's folder
* [x] #2566 Enable upload of physical files that do not participate in an Aggregation
* [x] #2567 Implement user interface functions/actions for Aggregation files and folders
* [x] #2568 Implement Aggregation naming rules
* [x] #2569 Design and implement new layout for Aggregation-level metadata on the resource landing page
* [x] #2570 Add new functionality for creating Aggregations
* [x] #2571 Add new functionality to auto-detect Aggregations on file upload
* [x] #2572 Add terms describing Aggregation types to HSTerms vocabulary namespace
* [x] #2573 Modify the file browser interface to display folders containing an Aggregation within an icon specific to the Aggregation type
* [x] #2574 Modify /hsapi/_internal/data-store-structure to include aggregations
* [ ] #2575 Implement new REST API endpoints
* [x] #2576 Add right click "open with" functionality to construct a URL to launch an Aggregation to an App
* [x] #2577 Enable editing of resource-level coverage so that a user can specify any coverage

### Aggregation types for Phase 2
* Geographic feature (shapefile)
* Geographic raster (GDAL VRT)
* Multidimensional (NetCDF)
* Referenced time series (.refts.json JSON)
* Time Series (ODM2 .SQlite)
* Single file (any single arbitrary file in a resource)
* File set (any arbitrary group of files)

NOTE:  The difference between the last two is that aggregation metadata is attached to the file for generic, but attached to the folder for the File Set.  From a user perspective this is like adding metadata to a file or to a folder. 

### Aggregation Principles
1. An aggregation is a file or set of files contained within a folder to which aggregation metadata is attached.
2. Aggregations comprised of multiple files, or of a type that can contain multiple files, even if they only contain one file, will be placed in a folder, and aggregation level metadata is associated with the Aggregation.  
3. Aggregations of a type that can only be comprised of single files do not have to be placed in a folder, and Aggregation metadata is associated directly with the file. 
4. The files that are part of a multi-file aggregation are, by definition, the files inside the Aggregation's folder. For convenience, file system folders will serve as a mechanism for grouping files into Aggregations.
5. Aggregations may be nested as long as the Aggregation type permits. Nesting of Aggregations follows the nesting of the folder hierarchy, which does not include references or links.  Thus there should be no possibility for infinite recursion.
6. An Aggregation type has business logic that indicates the following:
* Whether it admits single files only or multiple files
* Whether it admits folders
* Whether it allows nested folders and/or Aggregations
For example, of the Aggregation types listed above, Referenced time series and generic only admit single files and only File Set admits nested folders and Aggregations.

**Comment by pkdash** [comment]
@horsburgh 

> Aggregations of a type that can only be comprised of single files do not have to be placed in a folder, and Aggregation metadata is associated directly with the file.

Based on the above requirement I assume for ref time series aggregation the json file does n't need to be put inside a folder - that's how it's in phase-1.

**Comment by horsburgh** [comment]
Correct.

**Comment by aphelionz** [comment]
@horsburgh Please add https://github.com/hydroshare/hydroshare/issues/2635 to the checklist

**Comment by pkdash** [comment]
@horsburgh This can be closed.

**Comment by horsburgh** [comment]
@pkdash - Phase 2 is largely done, but there's still some issues in the checklist above that are not complete (or at least I don't think they are). Should we close this and leave those open, or should we leave this open until those are done?

**Comment by horsburgh** [comment]
@kjlippold - @sblack-usu and @pkdash should be able to give us an update on where the API is at with respect to phase 2 composite resources and aggregations. Yes, the intention was that the API would be updated so that you should should be able to learn which aggregations are in a resource by name and type. I'm not sure where we are at on implementation in the API. This would be pretty high priority though if it is blocking your work.

**Comment by pkdash** [comment]
@horsburgh There has been no change to API with respect to phase-2 of composite resource. Issue #2575  needs to be implemented.

**Comment by dtarb** [comment]
@pkdash what is status.  Last comment is in progress 2019.  @horsburgh Can you assess if there are remaining issues in this and perhaps identify them as separate issues for either @pkdash or @sblack-usu to address.

**Comment by horsburgh** [comment]
Based on the checklist in this issue, the only remaining thing to do was #2575. That's a separate issue that is still open (although might be able to be closed). Given that, I'm going to close this one.

@sblack-usu should be able to comment on whether #2575 is complete or not.
