### ISSUE TITLE
1.15.5 Release Checklist

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2890]
### Issues in Release
The following PRs have been consolidated into #2889 , but should still be reviewed separately.
- [x] hotfix yaml into settings #2887 (Issue #2721)  @aphelionz 
- [x] patch imghdr to look exif jpeg type #2888 (Issue #2758) @sblack-usu
- [x] HOTFIX - add ResourceFile indexes and get size off of directory listing #2885 (from user support) @sblack-usu 
- [x] Allow box coverage for file metadata in Rest API #2899 @sblack-usu
- [x] Enabling use of GABBs MultiSpec online tool for HydroShare resources #2520 @hyi 
- [x] CUAHSI Branding Updates #2745 @Lizabrazil
- [x] Hyperlink DOIs against preferred resolver #2689 @aphelionz 
- [x]  Time Series Content Type Validation in Phase 2 Composite Resource #2771 @sblack-usu 
- [x] Time Series Resource: ProcessingLevelCode should be a string and not an integer #2727 @sblack-usu 

### Beta Deployment
- [x] Deployed to Beta @sblack-usu
- [x] check_resource beta results match current www results @sblack-usu (re-verified by @aphelionz on 9/26/2018)
- [x] Review the search and discovery pages @aphelionz
- [x] Create a new user and update profile @aphelionz 
- [x] Create iRODS account, test connection and delete iRODS account @aphelionz
- [x] Create a new resource, check sharing/permission settings, delete new resource @aphelionz  
- [x] Developers test around issues @sblack-usu
- [x] QA testing around issues @ndebuhr 
- [x] GABBS / Purdue Federation tested on beta
- [x] Stakeholders approval @dtarb

### Production Deployment
- [x] Deployed to Production @aphelionz 
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages @aphelionz 
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Purdue pointing to www instead of beta
- [x] Developers test around issue @sblack-usu

### Notes relevant to deployment
1. Both beta and production show an ascii error in a file name for resource f4a7d4953a3a4fef85b0841f1c1a8e3c

**Comment by dtarb** [comment]
- I validated that 0778bfd3a34a4b84b7cd6470d722cec1 displays correctly on beta, the issue addressed by #2885 
- I validated that web app icon URL's can set to https://avatars3.githubusercontent.com/u/8520008?s=200&v=4 which triggered this error.  Giving stakeholder approval.

**Comment by dtarb** [comment]
Testing a landing page on new deploy I found https://github.com/hydroshare/hydroshare/issues/2897

**Comment by sblack-usu** [comment]
deploying to beta - ETA 12 hours

**Comment by sblack-usu** [comment]
deployed to beta and I stepped through all the steps I could.  check_resource is currently running, you can see the output in /home/hydro/hydroshare/nohup.out.

**Comment by dtarb** [comment]
Retested that 0778bfd3a34a4b84b7cd6470d722cec1 displays correctly on beta, the issue addressed by #2885 and validated that web app icon URL's can be set to https://avatars3.githubusercontent.com/u/8520008?s=200&v=4 which triggered #2758. Giving stakeholder approval.

**Comment by ndebuhr** [comment]
Not a lot of customer-visible changes in this release, but tested what I could.  Left the CUAHSI Branding Updates for @Lizabrazil  though.  Also did some general exploratory testing to see if I could find any regressions.  Nothing to hold deployment back, in my opinion.  Here is the list from beta testing today and some recent general systems testing (bug reports for all used this new beta deployment):
- https://github.com/hydroshare/hydroshare/issues/2910
- https://github.com/hydroshare/hydroshare/issues/2911
- https://github.com/hydroshare/hydroshare/issues/2912
- https://github.com/hydroshare/hydroshare/issues/2913
- https://github.com/hydroshare/hydroshare/issues/2914
- https://github.com/hydroshare/hydroshare/issues/2915
- https://github.com/hydroshare/hydroshare/issues/2916

**Comment by aphelionz** [comment]
Thanks @ndebuhr. I've triaged those issues. I agree, no show stoppers.

**Comment by dtarb** [comment]
I tried to create a new account and got this far
 
![image](https://user-images.githubusercontent.com/3456833/46115922-9d2d4b00-c1b6-11e8-80b6-b87a1f800f01.png)

But never received the email to click.

I also tried copying bag to iRODS zone for some big resources, and got no response.
Specifically copying the Resource bag to iRODS for this resource https://beta.hydroshare.org/resource/9badb941303d4813b3c398cdab038368/ clicking the Copy button nothing happens, then eventually the dialog goes away without any message or indication that anything has happened or not.

Neither of these are problems in www, but may reflect (1) email not set up for beta, and (2) iRODS different for beta.  If you are confident that these are sufficiently explanatory, then I am OK to give stakeholder approval, but at a minimum we need to be confident about account creation working before deploying.

**Comment by aphelionz** [comment]
The email problem does not present on production, as emails have been turned off on beta due to quota messaging.

Similarly, the copy resource issue does not present on www. The deployment has taken place and been tested by developers and we are confident the deploy was successful. Closing this now and other issues can be opened against 1.15.5
