### ISSUE TITLE
Release CheckList 1.16

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#2934]
#### Composite Phase 2
- [x] ~#2564 Change any text references from "Logical File" to "Aggregation"~ #2762 Improve Semantics for Usability
- [x] #2565 Implement writing of Aggregation metadata and Aggregation OAI-ORE resource map document to  the Aggregation's folder
- [x] #2566 Enable upload of physical files that do not participate in an Aggregation
- [x] #2567 Implement user interface functions/actions for Aggregation files and folders
- [x] #2568 Implement Aggregation naming rules
- [x] #2571 Add new functionality to auto-detect Aggregations on file upload
- [x] #2573 Modify the file browser interface to display folders containing an Aggregation within an icon specific to the Aggregation type
- [x] #2574 Modify /hsapi/_internal/data-store-structure to include aggregations
- [x] #2577 Enable editing of resource-level coverage so that a user can specify any coverage

#### Large File Download
- [x] Enable unlimited, bidirectional file transfer for apps #1842

#### Miscellaneous
- [x] Tooltip is grammatically incorrect #2841 @sblack-usu
- [x] Visibility of logout notification is window-size dependent #2828 @sblack-usu
- [x] Profile changes are not cancelled after cancel button click #2873 #2918 @engineSound
- [x] Abstract Message Error is not helpful #2883 #2918 @engineSound
- [x] DOI UX change #2918 @engineSound

### Beta Deployment
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval @dtarb ready to give stakeholder approval once missing aggregation level [metadata for existing resources](https://github.com/hydroshare/hydroshare/issues/2934#issuecomment-431688535) is addressed 

### Production Deployment
- [x] Deployed to Production
- [ ] check_resource www results match pre-deployment www result
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [FAILS] Create iROD account, test connection and delete iROD account.  See #2969 
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1.	fix_irods_user_paths      # without this, all user file checks will fail. 
2.	repair_resource              # skips new composite resources, not knowing what to do with them. 
3.	remove_auto_generated_generic_metadata
4.	check_bag –reset           # marks all bags for regeneration but doesn’t regenerate them. Regenerates metadata files even if not stale. 
5.	regenerate_xml_files_composite_resource  # regenerates all metadata files for aggregations

**Comment by ndebuhr** [comment]
I'm seeing same behavior as originally reported for the "Profile changes are not cancelled after cancel button click" issue in beta.  See original bug report https://github.com/hydroshare/hydroshare/issues/2873 and use same steps to reproduce.  

Automated test suite ran fine, so except for persistence of the bug mentioned above, this looks ready for production from QA perspective.

@engineSound @aphelionz

**Comment by pkdash** [comment]
It seems the download of any aggregations/content types in composite resource that existed as part of the deployment, still don't have the aggregation level metadata and resource map xml files in the downloaded zip file. Here is an example resource: https://beta.hydroshare.org/resource/ae24db0cca8549c5b7dcbd12bc23f5b6/

**Comment by dtarb** [comment]
I agree with @pkdash that this is a problem.  I am able to reproduce it with other resources of mine too.  Who knows what code is supposed to generate this, or what flag is supposed to be set "dirty" so that these files are created.

**Comment by sblack-usu** [comment]
regenerate_xml_files_composite_resource has been added to the release checklist and has been run on beta.  There were 

Results from running on beta.
>> 1477 COMPOSITE RESOURCES PROCESSED.
>> BAG FILES GENERATED FOR 1471 COMPOSITE RESOURCES.

Failed resources:
504c2d396f234e259949c25b5228a1ad
37259cd632ec469098fabb64cdc89fce
76d73ced9e0e4405a26e64225ff53869
42d80c46dab54fef958885d4588e4598
1fedd80cd20245409a0ea02cc2a1ecf0
99d5f690908b4c18bd362039522bff3f

**Comment by dtarb** [comment]
I checked the problem resources listed above.  The first three resources to not exist on www (They return page does not exist errors).  On beta they are owned by Chris Frans.  The presumption is that he deleted these on www after beta was cut, and that we therefore do not need to worry about them.  [It may be good to have someone verify deletion logs to be doubly sure]

The fourth does not exist on www.  On beta it is "Testing HS_REST_Client" owned by Scott Black.  Perhaps @sblack-usu remembers how it was created and this may give insight as to why it is troublesome.

The fifth is owned by Jon Goodall.  Download bag fails on both www and beta.  Problems with this are thus not a regression.  The error on beta indicates problems with strings and unicode characters.  

The sixth was created by Ray as a test resource for Chris Calloway.  On www it appears sound.  On beta no files are shown and debug indicates error processing irods proxy.  Perhaps @rayi113 remembers how it was created and this may give insight as to why it is troublesome.

Do not hold up deploy of 1.16 on account of these.  The two that exist on www are both team members.
After 1.16 is deployed, I think it would be prudent to investigate these resources further to see if they are symptomatic of any problems needing to be addressed.

**Comment by rayi113** [comment]
@dtarb The 99d5f690908b4c18bd362039522bff3f resource on https://www.hydroshare.org/resource/99d5f690908b4c18bd362039522bff3f/  was used in Feb 2018 when we were testing Federation schemes between hydroshareZone and nfiehydroZone to test files being physically stored in a zone federated with hydroshareZone, i.e. nfiehydroZone:

-bash-4.1$ ipwd
/nfiehydroZone/home/localHydroProxy
-bash-4.1$ ils | fgrep ff3f
  C- /nfiehydroZone/home/localHydroProxy/99d5f690908b4c18bd362039522bff3f
-bash-4.1$ 

So I believe it may be troublesome because beta.hydroshare.org may not federate with nfiehydroZone.  I can check.  Mention @hyi

**Comment by hyi** [comment]
@rayi113 Yes, it will break on any test VM since nfiehydroZone is not federated with any test VM and it is not modified by management commands to make it work on test VM since it is not from hydroshareuserZone. I suggested to delete that test resource from www so it will not bite us in future deployments. When we need to test federation functionalities using a federated zone other than default hydroshareuserZone, we can use nfiehydroZone to test again, but since this resource has already served its testing purpose, I suggest to delete this test resource for now.

**Comment by rayi113** [comment]
Thanks, @hyi -  I deleted the 99d5f690908b4c18bd362039522bff3f resource from www just now.

**Comment by sblack-usu** [comment]
@alvacouch - could you take a look at the check_resource run against production?
http://ci.hydroshare.org:8080/job/new-www-check-resource/10/console

There is a lot of output due to the new composite resource.  I kicked off a beta run just now if you'd like to compare.
