### ISSUE TITLE
Release CheckList 1.16.1

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#2981]
### Issues in Release
- [x] #2781 Eliminate case sensitivity of email addresses and usernames @sblack-usu
- [x] #2797 Composite Resource: Enable Adding and Managing Referenced File Content via the REST API @sblack-usu
- [x] #2796 Composite Resource: Enable Adding Referenced File Content via User Interface @hyi 
- [x] #2860 Support Overwriting Files @sblack-usu
- [x] #2961 Google maps api keys moved to local_settings @sblack-usu 
- [x] #2965 [HOTFIX] Updated aggregation level metadata is not reflected in aggregation level metadata xml file @sblack-usu 
- [x]  [PR 2951](https://github.com/hydroshare/hydroshare/pull/2951) fix management commands @alvacouch 
- [x]  #2978 folder rename bug fix @sblack-usu 

### Beta Deployment
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
beta - http://ci.hydroshare.org:8080/job/beta_check_resource/8/console
prod- http://ci.hydroshare.org:8080/job/new-www-check-resource/10/console
- [x] Review the search and discovery pages @sblack-usu 
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource @sblack-usu 
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
- [x] Maps API key is correct and maps are displaying correctly
- [no problems identified] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. add maps key to local_settings.py
2. update version in footer to 1.16.1
3. Validate email function is disabled on backup worker (and enabled on active)

**Comment by dtarb** [comment]
I have verified ability to add reference content through UI and through API using script written to create PASDA resources.  @horsburgh it would be good if you can also spot check reference functionality.

I have verified iRODs account creation and deletion.

I am giving stakeholder approval.

**Comment by dtarb** [comment]
@alvacouch @sblack-usu in testing I noticed that /debug does not work on beta.
On www with https://www.hydroshare.org/resource/d7b7f9d5c7e0411683b76ef45c6bf0d8/debug/ I get the usual report (which is clean in the case of this resource)
On beta with https://beta.hydroshare.org/resource/d7b7f9d5c7e0411683b76ef45c6bf0d8/debug/ I get
![image](https://user-images.githubusercontent.com/3456833/47893161-29b7d280-de21-11e8-823e-d35272269f90.png)

**Comment by horsburgh** [comment]
I just tried out the referenced content on beta. Here's some issues I noticed with the simple tests I performed:

1. I created a new resource and added a new referenced content object by clicking on the button on the toolbar. I set the name of the content to "Jeff's Website" and I set the URL to "http://jeffh.usu.edu". The .url file was created, but the apostrophe gets included in the .url file name (jeff's website.url) and causes some havoc. The double click redirect works, but when I right click and try to download the file, nothing happens. When I right click and try to download zipped, nothing happens. When I right click and choose "Get File URL", it gives me everything up to the apostrophe (which doesn't work). 

**To resolve this:** I think we need to filter out special characters when creating the .URL file name.

2. I deleted the first .url file I created in 1 above. Then, I just added it back using the exact same steps. The .url file gets created, but I get a huge long error that says "Add reference content Failed" and then has a BUNCH of other garbly gook. First, it shouldn't fail. Second, if it does fail, we should never print an error like this to the screen. Third, I think the failure is related to the system thinking that the file already exists, which means that it wasn't deleted cleanly before I tried to add it back. 

**To resolve this:** Not completely sure, but we need to make sure deletes are clean and that errors are handled more gracefully.

3. I then added a reference to another file available online via a URL. The .url file was created successfully. I then right clicked on the file and renamed it, removing the .url extension. I was able to do this, which leaves the file with a generic icon and no extension in the file browser. When I click on it, I see content metadata, and I can right click and select "Remove Content Type". This removes the content metadata from the view, and I can't add content metadata. Then, I renamed the file and put the .url extension back on. The reference icon comes back in the file browser view, but I still have no ability to add content metadata, so the reference file aggregation is gone.  

**To resolve this:** I think we should consider blocking removal of the .url file extension. This also likely has implications across other content types (e.g., file extensions for shapefiles, raster, netcdf, etc.). On my own computer, if I change the extension of a file, I know that I have no guarantees that it will work with anything after I do that, in fact it almost always breaks things. But, my computer does ask me if I really want to change the file extension before it does so.

**Comment by hyi** [comment]
@horsburgh I will try to fix these issues as much as I can by Tuesday for release 1.16.1 @sblack-usu

**Comment by hyi** [comment]
@horsburgh I have just created a PR to fix the issues you outlined and asked @sblack-usu to code review. What I did for fixing issue No. 1 is to replace all spaces with underline character and strip out all other special characters from user input with only numbers, letters, dash, dot, and underline characters allowed in the referenced url file name. Enforcing referenced url file name not containing special characters this way automatically fixed the issue No. 2 you detailed above. For issue No. 3, I have added check to make sure if the renamed new file name does not contain .url extension name, the system will append .url to the renamed file name to ensure the renamed file name always has a .url extension. @sblack-usu and I have been chatting on slack and realized this file name issue is wide spread across the board in our system, not specific to referenced content. File names that contain special characters would cause file download, deletion, and potentially issues with iRODS backend. Remove .url extension from file name rename is also widespread issue in our system, not specific to referenced content. What I did there is just to enforce referenced content to have a .url extension so the functionality will not break, and we can revisit it later when we have a holistic approach on enforcing extensions for aggregation file types for example.

**Comment by sblack-usu** [comment]
@ndebuhr - I didn't think to ask you to do QA testing on this.  Do you have time to do so on Monday?

**Comment by dtarb** [comment]
On the file naming question, perhaps it is time to revisit #2538

**Comment by horsburgh** [comment]
@hyi - I like your interim solutions. I think they will fix the behavior I saw today, and I like replacing spaces in the file names because it makes them more URL friendly. 

As @dtarb and you pointed out, it's probably time for some comprehensive thinking about file naming conventions and business rules around changing things, but with the fixes you have done so far, I don't think that should hold this current functionality up. Thanks for the quick turnaround.

**Comment by martinseul** [comment]
I spent some time testing the signup and user profile and I did not receive an email to activate my account. @phuongdm could you please check. I was able to activate it manually. so the account creation works but the email does not. Also when testing the profile editing i realized that the required fields are not enforced.  I remember we had a reminder for a user to complete the profile at some point.  Also sending a test email to my contact email failed. @ndebuhr could you please confirm

**Comment by martinseul** [comment]
I also looked at this: check_resource beta results match current www results
beta - http://ci.hydroshare.org:8080/job/beta_check_resource/8/console
prod- http://ci.hydroshare.org:8080/job/new-www-check-resource/10/console
but don't know all the details could someone comment on what it tests and what to look for?

**Comment by dtarb** [comment]
@martinseul email sending is typically turned off for beta to avoid spurious quota messages being sent to users from beta.  I have suggested earlier that would be better if it could be turned on and just the quota messages turned off.  But so far this has not been possible.

**Comment by ndebuhr** [comment]
Version listed in the footer is not correct.  Otherwise, manual+automated system testing resulted in just a couple low priority bugs that don't seem to prevent release.  
1. https://github.com/hydroshare/hydroshare/issues/2987
2. https://github.com/hydroshare/hydroshare/issues/2988
3. https://github.com/hydroshare/hydroshare/issues/2989
@martinseul I'm not able to duplicate the profile required fields problem.  Is it possible that you are seeing this https://github.com/hydroshare/hydroshare/issues/2873?

**Comment by sblack-usu** [comment]
An admin has to update the version in the footer, with @aphelionz leaving this week, I don't know of any developers that have admin access.  I'm happy to update it if given admin access, otherwise, please let me know who to contact during deployment.
