### ISSUE TITLE
Release CheckList 1.17

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3000]
### Issues in Release
- [x] #2863 Django 1.11 upgrade
- [x] #2820 html metadata

### Beta Deployment
- [x] Deployed to Beta
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [ ] check_resource beta results match current www results
- beta - http://ci.hydroshare.org:8080/job/beta_check_resource/10/console
- www - http://ci.hydroshare.org:8080/job/new-www-check-resource/12/console
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
- [x] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. This deployment updates hs_docker_base to "release-1.9".  Use docker pull to download the image before running ./hsctl rebuild for a quicker deployment.
2. Migrations are a part of this deployment
3. @phuongdm - check hotfix for large file download
4. @phuongdm disable email on backup worker after swap worker

**Comment by sblack-usu** [comment]
I did a mock deployment from 1.16.1 to 1.17. 
Check it out at https://dev-hs-1.cuahsi.org/

**Comment by dtarb** [comment]
iRODS account creation does not work.   @hyi did magic last time on beta to fix this 
![image](https://user-images.githubusercontent.com/3456833/48241169-f3cf9c80-e392-11e8-9a7b-9dbc73ab69b1.png)

**Comment by dtarb** [comment]
This resource https://dev-hs-1.cuahsi.org/resource/f399b429ce8a47f2946a97e1f0b83028/ appears to be broken.  It does not show content files.  It does on www.  Download bag results in session error
![image](https://user-images.githubusercontent.com/3456833/48241821-ba4c6080-e395-11e8-8663-04c02e5ac04c.png)

**Comment by dtarb** [comment]
I think both of the above two errors are due to differences in the iRODS configuration of this test VM and www, weakening the testing process.

**Comment by sblack-usu** [comment]
yeah, I don't think we want to do beta testing on dev-hs-1.  I just deployed as a proof.  I'll see if Chris is done with beta.

**Comment by sblack-usu** [comment]
Adding #2820 to this release since it is a very minor javascript change and was merged into develop before the django 1.11 branch was merged.

**Comment by dtarb** [comment]
I tested creating account, creating and deleting iRODS account and quite a lot of working with resources and all seems the same as www.  Indicated stakeholder approval.

**Comment by ndebuhr** [comment]
@sblack-usu I have noted some bugs to report, but am getting a 502 bad gateway on beta.  Had this earlier in the week two.  Will post bug reports when beta is stable and I can record the necessary screenshots/videos

@martinseul FYI

![bildschirmfoto vom 2018-11-19 08-51-49](https://user-images.githubusercontent.com/14877920/48693120-b829a380-ebd8-11e8-8ca9-1863bf160ee8.png)

**Comment by ndebuhr** [comment]
From automated testing and QA, nothing to hold up release.

- Beta deployment version number in footer is incorrect
- https://github.com/hydroshare/hydroshare/issues/3013
- https://github.com/hydroshare/hydroshare/issues/3014
- https://github.com/hydroshare/hydroshare/issues/3015
- https://github.com/hydroshare/hydroshare/issues/3016
- https://github.com/hydroshare/hydroshare/issues/3017
- https://github.com/hydroshare/hydroshare/issues/3018
- https://github.com/hydroshare/hydroshare/issues/3019
- https://github.com/hydroshare/hydroshare/issues/3020
- https://github.com/hydroshare/hydroshare/issues/3021

**Comment by martinseul** [comment]
Thanks all, looks like we are good to go for the release on Tuesday. I'll let Liza now to sent out notification. So we are on for a release on Tuesday.

**Comment by sblack-usu** [comment]
After a few hiccups, 1.17 was successful.  Diff check for files that need manual updates have been added to the release checklist template.

Django 1.11 and mezzanine pages aren't playing nice in some places.  We need to bring back support in mezzanine for the HomePage and the SiteConfiguration.  #3025 has been created to update those pages.  We wrote the following query to update the version and bring down the maintenance message.

```
from theme.models import SiteConfiguration
sc = SiteConfiguration.objects.get()
content = sc.col3_content
content = content.replace("1.16.1", "1.17")
sc.col3_content = content
sc.save()

from theme.models import HomePage
hp = HomePage.objects.get()
import datetime
hp.message_end_date = datetime.date(2018, 11, 26)
hp.save()
```
