### ISSUE TITLE
Release Checklist 1.18

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3039]
### Issues in Release
- [x] #2808 Composite resource to support File Set - a new aggregation type @pkdash (verified by @sblack-usu)
- [x] #3037 File set migartion file is not correct @pkdash (verified by @sblack-usu)
- [x] #3012 Bugs in rules for spatial coverage @sblack-usu 
- [x] #3027 failed to update coverage via rest api for Composite Res (a bug or by design?) @zhiyuli 
- [x] #3025 Re-enable HomePage and SiteConfiguration via Mezzanine @sblack-usu 
- [x] #2977 create REST API endpoint for iRODS to notify HS quota update @hyi 
- [x] #2941 Fix name listing issues in MyResources @hyi 
- [x] #2860 Support Overwriting Files @sblack-usu 
- [x] #2931 Discover listing issues @hyi 
- [x] #2980 web app bugs @sblack-usu 
- [x] #3042 web app bugs @Maurier 
- [x] #3030 Add files to resource fails, irods @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files: @phuongdm 
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py (IRODS_SERVICE_ACCOUNT_USERNAME added)
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. delete_hanging_logical_files will need to be run for all the migrations to work.  Update the code base, run migrations, let it run until it fails.  run the command manually.  Then proceed with the deployment.

**Comment by hyi** [comment]
@phuongdm is it possible for you to test the quota update endpoint against beta? I have checked the corresponding issue in the checklist, but to verify it indeed works, you will have to test to verify. Also, since it does not affect the current functionalities, I think it would be OK to include the endpoint code even if you could not test it on beta in time before the deployment, but it'd be good if you could test it on beta before the next release.

**Comment by phuongdm** [comment]
Sorry, will finish today

**Comment by ndebuhr** [comment]
Nothing especially concerning from QA perspective - all automated/manual completed.  I checked off a number of the checklist items.  Here are the new issues in GitHub:
    https://github.com/hydroshare/hydroshare/issues/3046
    https://github.com/hydroshare/hydroshare/issues/3047
    https://github.com/hydroshare/hydroshare/issues/3048
    https://github.com/hydroshare/hydroshare/issues/3049
    https://github.com/hydroshare/hydroshare/issues/3050
    https://github.com/hydroshare/hydroshare/issues/3051
    https://github.com/hydroshare/hydroshare/issues/3052
    https://github.com/hydroshare/hydroshare/issues/3053
    https://github.com/hydroshare/hydroshare/issues/3054
    https://github.com/hydroshare/hydroshare/issues/3055
    https://github.com/hydroshare/hydroshare/issues/3056

"Create a new user and update profile" still not possible given SMTP server limitations of beta environment.  Left that unchecked.

**Comment by dtarb** [comment]
I created a new account on beta.hydroshare.org (had to activate using admin as outgoing email is not ste)
I created an iRODS account associated with it (dtbeta)
I saved a resource to iRODS.  This resulted in a zip file in iRODS
I attempted to add this zip file to an empty resource that I created and received the following error
![image](https://user-images.githubusercontent.com/3456833/50056587-5139d480-011b-11e9-8a9d-991e71bf45ff.png)

I tried to repeat this process, this time logging into users.hydroshare.org, hydroshareuserZone with a previously existing iRODS account and attempted to add a file from this account to a resource and received the same error.

@phuongdm @cbcunc @rayi113 @hyi please comment if this is a deficiency in beta that needs to be fixed before we deploy, or just a difference in configuration.  [We need to avoid these differences in configuration to the maximal extent possible as they hamper testing.]

**Comment by phuongdm** [comment]
@dtarb,

I think (not 100% for sure), users.hydroshare.org is not Federated server of beta system and also has no related with beta's iRODS LandingZone server, so it cannot work. You should try with userdev.hydroshare.org

**Comment by dtarb** [comment]
@phuongdm 
The RENCI group (@hyi, @rayi113 and @cbcunc) should be able to verify that this functionality should work for any iRODS server where the user has credentials, and has in the past worked from many other servers.  In addition to users.hydroshare.org and usersdev.hydroshare.org I often test using data.iplantcollaborative.org.

I just tested on www and found that on www I am not able to load files from iRODS from any of the 3 servers mentioned above (users, usersdev and iplant), thus iRODS is not working properly even on www.  This is a regression that must have happened previously as I know that iRODS file loading has worked in the past.

**Comment by dtarb** [comment]
Closing.  We have moved past this.
