### ISSUE TITLE
Release Checklist 1.19

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3102]
### Issues in Release
- [x] #3091 update quota usage internal endpoint fails when username contains special character @hyi 
- [x] #3065 Cannot copy any web app resource @sblack-usu 
- [x] #2812 Resource Landing Page: Add Readme Functionality @Maurier 
- [x] #2569 P2 Composite Res: New layout for Aggregation-level metadata on composite resource landing page @Maurier 
- [x] #2763 Resource Landing Page: Modify Related Resources @Maurier 
- [x] #2810 Resource Landing Page: Reorganize Elements For Clarity and Easier Access @Maurier 
- [x] #2813 Resource Landing Page: File Metadata View @Maurier 
- [x] #2924 Resource Landing Page: File Browser List View Formatting off for Long File Names @Maurier 
- [x] #3022 "hidden" buttons on resource landing page are "pressed" by web spiders @Maurier 
- [x] #2988 Tooltip inconsistency on profile page @engineSound 
- [x] #2992 HydroShare reference timeseries validation requires method link url @pkdash 
- [x] #3137 Unzipping does not work on 1.19 candidate release
- [x] #3141 Resource specific metadata getting cutoff

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [NA] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [NA] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Resource Landing Page redesign!

**Comment by alvacouch** [comment]
I found it extremely difficult to make something public after its requirements were met. I was in a hurry to make the test and after meeting all requirements for public, the resource could not be made public. I had to redisplay the page to make it public.

**Comment by engineSound** [comment]
@alvacouch I felt your pain that you had to refresh the page. Was it easier to you in the previous release?

**Comment by horsburgh** [comment]
@alvacouch and @engineSound - I just tried on beta, and setting a resource as public or private does not require a page refresh. It does require using the Manage Access window. We have consolidated all access/permission functionality on that one window so it is all in one place. There obviously may be a little bit of confusion for some users who were used to finding the public/private buttons in the middle of the page.

**Comment by Castronova** [comment]
I really like the redesign! 

However, I found it difficult to download resource content. I eventually figured it out (with help from Liza), but we might want to make this a bit more obvious since its a very common action.

**Comment by cuahsimarko** [comment]
As someone not as familiar with the product, I scrambled for about 30 seconds then the icon caught my eye. Somewhat agree, but it was intuitive enough...

On Feb 6, 2019, at 4:15 PM, Tony Castronova <notifications@github.com<mailto:notifications@github.com>> wrote:


I really like the redesign!

However, I found it difficult to download resource content. I eventually figured it out (with help from Liza), but we might want to make this a bit more obvious since its a very common action.

**Comment by cuahsimarko** [comment]
10-15 seconds more like it.

On Feb 6, 2019, at 4:19 PM, cuahsimarko <notifications@github.com<mailto:notifications@github.com>> wrote:

As someone not as familiar with the product, I scrambled for about 30 seconds then the icon caught my eye. Somewhat agree, but it was intuitive enough...

On Feb 6, 2019, at 4:15 PM, Tony Castronova <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


I really like the redesign!

However, I found it difficult to download resource content. I eventually figured it out (with help from Liza), but we might want to make this a bit more obvious since its a very common action.

**Comment by Castronova** [comment]
This icon doesn't really scream "download" to me: ![image](https://user-images.githubusercontent.com/4822372/52374430-3ef95a00-2a2b-11e9-8cb6-946218b1a3bf.png)

**Comment by cuahsimarko** [comment]
Yeah maybe text labels

On Feb 6, 2019, at 4:21 PM, Tony Castronova <notifications@github.com<mailto:notifications@github.com>> wrote:


This icon doesn't really scream "download" to me: [image] <https://user-images.githubusercontent.com/4822372/52374430-3ef95a00-2a2b-11e9-8cb6-946218b1a3bf.png>

**Comment by Castronova** [comment]
I created a resource consisting of 2 python scripts and 4 raster tifs. The python scripts simply load the rasters and create a plot. https://beta.hydroshare.org/resource/3867d7662ea34974a8bb12faf5d84ed6/ 

1. Upload these data to HydroShare. Metadata from the rasters are extracted and their resource type is set to "Geographic Raster"

![image](https://user-images.githubusercontent.com/4822372/52374874-613fa780-2a2c-11e9-96fb-476717d73326.png)

2. Download the content as a zipped bagit archive and notice that each raster is in its own directory, unlike when the data was uploaded.

![image](https://user-images.githubusercontent.com/4822372/52374983-951acd00-2a2c-11e9-9767-1d1a7efc8fe6.png)

3. Running the script produces an error because uploading the data to HydroShare has changed the paths to the rasters. This could cause problems with users, because they will not notice that their files have been moved into folders. Additionally, they won't find out that things are broken until someone else tries to user their data.

I tried to fix this by  "Removing Content Type" for each raster in HydroShare. This removes the content type association but keeps each raster file in separate directories.  There is currently no way to move a file into its parent directory, which is one way to fix this broken paths. 

I'm not sure how to best solve this problem, but I'm worried that this could cause serious problems with modeling and jupyter-related resources.

**Comment by horsburgh** [comment]
@Castronova - moving files between directories can be done via cut and paste.

FYI - this is not an issue with the 1.19 release. This behavior (putting raster content in its own folder) was introduced with phase 2 of composite resource some time ago.

**Comment by horsburgh** [comment]
@cuahsimarko - the download buttons do have hover text.

**Comment by Castronova** [comment]
I think the issue is that the automatic extraction of metadata that changes file paths without asking the user.

**Comment by alvacouch** [comment]
@engineSound @sblack-usu 
I did the following: 

1.  create a new resource. 
and then, without refreshing the page: 
2.  save an abstract. 
3. save keywords. 
4. dump a document into the resource.

And then the public button was greyed out and could not be pressed. 

I haven't tried this in previous releases. I was actually testing dynamic discovery indexing, which works.

**Comment by horsburgh** [comment]
@Maurier - Not a deal killer, but there's some spacing issues on the edit coverage element. The set spatial coverage from content files button is too close to the longitude box, and there's too much vertical space between that and the temporal coverage element. I see that the start date and end date expand if I make the window wider, so maybe they need to stay below the map, but you could put end date below start date instead of on the same line and then move them up so we aren't taking up so much vertical space.

![image](https://user-images.githubusercontent.com/3485902/52426734-c1315f00-2abb-11e9-9e62-bd231f8c173d.png)

**Comment by Maurier** [comment]
@horsburgh I have pending pull requests for this and some minor issues that we could consider including. Some of these were issues I found during testing of the beta deployment.

#3110 #3112 #3111 #3109 #3108 #3106 
@sblack-usu Let me know what you think.

**Comment by horsburgh** [comment]
@Maurier - OK. I'm still just kicking tires a bit on the beta deployment while helping Liza with some documentation. Glad to know you've already caught this.

**Comment by Maurier** [comment]
> @engineSound @sblack-usu
> I did the following:
> 
> 1. create a new resource.
>    and then, without refreshing the page:
> 2. save an abstract.
> 3. save keywords.
> 4. Open sharing icon. Can't select public, asks that a document be uploaded.
> 5. Close sharing page.
> 6. Upload a document  (now requirements are met)
>    And then the public button was greyed out and could not be pressed. It was pressable after a refresh.
> 
> I haven't tried this in previous releases. I was actually testing dynamic discovery indexing, which works.

I will be addressing this today. I was able to reproduce it as described above.

**Comment by sblack-usu** [comment]
If they're minor issues that you can live with for a week or two, I'd rather push these small issues until the next release.  We should really only consider hotfixes if they're fixing an issue that is a dealbreaker with the release at this point.

**Comment by Maurier** [comment]
In that case we could include thse ones as a hotfixes: #3110 #3111

**Comment by engineSound** [comment]
I agreed with @sblack-usu. These things can be marked as known issues when we notify users. As I am aware of, many software releases have this practice. @Lizabrazil please take a note on this when email to users. We can release a patch in a week or so.

**Comment by sblack-usu** [comment]
@Maurier, Both of those have minor in the titles.  @horsburgh what do you think?  I prefer avoid hotfixes this late in the game if possible.

**Comment by Maurier** [comment]
@alvacouch - I tested again and the UI is working as expected. I think we both forgot to add a title to the resource.

One thing I noticed though, the warning on top describing what's needed to make the resource public goes away as soon as one fills in any metadata. It should persist until all required metadata has been added.

**Comment by horsburgh** [comment]
@Maurier and @sblack-usu - the world is not ending today. So, unless people find bugs that are pretty bad, we should deploy this to production and then do the minor fixes after. Better to not risk breaking something that has already been tested by "fixing" something hastily.

**Comment by Maurier** [comment]
@sblack-usu These two issues correspond to some of my pending PRs and were not finished in time for this release.

* #2638 Edit to text on My Resources @Maurier
* #2765 zip file/folder name suggestion and auto-select not working @Maurier

**Comment by sblack-usu** [comment]
@Maurier - Thanks, I've removed those two tickets from the checklist

**Comment by dtarb** [comment]
See issue #3127.  It is a regression.  If we go ahead with this deploy we need to fast track an unzipping fix.

**Comment by horsburgh** [comment]
@dtarb - I think you meant #3137 not #3127.

**Comment by dtarb** [comment]
Correct #3137

**Comment by hydrocheck** [comment]
Only thing I noticed which hasn't been reported is (cosmetic) #3140.  If we support IE11, then I have a number of bugs to add, but even then they don't hold up deployment in my opinion.

**Comment by pkdash** [comment]
It seems resource specific metadata is not getting displayed properly (getting cutoff on the left side) in both view and edit modes for resource types like Time Series, Multidimensional, Geographic Feature, Geographic Raster. Here is an example of the problem:

![image](https://user-images.githubusercontent.com/2523434/52569425-2bf5d980-2ddf-11e9-8bfa-089e7ada014e.png)

**Comment by engineSound** [comment]
@hydrocheck Does it work on edge browser? 

I think we support IE11. Adding @Lizabrazil , do we have a data point that indicates the percentage of IE 11 users? This helps us scale the impact of the cosmetic issues.

**Comment by Lizabrazil** [comment]
![image](https://user-images.githubusercontent.com/13852599/52572469-dd980900-2de5-11e9-870a-0b99e1fa3cb8.png)
Looks like in just the past week we have had 24 users using IE11. Overall IE is the 4th most common browser that our users use (looking back just this month).

**Comment by Lizabrazil** [comment]
I'm looking into an easy implementation that detects the type of browser being used and if unsupported, it displays a banner to the user that we may not support your current browser and to please upgrade.

**Comment by hydrocheck** [comment]
@engineSound No, I currently do not test Edge.  Firefox, Chrome, and IE11 seem to give more bang for the buck.  The idea being that if it works all on all three, it probably works on Edge, but I wouldn't say the reverse is true - for Firefox, Chrome, and Edge (e.g. IE11 bugs are unlikely to surface using those three browsers).  Could of course add to the number of browsers used, but that leads to massive increases in testing time.  
@Lizabrazil Keep me posted on the IE11 decision.  Showing a message does seem like a good approach, since I would suspect IE11 users probably have another browser installed.  IE11 is still supported by Microsoft and is the most recent (last) version of IE, FYI.  If you are looking at browser usage data anyway @Lizabrazil, I would be curious to know Safari usage.  I tend to avoid Safari testing, except for some exceptional cases.

**Comment by martinseul** [comment]
Liza, where can i see the statistics for the browser use, is it google analytics?

**Comment by Lizabrazil** [comment]
Yes, Google Analytics

**Comment by Lizabrazil** [comment]
https://analytics.google.com/analytics/web/#/report-home/a74322358w116039831p121330771 
Under Audience>Technology

I think this is public but let me know if anyone needs access granted.

**Comment by Lizabrazil** [comment]
@hydrocheck Looks like safari is second most commonly used.

**Comment by Lizabrazil** [comment]
A few different options here and i'm sure there are many more: 
https://browser-update.org/ 
http://outdatedbrowser.com/en/how

**Comment by rayi113** [comment]
@Lizabrazil looks like https://analytics.google.com/analytics/web/#/report-home/a74322358w116039831p121330771  is not public, could you add Dave, Martin, Tony, myself, any others?  Thanks.  Here is a screen cap:

![ga_page](https://user-images.githubusercontent.com/2846017/52866848-907da500-310d-11e9-99de-983cc71ada17.png)

**Comment by Lizabrazil** [comment]
I just checked and my account doesn't have permissions to give others access. I think @Castronova has admin rights?

**Comment by rayi113** [comment]
Okay thanks.  @Castronova consider making @Lizabrazil an admin for future requests.  Thanks.
