### ISSUE TITLE
Resource migration Phase-1

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3128]
In phase-1, the following resource types will be migrated to composite resource type:

- [x] Generic resource (#3100) (PR: #3101) 
- [ ] Multidimensional resource (NetCDF)(#3135)(PR: #3159)
- [ ] Geographic Raster resource(#3249 )(PR:#3339)
- [ ] Geographic Feature resource(#3566)(PR:#3567)
- [ ] Time Series resource (#3568)(PR:#3572)

**Comment by zhiyuli** [comment]
@dtarb @pkdash 
Is this the right ticket where concerns and edge cases regarding "Generic to Composite migration" should be noted?

**Comment by dtarb** [comment]
@zhiyuli yes.  If they are ONLY for generic to composite they could be discussed in #3100.  This issue is for any type migration issue.
