### ISSUE TITLE
Resource migration Phase-2

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3129]
In phase-2, all dead code as well as unit tests for resource types migrated in phase-1 will be removed. The following apps need to be cleaned up:

- [x] hs_app_netCDF (#4535 )
- [x] hs_geo_raster_resource (#4538 )
- [x] hs_geographic_feature_resource (#4572)
- [x] hs_app_timeseries (#4608)
- [x] hs_model_program (#4652)
- [x] hs_modelinstance (#4653)
- [x] hs_swat_modelinstance (#4710)
- [x] hs_modflow_modelinstance (#4655)
- [x] ref_ts (Reference timeseries resource) (#4632 )
- [x] hs_script_resource (there is no equivalent aggregation - however, script resources has been migrated as composite resource as part of release 1.54) (#4640)

There will be separate PRs for removing each of the above deprecated resource types.

**Comment by Castronova** [comment]
@pkdash what is the status of this?

**Comment by sblack-usu** [comment]
There's quite a bit of stale code that needs to be cleaned up.  Not all of it is straightforward to identify and remove.

**Comment by dtarb** [comment]
Moved to selected next for development as part of resource consolidation wrap up.

**Comment by pkdash** [comment]
Code for all the deprecated resource types listed in this issue has been removed as of release 1.58.  There is a final step as per issue #4749 which needs to be implemented. So closing this issue.
