### ISSUE TITLE
Release Checklist 1.20

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3199]
### Issues in Release
- [x] #3076 Fix irods containers to persist beyond a system reboot or docker comp @cuahsimarko 
- [x] #3104 New dev build @cuahsimarko 
- [x] #2955 pop up after keywords and abstract are included is incorrect @Maurier 
- [x] #2873 Profile changes are not cancelled after cancel button click @engineSound 
- [x] #2276 When creating new resources, author and owner middle initials are ignored @hyi 
- [x] #3114 Remove unused redis @cuahsimarko 
- [x] #3138 Attempt to remove self as owner instead switches quota holder to self @Maurier 
- [x] #2946 Improve geographic feature error message @engineSound 
- [x] #2709 Non-unique IDs on Resource Landing Page @engineSound 
- [x] #2870 My Resources page should probably have pagination like Discover page @cuahsimarko 
- [x] #3115 Prevent auto timeseries aggregation creation from CSV file @pkdash 
- [x] #3158 Edit mode for geo feature aggregation doesn't show point type coverage @pkdash
- [x] #1632 Refining group capabilities @alvacouch 
- [x] #3176 Resource Landing Page: Rendering of readme.txt files is ignoring formatting @Maurier 
- [x] #3088 Rest Api Improvements @sblack-usu 
- [x] #3084 hsapi /resource path cleanup @sblack-usu 
- [x] #3174 Add pytest @cuahsimarko 
- [x] #3193 Set default per page very high @cuahsimarko 
- [x] #3141 Fix layout issues concerning resource specific metadata cutoff @Maurier 
- [x] #3169 Local iRODS installation fails without local_settings.py @kjlippold 
- [x] #3175 make url validator more robust @hyi 
- [x] #3075 Embed heapmetrics script @engineSound 

- [x] #3167 Add table column sort indicator @Maurier 
- [x] #3136 Put copy resource bag to iRODS button with other buttons @Maurier 
- [x] #3206 resource updated time is updated on view and download @sblack-usu 
- [x] #3201 Truncate file path for open with @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [NA] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [NA] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue 

### Notes relevant to deployment
1. Includes deployment and swap worker updates

**Comment by horsburgh** [comment]
I can confirm that the keywords issue is not resolved on Beta.

**Comment by horsburgh** [comment]
Also - in testing readme functionality, I noted that new lines are not being handled correctly for readme.md files. I've reported this to @Maurier with demonstrating data.

**Comment by sblack-usu** [comment]
I was aware of the keywords issue, but haven't taken the time to look into it yet.  This could be a blocker for 1.20, so I'll take a look now.

**Comment by horsburgh** [comment]
@Maurier has fixed the larger issue with readme files, so I don't think that one is a blocking issue, but it would be great to get it fully sorted.

**Comment by sblack-usu** [comment]
I did some investigation into the keywords and nailed it down to a commit.  https://github.com/hydroshare/hydroshare/commit/e16ded601b0b81c95176f40d1d836572819b6469

I've asked @Maurier to look at it and he indicated he knows what's going and how to fix it.  He'll get time to work on it this evening.

**Comment by hydrocheck** [comment]
1.     https://github.com/hydroshare/hydroshare/issues/3214
2.     https://github.com/hydroshare/hydroshare/issues/3215
3.     https://github.com/hydroshare/hydroshare/issues/3216
4.     https://github.com/hydroshare/hydroshare/issues/3217
5.     https://github.com/hydroshare/hydroshare/issues/3218
6.     https://github.com/hydroshare/hydroshare/issues/3219
7.     https://github.com/hydroshare/hydroshare/issues/3220
8.     https://github.com/hydroshare/hydroshare/issues/3221
9.     https://github.com/hydroshare/hydroshare/issues/3222
10.     https://github.com/hydroshare/hydroshare/issues/3223
11.     https://github.com/hydroshare/hydroshare/issues/3224
12.     https://github.com/hydroshare/hydroshare/issues/3225
13.     https://github.com/hydroshare/hydroshare/issues/3226
14.     https://github.com/hydroshare/hydroshare/issues/3227

**Comment by sblack-usu** [comment]
What is hydrocheck???

**Comment by hyi** [comment]
I believe hydrocheck is an agent user from Neil's selenium tests.

**Comment by Lizabrazil** [comment]
@dtarb To follow up on documentation, I do not think any documentation needs to up updated with this release (besides the Irods icon which is asked about in the #3136)

**Comment by pkdash** [comment]
The count for 'Resources owned by me' is not correct. This is a regression issue.

**Comment by Maurier** [comment]
@sblack-usu - I'm trying to create a new account on beta, but I do not get the verification email. Has this happened to anyone else?

**Comment by Maurier** [comment]
> #3185 Update text in Add/Edit Relation modals @Maurier

I'm not seeing the changes in https://github.com/hydroshare/hydroshare/pull/3185 included in this release which addresses the bullet point above.

**Comment by sblack-usu** [comment]
@Maurier - I think you have to use squirrel mail for beta.  I usually just login as an admin and activate a new account if I need one so I'm not sure what the credentials are...  Maybe @phuongdm could help out there?  https://nginx1-beta.hydroshare.org:8443/webmail/src/webmail.php

**Comment by Maurier** [comment]
@sblack-usu - Thanks for the clarification. I was able to test resource access with my current account, and gave access to another developer's account. As long as account creation works in www you can disregard my message above.

**Comment by cuahsimarko** [comment]
Scott and I just chatted and our new working agreement will be I post my understanding and close the issue and he'll see the notification and if I misunderstood or have incomplete info, he'll just reopen.
