### ISSUE TITLE
Release Checklist 1.21

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3239]
### Issues in Release
- [x] #2763 (PR #3185) Update text in Add/Edit Relation modals @Maurier 
- [x] #3183 Hide items in Comments section @Maurier 
- [x] #2813 (PR #3112) Resource Landing Page: File Metadata View @Maurier 
- [x] #2989 Unintuitive cursor settings for various interface elements @Maurier 
- [x] #2765 (PR #3108) Fix for text input auto select on Zip Folder dialog @Maurier 
- [x] #3204 Editing keywords removes existing keywords and new keywords aren't added on beta. @Maurier 
- [x] #3119 Additional validation fo timeseries CSV file @pkdash 
- [x] #3130 Resource Landing Page - required metadata alert goes away @Maurier 
- [x] #3110 Resource Landing Page - Minor layout adjustments @Maurier 
- [x] #2823 No resolution validation for profile image @engineSound 
- [x] #3100 Migrate all generice resources to composite resource @pkdash 
- [x] #3180 add relations and funding_agencies updating via rest api @sblack-usu 
- [x] #3136 (PR #3213) Add custom HydroShare font icons setup @Maurier 
- [x] #3232 Update for builds @cuahsimarko 
- [x] #3156 Support special case in creation of ReferencedFile with a "not-resolving" url @hyi 
- [x] #3234 HydroShare template rendering improvements @sblack-usu 
- [x] #3163 Enable ToolMetaData in mezzanine @sblack-usu 
- [x] #3211 My resources page loading time improvement @pkdash 
- [x] #3251 A resource that requires a license agreement will not download @Maurier 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [ ] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

**Comment by phuongdm** [comment]
@sblack-usu ,

please remove `hydroshare/settings.py`, we won't use it while deploying anymore

**Comment by hyi** [comment]
@phuongdm ```settings.py``` is required by Django and should not be removed. Do you mean some other file?

**Comment by phuongdm** [comment]
I meant we no need to care about this file (Diff RC check list) while deploying, not while running HS :)

**Comment by sblack-usu** [comment]
oh, so just update the checklist to not include looking for changes in settings.py?

**Comment by cuahsimarko** [comment]
Seems legit

**Comment by phuongdm** [comment]
@sblack-usu yes

**Comment by Maurier** [comment]
@sblack-usu - I did a round of testing on beta of the issues I worked on. I checked off the ones that look good. However, I don't think the PRs for the bullet points below are included in this release candidate. Could you confirm?

- [ ] #2763 (PR #3185) Update text in Add/Edit Relation modals @Maurier 
- [ ] #3251 (PR #3252) A resource that requires a license agreement will not download @Maurier

**Comment by sblack-usu** [comment]
@Maurier - You are correct that #3251 was not included, however I was hoping to include it when I put together the checklist before it was merged to develop.  It's now been pulled into the RC as well.

#2763, according to the PR was merged 20 days ago, so it should be included.  Is the functionality just not there or is there more work to be done?  I can help you hunt it down in the git history if you'd like help.

**Comment by Maurier** [comment]
@sblack-usu - I'm not sure why, but https://github.com/hydroshare/hydroshare/pull/3185 didn't make it into the develop branch. I see it merged, but I cannot find the commit in the history of the file. The work in this PR is missing from our develop branch. We'll have to add it back.

**Comment by sblack-usu** [comment]
It kind of looks like it was reverted.  I see the commits in develop's history, but the changes aren't there.  I'll look into it more and see if I can explain what's going on.

**Comment by sblack-usu** [comment]
@Maurier - The landing page commit shows up just fine.  https://github.com/hydroshare/hydroshare/blame/develop/theme/templates/resource-landing-page/references.html#L182

**Comment by Maurier** [comment]
@sblack-usu - I see. It seems like only the changes in https://github.com/hydroshare/hydroshare/pull/3185/commits/6f5e646dd110cbbb022efb445cc50b600320c2fb and https://github.com/hydroshare/hydroshare/pull/3185/commits/b46df2f530b2280bfe3955d53ef0367220b2219e are missing.

**Comment by sblack-usu** [comment]
I'm not exactly sure what happened there, but we can fix it with a cherry-pick of those two commits.  Here is a PR for that.
https://github.com/hydroshare/hydroshare/commit/6b09888f446df31415bdd0d43826e57a700499ee?diff=unified

**Comment by sblack-usu** [comment]
@Maurier - #3185 is deployed to beta and ready for you to test.

**Comment by pkdash** [comment]
My resources page missing resource type icon for geo feature resources. This is a regression issue. I have created a PR as a hotfix: #3260

**Comment by pkdash** [comment]
@sblack-usu In relation to testing issue #3101, I see there are still generic resources on beta. I assume then the management command for migrating generic resources yet to be run on beta resource.

**Comment by pkdash** [comment]
Filtering on 'Author' or 'Subject' on my resources page is not working - a regression issue.

**Comment by dtarb** [comment]
@pkdash the plan for 1.21 is that while the management command is in this release that it will not be run on www.  There are a few reasons for this.
1. We need to appropriate messaging to warn users about this resource type change.  
2. We need some work on apps that may still create generic resources
3. Testing of some of the problem resources in #3101 has not been fully resolved
The plan for this messaging is https://docs.google.com/document/d/1NP3fAjR8PC2_eO2CvXNvl3HmvRN5LvbzhiOl1nUzpYE/edit#

All.  Based on my spot testing, I have checked stakeholder approval.  The main features of this deploy that benefit users are halving the load time for My Resources page and improved messages associated with related resources.

This release should merge and include the hotfix to #3259.  This is a one line code change

**Comment by hydrocheck** [comment]
1. Version number incorrect on beta
2. https://github.com/hydroshare/hydroshare/issues/3262
3. https://github.com/hydroshare/hydroshare/issues/3263
4. https://github.com/hydroshare/hydroshare/issues/3264
5. https://github.com/hydroshare/hydroshare/issues/3265
6. https://github.com/hydroshare/hydroshare/issues/3266
7. https://github.com/hydroshare/hydroshare/issues/3267
8. https://github.com/hydroshare/hydroshare/issues/3268
9. https://github.com/hydroshare/hydroshare/issues/3269
10. https://github.com/hydroshare/hydroshare/issues/3270
11. https://github.com/hydroshare/hydroshare/issues/3271
12. https://github.com/hydroshare/hydroshare/issues/3272
13. https://github.com/hydroshare/hydroshare/issues/3273

**Comment by martinseul** [comment]
I did spent some time looking at creating collection resources and it looks to be working fine
@phuongdm @cbcunc @Lizabrazil @dtarb  
we are still on for tomorrow.

**Comment by dtarb** [comment]
@martinseul thanks.  I tested too.  Good luck with the deploy.

**Comment by Maurier** [comment]
I tested my tickets on production and it all seems in order.
