### ISSUE TITLE
Release Checklist 1.22

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3312]
### Issues in Release
- [x] #3262 Non-utf8 characters cause issues in resource READMEs @pkdash 
- [x] #3290 Update for local developer environment @cuahsimarko 
- [x] #1632 Refining group capabilities  @alvacouch 
- [x] #3254 Profile page loading time improvement @pkdash 
- [x] (PR #3256) Replace mezzanine routing with Django for My Resources @cuahsimarko 
- [x] (PR #3280) PyTest my resource @cuahsimarko 
- [x] #3297 Prefetch metadata for resource listing @pkdash 
- [x] #3245 Update modified date on discover @sblack-usu 
- [x] #3294 Ascii characters without a unicode mapping cause resource creation to fail @sblack-usu 
~- [ ] #3324 Res landing page crashed with UnicodeEncodeError after being made Public @sblack-usu~ Reverted
- [x] #3330 local_settings not overwriting all settings @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

**Comment by pkdash** [comment]
@sblack-usu While testing #3297 I am seeing the issue (#3259)  again for which I had made a hotfix for the last release 1.21. It seems this issues has been resolved on www. Not sure why this fix did not make into 'develop'.

**Comment by pkdash** [comment]
While testing #3254 found that the icon for Geographic Feature resource type is missing on profile page. @sblack-usu Should I create a fix for 'develop' or 'RC 1.22'?

**Comment by pkdash** [comment]
@Maurier Would appreciate if you can test the profile page.

**Comment by sblack-usu** [comment]
Go ahead and sumbit a PR against RC-1.22 and we can get it in, assuming it's just a frontend change.

**Comment by pkdash** [comment]
Here is the PR #3350

**Comment by sblack-usu** [comment]
Beta has been updated with the updated RC

**Comment by pkdash** [comment]
Fix for the missing icon for geo feature resource type is working now on beta.

**Comment by hydrocheck** [comment]
1. - https://github.com/hydroshare/hydroshare/issues/3352
2. - https://github.com/hydroshare/hydroshare/issues/3353
3. - https://github.com/hydroshare/hydroshare/issues/3354
4. - https://github.com/hydroshare/hydroshare/issues/3355
5. - https://github.com/hydroshare/hydroshare/issues/3356
6. - https://github.com/hydroshare/hydroshare/issues/3357
7. - https://github.com/hydroshare/hydroshare/issues/3358
8. - https://github.com/hydroshare/hydroshare/issues/3359
9. - https://github.com/hydroshare/hydroshare/issues/3360
10. - https://github.com/hydroshare/hydroshare/issues/3361
11. - https://github.com/hydroshare/hydroshare/issues/3362
12. - https://github.com/hydroshare/hydroshare/issues/3363
13. - https://github.com/hydroshare/hydroshare/issues/3364

**Comment by dtarb** [comment]
I tested creating and deleting an iRODS account.  I tested creating, deleting and changing ownership of a resource.  Gave stakeholder approval.
