### ISSUE TITLE
Release Checklist 1.23

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3380]
### Issues in Release
- [x] #2790 No message to user when resource folder creation fails due to duplicate name @pkdash 
- [x] #1505 Order recent activity in groups from last to first @mraocuahsi 
- [x] #2871 No user message during processing for resource creation/deletion @cuahsimarko 
- [x] #3267 Capitalization issue - "Programming language" in the resource landing page Resource Specific metadata @cuahsimarko 
- [x] #2915 Inconsistent capitalization approach on user profile page @cuahsimarko 
- [x] #3229 Remove old NetCDF template contents @cuahsimarko 
- [x] #3273 The "user type" on the hydroshare profile page is incorrectly formatted @mraocuahsi 
~- [ ] #2777 Python strftime can't handle dates before 1900 @mraocuahsi~
~- [ ] #2871 No user message during processing for resource creation/deletion @mraocuahsi~
- [x] #3292 colon in discover @alvacouch 
- [x] #3273 The "user type" on the hydroshare profile page is incorrectly formatted @mraocuahsi 
- [x] #2405 Resource Landing Page: Performance Enhancements Needed @pkdash 
- [x] #3059 Dashboard UI and Backend  @engineSound @alvacouch 
- [x] #2756 Delete resource metadata confirmation  @engineSound  
- [x] #3242 Create" should be moved to the top navigation with a dropdown @Maurier 
- [x] #3362 Group searches UI need inform user when no result found @engineSound 
- [x] #3310 Spatial coverage place/area name not displayed in resource edit mode @Maurier 
- [x] #2556 Redirect To Resource After Login @pkdash 
- [x] #3226 Searching users to add as contributors does not work in IE11 @Maurier 
- [x] #3324 Res landing page crashed with UnicodeEncodeError after being made Public @sblack-usu 
- [x] #3120 New owner requires refresh before it shows up on landing page @mraocuahsi 
- [x] #3388 textual change: "Show get started" to "Show getting started" in dashboard @engineSound 
- [x] #3392 Without user logged in, the hydroshare page url should not redirect @engineSound 
- [x] #3382 Anomaly in community resource listing @alvacouch 
- [x] #3242 "Create" should be moved to the top navigation with a dropdown @sblack-usu @Maurier 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. There was a deployment problem with static/media during the beta deploy.  It has been fixed in both beta and production scripts, but we need to make sure we test those changes.

**Comment by dtarb** [comment]
#3400 reports a regression that is in my opinion deploy blocking.

**Comment by dtarb** [comment]
#3397 is also a regression that I think should be a hotfix to beta.

**Comment by sblack-usu** [comment]
> 
> 
> #3400 reports a regression that is in my opinion deploy blocking.

This has been resolved.

**Comment by sblack-usu** [comment]
#2777 and #2871 have been removed from the checklist because they are not complete.  The code changes from these two issues are not creating any regressions.

#3382 - is dark code for communities, so I'm verifying it.
