### ISSUE TITLE
Release Checklist 1.23.1

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3434]
### Issues in Release
- [x] #3432 Fix for broken Group page functionality

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

**Comment by sblack-usu** [comment]
Because @ndebuhr is out and we haven't transferred the knowledge on running the QA automation tools yet, we'll have to move forward without it.  This should not be a concern because the changes are almost all on the frontend and limited to the groups page.  I'll walk through the manual tests outlined in the release checklist.

**Comment by sblack-usu** [comment]
@dtarb @martinseul @phuongdm @cuahsimarko @cbcunc

**Comment by dtarb** [comment]
I tested beta.hydroshare.org and found that attempting to add invite a new member to a group that I own still does not work.

**Comment by sblack-usu** [comment]
@dtarb - did you clear your cache?

**Comment by dtarb** [comment]
Yes - I did clear cache.

The behavior I am getting on beta (with Firefox) is
1. I click invite people
2. I start filling in a name
3. I pick a person off the list that appears
4. As soon as I have picked a person the "invite people" box disappears
5. If I click "invite people" again, the box opens with the name I picked already in it and the invitation gets sent.

This appears to be a partial improvement over www where the invitation is not being sent, but the box disappearing is confusing.

**Comment by sblack-usu** [comment]
weird, I'm not getting that behavior on firefox.  Mauriel also tested chrome, and ie.  So the modal window is just disappearing?  I'm not able to recreate that behaviour, I've tried a few different workflows using tabs/returns/clicks.  @Maurier - Any idea what's going on or are you able to reproduce this?

**Comment by Maurier** [comment]
I was able to reproduce it now. You actually need to click on an item from the list which hovers outside of the modal window. I'll try to have a fix soon.

**Comment by Maurier** [comment]
@sblack-usu, I have a fix ready. Let me know which branch we are using so I can add it.

**Comment by sblack-usu** [comment]
It's already on master, so go ahead and branch off of master and submit a PR against it.

**Comment by sblack-usu** [comment]
The latest patch has been deployed to beta.  I tested selecting a user from the dropdown list that is below the modal window.  Just looking for Stakeholder approval @dtarb @martinseul

**Comment by dtarb** [comment]
+1 from me
