### ISSUE TITLE
Release Checklist 1.24

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3439]
### Issues in Release
- [x] URL of RDF namespace in resourcemetadata.xml incorrect #3319 @pkdash 
- [x] Getting rid of page refresh when updating Resource Landing page items #3186 @Maurier 
- [x] Remove the logic in iRODS browser to create resources in user zone #3406 @hyi 
- [x] Connect Discover to the REST API #3418 @sblack-usu 
- [x] P2 Composite Res: Implement NEW REST Endpoints for Aggregations #2575 @sblack-usu
- [x] Simplify iRODS federation configurations and related code logic #3430 @hyi 
- [x] non-ascii characters in author/title breaks recently visited on dashboard #3431 @hyi 
- [x] Change weekly quota email to be monthly #3442 @hyi 
- [x] Author Naming Inconsistency Issue #3428 @Maurier 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. For this release deployment, after HydroShare server is up and running, the following command needs to be run to migrate all resources from iRODS user zone to data zone:
```
./hsctl managepy migrate_resources_from_userzone_to_datazone
```
The console output should print out all resources that have been migrated successfully from user zone to data zone. Please copy and paste the console output in this issue for testing purposes and for future reference. The problematic resource described in the issue #3351 can be used as a test resource, which should be fixed after the migration. 
2. If there were no issues being raised related to these migrated resources after a couple of releases, those resources from user zone could be deleted manually. @sblack-usu

**Comment by hydrocheck** [comment]
1. - https://github.com/hydroshare/hydroshare/issues/3457
2. - https://github.com/hydroshare/hydroshare/issues/3458
3. - https://github.com/hydroshare/hydroshare/issues/3459
4. - https://github.com/hydroshare/hydroshare/issues/3460
5. - https://github.com/hydroshare/hydroshare/issues/3461
6. - https://github.com/hydroshare/hydroshare/issues/3462
7. - https://github.com/hydroshare/hydroshare/issues/3463
8. - https://github.com/hydroshare/hydroshare/issues/3464
9. - https://github.com/hydroshare/hydroshare/issues/3465

**Comment by sblack-usu** [comment]
@hyi 
Here are the results from running `migrate_resources_from_userzone_to_datazone` on production

![image](https://user-images.githubusercontent.com/35820390/60515562-16535480-9c99-11e9-9d4d-d86528c0b378.png)

**Comment by hyi** [comment]
@sblack-usu I have verified on www2 - the active worker and confirmed all resources from user zone have been migrated successfully to data zone now. I checked on this resource from @dtarb https://www.hydroshare.org/resource/abba182072cc48b691ca61509019e9f8/ and verified that after the migration, raster aggregation was created correctly which fixed that issue. However, we did get that ```duplicate keyword not added``` error, which was not related to userzone-to-datazone migration as I had confirmed on beta. The keyword for this resource was ```bug``` which somehow raises this duplicate key error for keywords on this latest release. It looks to me like the updated code from the last release most likely have caused this issue although I have no idea on specifics. My migration script does not touch metadata on migrated resources at all, and I suspect the metadata validation code in the latest release somehow raises this duplicate key error in the latest release although it was fine in the last release.  Might worth looking into to get to the bottom of it.
