### ISSUE TITLE
Release Checklist 1.24.3

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3485]
### Issues in Release
- [x] Resource landing page slower when loading private pages #3481 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. This is a hotfix that does not require a migration, so the only downtime required is for swap (~1 second).  @phuongdm - please make sure migrations are not run for this deploy.

**Comment by sblack-usu** [comment]
@ndebuhr - could you do a QA pass on beta?  Once you've approved it, we'll schedule a release for this hotfix.

**Comment by hydrocheck** [comment]
https://github.com/hydroshare/hydroshare/issues/3487
https://github.com/hydroshare/hydroshare/issues/3488
https://github.com/hydroshare/hydroshare/issues/3489
https://github.com/hydroshare/hydroshare/issues/3490
https://github.com/hydroshare/hydroshare/issues/3491
https://github.com/hydroshare/hydroshare/issues/3492
https://github.com/hydroshare/hydroshare/issues/3493
@sblack-usu
