### ISSUE TITLE
Release Checklist 1.25

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3518]
### Issues in Release
- [x] #3402 Add quota support into local-dev setup @phuongdm 
- [x] #3441 fixed the issue with launching GABBs tool from aggregation in composi… @hyi 
       *Note*: Since GABBs iRODS server is only federated with www iRODS server, I cannot really test it out on beta to verify it works, but I checked the async relevant tools PR and made sure my fix has been accommodated there. Verified it indeed works on www release 1.25.
- [x] #3500 Disable comment hyperlinks @sblack-usu 
- [x] #3511 Single file download for Reference Time Series files not working @klippold (@sblack-usu verified)
- [x] #3506 async relevant_tools on resource landing page @sblack-usu 
- [x] #3498 Expose settings.DEBUG in templates and insert noindex in DEBUG @alvacouch (@sblack-usu - tried to verify but this is not working.  It has no ill effect and should not hold up the release)
- [x] PR #3425 Aggregation without folder @pkdash @sblack-usu @Maurier 
- [x] Verify local_settings are correct for geoserver @klippold (@martinseul says to leave it off for now)

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Update local_settings.py with @klippold settings for geoserver

**Comment by martinseul** [comment]
I tested the setup Geoserver by uploading a shapefile and making it public and did not see the proper endpoints appear, is this functionality enabled or am I missing a step? Also as we are missing some documentation and a migration script for the current geographic resources I'm leaning towards pushing this feature to a future release.

**Comment by sblack-usu** [comment]
I checked that based off of @klippold verifying beta was sending to geoserver earlier.  @klippold - could you look into what's going on?

**Comment by dtarb** [comment]
I am also not seeing geoserver functionality.  I looked at this in an old resource
https://beta.hydroshare.org/resource/d7b7f9d5c7e0411683b76ef45c6bf0d8/ and a new resource I created to specifically try this

**Comment by dtarb** [comment]
I also noticed that the color of the Open With button has changed from Blue to White.  I do not necessarily object to this, but I wonder why this is being done and feel that we may have more important things to worry about.  Also, this is a change that users will notice, so if we make changes like this they should be deliberate.  I do not see button color change in the checklist above.

**Comment by Maurier** [comment]
The color of the button was changed as part of #3506. While implementing the logic in the PR I did some cleanup on the layout and made the decision to change the color because this button does not denote a primary action, but it's rather a menu toggle.

**Comment by sblack-usu** [comment]
@katrinleinweber @dtarb - Looks like the geoserver settings were overwritten.  I restored them and restarted the beta server.  Could you please verify it is working now?

**Comment by dtarb** [comment]
@Maurier can you please revert the open with button back to blue.

**Comment by Maurier** [comment]
@dtarb - Here: https://github.com/hydroshare/hydroshare/pull/3546
