### ISSUE TITLE
Release Checklist 1.26

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3582]
### Issues in Release
- [x] add/edit reference url fix #3577 @sblack-usu 
- [x] fixed open with button display issue for web apps with appkey extra metadata #3536 @hyi 
- [x] Hide keywords edit message in view mode #3521 @Maurier 
- [x]  Revert button color #3545 @Maurier 
- [x]  Resource Header Vue Instance #3186 @Maurier
- [x]  group product listings #3382 @alvacouch 
- [x] Change flake8 line max to 120 PR #3565 @cuahsimarko 
- [x] Optimize aggregation lookup #3530 @pkdash 
- [x] Management command to modify a resource id #3338 @sblack-usu 
- [x] import ODM2 variable names from SKOS server #3496 @alvacouch 
- [x] czo community PR #3515 @cuahsimarko 
- [x] Add conditional PR #3581 @cuahsimarko
- [x] fix bug in url parsing of tools #3583 @sblack-usu
- [x] Serious discovery shortcomings "discovered" and addressed #3605 @alvacouch

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local_settings.py
  * hydroshare/settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue
- [x] Run solr_update management command

### Notes relevant to deployment
1. CZO community will be deployed dark
2. Skip Solr reindex job and use the new solr index management command written by @alvacouch

**Comment by hydrocheck** [comment]
https://github.com/hydroshare/hydroshare/issues/3608
https://github.com/hydroshare/hydroshare/issues/3609
https://github.com/hydroshare/hydroshare/issues/3610
https://github.com/hydroshare/hydroshare/issues/3611
https://github.com/hydroshare/hydroshare/issues/3612
https://github.com/hydroshare/hydroshare/issues/3613
https://github.com/hydroshare/hydroshare/issues/3614
