### ISSUE TITLE
Release Checklist 1.27

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3643]
### Issues in Release
- [x] #3558 Title element hidden by header @Maurier 
- [x] #3592 Submitting comma separated keywords will only render the first one @Maurier 
- [x] PR #3597 Community frontend @cuahsimarko 
- [x] #3562 Cleanup is_federated blocks @hyi 
- [x] #3621 Force client refresh of css and js files @sblack-usu 
- [x] #3632 group image doesn't appear when unauthenticated @alvacouch 
- [x] PR #3628 Hydro flower @sblack-usu 
- [x] #3623 naming issues for organizations @alvacouch 
- [x] #3625 bulk add owner @alvacouch 
- [x] PR #3641 fixed iRODS browser issue @hyi 
- [x] #3636 reorder tabs on group landing page @cuahsimarko 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * hydroshare/local-settings.py
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [NA] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [NA] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Several files that require manual updates of the backups have been modified with flower and django freshly updates.
- config/hydrohsare-config.yaml
- hsctl
- hydroshare/settings.py
- scripts/templates/docker-compose.template
2. This release introduces django freshly, which allows us to version static files by updating FRESHLY_ASSETS_VERSION in hydroshare/settings.py.  It's set to 1.27 and does not need to be updated again for this release.
3. hs_docker_base has been update and the latest commit is currently pointing to a develop image.  hs_docker_base is building a release image now and hydroshare will have to be updated before setting the tag.
4. Geoserver is ready to be turned on, update the HSWS_* settings.  @sblack-usu has the settings on hand.

**Comment by hydrocheck** [comment]
https://github.com/hydroshare/hydroshare/issues/3648
https://github.com/hydroshare/hydroshare/issues/3649
https://github.com/hydroshare/hydroshare/issues/3650
https://github.com/hydroshare/hydroshare/issues/3651
https://github.com/hydroshare/hydroshare/issues/3652
https://github.com/hydroshare/hydroshare/issues/3653
https://github.com/hydroshare/hydroshare/issues/3654
https://github.com/hydroshare/hydroshare/issues/3655
https://github.com/hydroshare/hydroshare/issues/3656
https://github.com/hydroshare/hydroshare/issues/3657
https://github.com/hydroshare/hydroshare/issues/3658
https://github.com/hydroshare/hydroshare/issues/3659
