### ISSUE TITLE
Release Checklist 1.27.2

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3681]
### Issues in Release
- [x] #3657 Navigating to the CZO Admin tab results in a lengthy error for non-CZO-community members.  @cuahsimarko 
- [x] PR #3616 update release checklist to account for local_settings being removed @sblack-usu 
- [x] PR #3673 update local dev to use 9.4.7 postgres image @sblack-usu 
- [x] PR #3668 Serialize add_owner database updates with transactions. @alvacouch 
- [x] PR #3675 remove django-freshly until a patch is made @sblack-usu 
- [x] #3676 File browser not getting refreshed after aggregation creation @Maurier 
- [x] #3636 reorder tabs on groups landing page @cuahsimarko 
- [x] #3672 Groups page inconsistencies and request to join has disappeared @cuahsimarko 
- [x] PR #3680 add check in solr_update for None metadata @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [NA] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [NA] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Update local_settings.py to enable communities `COMMUNITIES_ENABLED = True`

**Comment by hydrocheck** [comment]
- https://github.com/hydroshare/hydroshare/issues/3683
- https://github.com/hydroshare/hydroshare/issues/3684
- https://github.com/hydroshare/hydroshare/issues/3685
- https://github.com/hydroshare/hydroshare/issues/3686
- https://github.com/hydroshare/hydroshare/issues/3687
- https://github.com/hydroshare/hydroshare/issues/3688
- https://github.com/hydroshare/hydroshare/issues/3689
- https://github.com/hydroshare/hydroshare/issues/3690
- https://github.com/hydroshare/hydroshare/issues/3691

**Comment by hydrocheck** [comment]
Beta redeployed/retested.  Updated list:

- https://github.com/hydroshare/hydroshare/issues/3683
- https://github.com/hydroshare/hydroshare/issues/3684
- https://github.com/hydroshare/hydroshare/issues/3685
- https://github.com/hydroshare/hydroshare/issues/3686
- https://github.com/hydroshare/hydroshare/issues/3687
- https://github.com/hydroshare/hydroshare/issues/3688
- https://github.com/hydroshare/hydroshare/issues/3689
- https://github.com/hydroshare/hydroshare/issues/3690
- https://github.com/hydroshare/hydroshare/issues/3691
- https://github.com/hydroshare/hydroshare/issues/3692
- https://github.com/hydroshare/hydroshare/issues/3693
- https://github.com/hydroshare/hydroshare/issues/3694
- https://github.com/hydroshare/hydroshare/issues/3695
- https://github.com/hydroshare/hydroshare/issues/3696
- https://github.com/hydroshare/hydroshare/issues/3697
- https://github.com/hydroshare/hydroshare/issues/3698
- https://github.com/hydroshare/hydroshare/issues/3699
