### ISSUE TITLE
Release Checklist 1.28.1

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3756]
### Issues in Release
- [x] #3752 make iquest more restrictive so as not to pick up temporary zips @hyi
- [x] #3754 Fix SOLR harvesting crashes due to incomplete and/or corrupt resources @alvacouch 
- [x] #3618 HydroShare Schema.org Implementation @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. ./hsctl managepy compute_bag_checksum_for_published_resources

**Comment by alvacouch** [comment]
I checked out the SOLR encoding with the separate sanity/debugging command solr_prepare and it works fine. I ran the solr_update and it works fine:
```
SOLR count = 4287
Django count = 4287
Django contains 4237 discoverable resources and 50 replaced resources
0 resources in Django refreshed in SOLR
SOLR contains 4237 discoverable resources and 50 replaced resources
0 resources not in Django removed from SOLR
```
It checks out.
