### ISSUE TITLE
Release Checklist 1.30

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3771]
### Issues in Release
- [x] fixed schema.org syntax issue #3761 @hyi
- [x] Fix access control management command messages. #3765 @alvacouch 
- [x] added get_modified_time() and test #3768 @hyi 
- [x] Fix hs_tracking stats yesterdays-variables command #3763 @sblack-usu 
- [x] Celery upgrade #3769 @sblack-usu 
- [x] #3716 raster folder #3730 @sblack-usu 
- [x] #3779 improved quota usage update code in Django @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [NA] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Started 8:55am EDT. Completed 9:36am EDT
1. 28 seconds total downtime
1. SOLR contains 4442 discoverable resources and 51 replaced resources

**Comment by hydrocheck** [comment]
* https://github.com/hydroshare/hydroshare/issues/3785 is the only beta release bug not traceable back to the 502 Response Codes issue
