### ISSUE TITLE
Release Checklist 1.31

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3801]
### Issues in Release
- [x] #3135 Migrate NetCDF @sblack-usu 
- [x] #3249 Migrate Geographic Raster @sblack-usu 
- [x] #3566 Migrate Geographic Feature @sblack-usu 
- [x] #3568 Migrate TimeSeries @sblack-usu 
- [x] #3796 Group Oauth Registration @sblack-usu 
- [x]  #3798 Fix web app icon @sblack-usu 
- [x] #3800 analytics encoding fix @sblack-usu 
- [x] #3790 added collection constraint into checksum query @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]
