### ISSUE TITLE
Release Checklist 1.31.1 Hotfix

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3819]
### Issues in Release
- [x] #3813 Nginx reverse proxies too much @alvacouch 
- [x] #3815 Verify applaunch tracking redirect url @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. nginx/config-files/hydroshare-ssl-nginx.conf.template needs to be manually updated
2. env.sh on nginx1 needs to be manually updated to look for fist match for RUNNING_VM paramter (check beta to see difference)
3. nginx1 hydroshare-ssl-nginx.conf needs to be manually updated

**Comment by hydrocheck** [comment]
1. https://github.com/hydroshare/hydroshare/issues/3821
