### ISSUE TITLE
Release Checklist 1.32

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3824]
### Issues in Release
- [x] #3629 improve group loading page layout @Maurier 
- [x] #3735 The map tab on the Discover page never completes loading @Maurier 
- [x] #3249 Migrate geographic raster resources to composite resource type @sblack-usu 
- [x] #3803 Copy Discoverable Resource Bug @sblack-usu 
- [x] #3807 Update HydroShare Legend with content types @sblack-usu 
- [x] #3534 Manage access not working for groups @Maurier (This bug still exists.  I'm leaving the changes for this issue as it does not introduce regressions.)
- [x] #3804 Word wrap needed in display of aggregation metadata text @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

**Comment by hydrocheck** [comment]
No issues
