### ISSUE TITLE
Release Checklist 1.32.1

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3833]
### Issues in Release
- [x] #3830 Resource without header fix @hyi 
- [x] #3741 Edit fields aren't updated when file metadata auto extracted into the resource @Maurier 
- [x] PR #3832 not to send out quota warning emails on debug server @hyi 
- [x] PR #3820 added force quota reset management command @hyi
- [x] #1369 Add capability to edit and delete comments @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. To reset quota for all users, run the management command ```./hsctl managepy reset_quota```. To compare user quotas before and after running this quota reset command, run the management command ```./hsctl managepy dump_user_quota <output_user_quota_csv_file_name>``` before and after running the quota reset command with different output user quota csv file names for comparison with quota changes.
