### ISSUE TITLE
Release 1.34

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3892]
### Issues in Release
- [x] #3863 README.md sometimes does not display @sblack-usu 
- [x] PR #3853 Frontend ping endpoint (deployed dark) @cuahsimarko 
- [x] #3868 HSAPI returns non-published resource when filtering on "published" @sblack-usu 
- [x] #3862 Group membership confirmation does not work from email @sblack-usu 
- [x] #3893 Pull in latest hs_docker_base 1.13 @sblack-usu 
- [x] #3889 Remove login check on tokens when not resetting passwords @sblack-usu 
- [x] #3888 Prevent permanently published resource from becoming editable when new version is deleted @hyi
- [x] PR #3896 handle validation error when file not on irods @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1.
