### ISSUE TITLE
Release Checklist 1.35

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3948]
### Issues in Release
- [x] #3887 redirect subdomains other than www on port @cbcunc 
- [x] PR #3933 upgrade deprecated setting MIDDLEWARE_CLASSES to MIDDLEWARE @sblack-usu 
- [x] #3902 fix point/box radio selectors @sblack-usu 
- [x] PR [#3919](https://github.com/hydroshare/hydroshare/pull/3913) include checksum on file listing @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Changes in nginx/config-files/hs-nginx.conf need to be coordinated for manual update
  * Copy hydroshare-ssl-nginx-ingress.conf.template to nginx/config-files/hydroshare-ssl-nginx.conf on outer proxy
  * Run ./hs_proxy on outer proxy
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Changes in nginx/config-files/hs-nginx.conf need to be coordinated for manual update

    Copy hydroshare-ssl-nginx-ingress.conf.template to nginx/config-files/hydroshare-ssl-nginx.conf on outer proxy
    Run ./hs_proxy on outer proxy
