### ISSUE TITLE
Release Checklist 1.36

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3961]
### Issues in Release
- [ ] #3938 manage access tool tip fix @pkdash 
- [ ] #3946 Clarify shareable option (manage access) @pkdash 
- [ ] #3953 Turn on pseudo threads in gevent @alvacouch 
- [ ] #3959 Change JH app target URL to jupyterhub.cuahsi.org @Castronova 
- [ ] #3852 async tasks @hyi 

### Beta Deployment
- [ ] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [ ] nginx/config-files/hydroshare-ssl-nginx.conf.template
- [ ] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [ ] Deployed to Beta
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issues
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] nginx/config-files/hydroshare-ssl-nginx.conf.template
- [ ] Maps API key is correct and maps are displaying correctly
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]
