### ISSUE TITLE
Release Checklist 1.37

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3987]
### Issues in Release
- [x] PR #3980 Bump node-fetch from 2.6.0 to 2.6.1 in /hs_discover @cuahsimarko 
- [x] PR #3985 pushing serializing of resource to the serializer @sblack-usu
- [x] #3838 Add all required fields to the Account Creation page @hyi

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. No manual file changes or migrations are necessary
