### ISSUE TITLE
Release Checklist 1.39.1

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4020]
### Issues in Release
- [x] PR #3971 Async tasks @sblack-usu @hyi 
- [x] #3931 collection resource refuses resources that are not sharable, but are public @pkdash 
- [x] PR #4002 make reset quota command to take user zone into account @hyi
- [x] #3981 Allow public/discoverable resource to be part of collection resource @pkdash 
- [x] PR #3993 Updating hsctl to read hydroshare home directory from config @dan-palmer1 
- [x] PR #4002 make reset quota command to take user zone into account @hyi 
- [x] PR #4026 removed the duplicate create_bag_files call in download view func @hyi 
- [x] PR #4010 make empty author name display on resource landing page @hyi 
- [x] PR #4039 corrected legacy unspecified user profile fields @hyi

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. There is a minor change to hsctl

**Comment by sblack-usu** [comment]
To test:
async tasks (resource delete, bag download, zipped download, unzip)
race condition on creating/download the resource bag

**Comment by hydrocheck** [comment]
* https://github.com/hydroshare/hydroshare/issues/4045
* https://github.com/hydroshare/hydroshare/issues/4046
* https://github.com/hydroshare/hydroshare/issues/4047
* https://github.com/hydroshare/hydroshare/issues/4048
* https://github.com/hydroshare/hydroshare/issues/4049

Also, failures start to occur when more than a few async tasks are running.

![2020-11-async-resource-deletions-v01 (1)](https://user-images.githubusercontent.com/43424907/100403499-1346ca00-302d-11eb-9d94-929eae290c97.png)
![2020-11-async-file-downloads-v01 (1)](https://user-images.githubusercontent.com/43424907/100403502-1477f700-302d-11eb-8cba-a693b15c270c.png)
![2020-11-async-bag-downloads-v01 (1)](https://user-images.githubusercontent.com/43424907/100403503-15a92400-302d-11eb-9592-3613d22fda9e.png)

**Comment by martinseul** [comment]
@sblack-usu closing this as it has been deployed
