### ISSUE TITLE
Release Checklist 1.40

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4079]
### Issues in Release
- [x] #3767 "How to cite" @cuahsimarko 
- [x] #4040 Node fix - for Jenkins errors @dan-palmer1 
- [x] #4044 Bump highlight.js from 9.18.1 to 9.18.5 in /hs_discover @cuahsimarko 
- [x] #3928 Bag ingestion @sblack-usu 
- [x] #4059 Fix for local development solr schema @dan-palmer1 
- [x] #4040 Node fix - for Jenkins errors @dan-palmer1 
- [x] #4081 async - default username to empty, created timestamp, index username @hyi @sblack-usu 
- [x] #4083 disable celery mailchimp sync in favor of using jenkins job @sblack-usu 

#### hotfixes deployed previously without a tag
- [x] #4071 Fix disappearing user_type bug @sblack-usu 
- [x] #4063 Enable an empty user type user to select the first entry in the user type list @hyi

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. There are changes to `hsctl` and `nginx/config-files/hydroshare-ssl-nginx.conf.template` which need to be manually updated before deploy in zdt
2. Two management commands need to be run, there are changes to the rdf/xml and it needs to be regenerated.  First run `regenerate_xml_files_composite_resource`, then after it completes, run `set_bag_dirty`.  These are long running tasks which take several hours each.

**Comment by hydrocheck** [comment]
* https://github.com/hydroshare/hydroshare/issues/4089
* https://github.com/hydroshare/hydroshare/issues/4090
* https://github.com/hydroshare/hydroshare/issues/4091
* https://github.com/hydroshare/hydroshare/issues/4092

**Comment by hydrocheck** [comment]
Nothing to add from hotfix testing

**Comment by sblack-usu** [comment]
`regenerate_xml_files_composite_resource` https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Production-Deployment/job/prod-hsctl-command/98/console

**Comment by sblack-usu** [comment]
`set_bag_dirty` https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Production-Deployment/job/prod-hsctl-command/99/console
