### ISSUE TITLE
Release Checklist 1.41

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4106]
### Issues in Release
- [x] Add watchdog URLs in http mode to outer and inner nginx proxies #4096 @alvacouch 
- [x] turn off TaskNotification creation for api downloads #4098 @sblack-usu 
- [x] url encode resourcemap urls #4099 @sblack-usu 
- [x] Fix botch in adding resources to collections #3932 @sblack-usu 
- [x] updated vocab schema.org url to be compatible with DataONE #4101 @hyi
- [x] add missing abstract to timeseries rdf/xml #4100 @sblack-usu 
- [x] fixed the carriage return issue #3899 @hyi 
- [x] Remove frontend messages for large files download #3520 @cuahsimarko 
- [x] encode urls in aggregation map rdf/xml file #4103 @sblack-usu 
- [x] web service endpoints #3825 @kjlippold @sblack-usu 
- [x] Split bagit file creation from bag zipping to allow bagit file downloads #4102 @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. `HSWS` keys need to be coordinated with local_settings
2. `nginx/config-files/hydroshare-ssl-nginx.conf.template` changes need to be coordinated
3. ` nginx/hs_proxy/nginx/config-files/hydroshare-ssl-nginx.conf.template` changes need to be coordinated

**Comment by eclark-cuahsi** [comment]
Discussed with @martinseul and we are closing this issue.
