### ISSUE TITLE
Release Checklist 1.42

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#4175]
### Pull Requests in Release
- [ ] ~~Limited editing of published resource #3969 @pkdash~~ 
- [x] Change from UNC addresses to RENCI addresses #4112 @alvacouch 
- [x] get versioning moved to async #4116 @hyi
- [x] Resource Landing Page and Discover Linked Functionality #4117 @cuahsimarko 
- [x] Allow dev deployments to survive network interruption #4129 @cuahsimarko 
- [x] 4127 res delete async - discovery appears to work after resources are deleted async'ly #4137 @hyi  
- [x] Discover Safari and Mobile Compatibility #4160 @cuahsimarko 
- [x] Navbar Modularize #4162 @cuahsimarko 
- [x] Fix for SOLR corruption problem. #4167 @alvacouch 
- [x] No exception when checking for undo involving inactive user or group #4168 @alvacouch 
- [x] Notification app #4169 @cuahsimarko
- [x] add missing realtime processing to SOLR. #4173 @alvacouch 
- [x] Remove stale code make navbar more independent #4174 @cuahsimarko 
- [x] Bump elliptic from 6.5.3 to 6.5.4 in /hs_discover #4176 @cuahsimarko 
- [x] 4179 fix composite resource discovery #4180 @alvacouch 
- [ ] ~~django will cascade delete for us #4182 @sblack-usu~~

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template - __CHANGES IN THIS RELEASE__
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

**Comment by cbcunc** [comment]
Limited editing of published resource #3969 @pkdash was withdrawn from this release.

**Comment by hydrocheck** [comment]
👍 
No blockers
