### ISSUE TITLE
Release Checklist 1.43

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4201]
### Issues in Release
- [ ] #4181 scheme org update @hyi 
- [ ] #4087 delete box update @soumyapurohit 
- [ ] #4191 meta xml file check fix for check_irods_files @sblack-usu 
- [ ] #4184 schema org bug @hyi
- [ ] #4179 discover logical file attributes @alvacouch 
- [ ] #4195 Bump y18n from 4.0.0 to 4.0.1 in /hs_discover @sblack-usu 
- [ ] #3936 discovery backend improvements @alvacouch 

### Beta Deployment
- [ ] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [ ] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [ ] Deployed to Beta
- [ ] check_resource beta results match current www results
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issues
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

**Comment by hydrocheck** [comment]
Small issues from initial testing:
https://github.com/hydroshare/hydroshare/issues/4214
https://github.com/hydroshare/hydroshare/issues/4215

Will do final regression testing within the next couple of days, as discussed with the team.
