### ISSUE TITLE
Release Checklist 1.44

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4229]
### Issues in Release
- [x] #4219 Users unable to reset password @sblack-usu 
- [x] #3702 Replace update_index with solr_update in hsctl @cbcunc 
- [x] #4199 Consolidating OGC URL Endpoints @jcalhoon96 
- [x] #4200 Copying citations includes whitespace @sblack-usu 
- [x] #4222 Add support for metadata on logical files @sblack-usu 
- [x] #4228 Bump lodash version @sblack-usu 
- [x] #4227 Bump url-parse version @sblack-usu 
- [x] #4226 bump hosted-git-info version @sblack-usu 
- [x] #4230 update the phone number validation message along with error styling @sblack-usu 
- [x] #4165 Title will use the fixed solr index @alvacouch 
- [x] #2559 Allow editing of metadata for published resources. @pkdash 
- [x] #3826 Add web service endpoints to content-level metadata for multidimensional content type @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. hsctl changes need to be coordinated for deployment

**Comment by hydrocheck** [comment]
1. https://github.com/hydroshare/hydroshare/issues/4232
1. https://github.com/hydroshare/hydroshare/issues/4233
2. https://github.com/hydroshare/hydroshare/issues/4234
3. https://github.com/hydroshare/hydroshare/issues/4235
4. https://github.com/hydroshare/hydroshare/issues/4236
