### ISSUE TITLE
Release Checklist 1.45

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4243]
### Issues in Release
- [x] #3792 Model Instance and Model Program Aggregation Types @pkdash 
- [x] #2829 When rating resource and not logged in, system doesn't redirect after login @hyi
- [x] #3196 profile media file @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] check_resource beta results match current www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

**Comment by hydrocheck** [comment]
1. https://github.com/hydroshare/hydroshare/issues/4248
2. https://github.com/hydroshare/hydroshare/issues/4249
3. https://github.com/hydroshare/hydroshare/issues/4250
4. https://github.com/hydroshare/hydroshare/issues/4251
5. https://github.com/hydroshare/hydroshare/issues/4252
