### ISSUE TITLE
Release Checklist 1.46

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4299]
### Issues in Release
- [x] #2080 file delete confirmation message change @pkdash 
- [x] #4279 Readable error message for metadata schema validation @pkdash 
- [x] #4244 Update HydroShare Terms Page with Model Program/Instance @sblack-usu 
- [x] #4277 split celery logging @alvacouch 
- [x] #4133 Update GeoServer when deleting files @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. iptables secured improved with deployment.

**Comment by hydrocheck** [comment]
* https://github.com/hydroshare/hydroshare/issues/4300
