### ISSUE TITLE
Release Checklist 1.47

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4320]
### Issues in Release
- [x] #4309 API endpoint /scimeta/custom currently requires edit permissions to GET @sblack-usu 
- [x] #4316 Bump url-parse from 1.5.1 to 1.5.3 in /hs_discover @sblack-usu 
- [x] #4314 Bump color-string from 1.5.3 to 1.6.0 in /hs_discover @sblack-usu 
- [x] #4312 Bump path-parse from 1.0.6 to 1.0.7 in /hs_discover @sblack-usu 
- [x] #4318 update his central url to https @sblack-usu 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. No migration or manual updates to environment files necessary.
