### ISSUE TITLE
Release Checklist 1.48

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4342]
### Issues in Release
- [x]  #4340  @pkdash 
- [x] #3685 @sblack-usu 
- [x] #3684 @sblack-usu 
- [x] #3683 @sblack-usu 
- [x] #4331 @pkdash 
- [x] #4333 @pkdash 
- [x] #4335 @sblack-usu 
- [x] #4070 @pkdash 
- [x] #4272 @sblack-usu 
- [x] #4322 @sblack-usu 
- [x] #4329 @alvacouch 
- [x] #4336 @pkdash 
- [x] #2942 @pkdash 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]
