### ISSUE TITLE
Release Checklist 1.50

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4416]
### Issues in Release
- [x] #4368 @sblack-usu 
- [x] #4369 @sblack-usu 
- [x] #4147 @pkdash 
- [x] #4157 @pkdash 
- [x] #4401 @pkdash 
- [x] #4355 @sblack-usu 
- [x] #4357 @Maurier 
- [x] #4322 @sblack-usu 
- [x] #4149 @pkdash 
- [x] #4347 @pkdash 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. No manual file updates are necessary
2. No migration is necessary
3. Model Program and Model Instance RDF/XML must be regenerated.  (beta https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-hsctl-command/200/console)

**Comment by sblack-usu** [comment]
Full example resource for model program json schema: 54f02a2a1a4b4aeaa78f80a2ae2785c2
