### ISSUE TITLE
Release Checklist 1.51

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4439]
### Issues in Release
- [x] #4297 @Maurier 
- [x] #3529 @sblack-usu 
- [x] #4434 @pkdash 
- [x] #4156 @pkdash 
- [x] #4424 @sblack-usu 
- [x] #4211 @pkdash 
- [x] #3529 @Maurier 
- [x] #4322 @sblack-usu 
- [x] #4410 @pkdash 
- [x] #4405 @pkdash 
- [x] #4390 @sblack-usu 

### Beta Deployment
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. No manual file changes were identified
2. Migration is necessary

**Comment by hydrocheck** [comment]
1. https://github.com/hydroshare/hydroshare/issues/4446
2. https://github.com/hydroshare/hydroshare/issues/4445
3. https://github.com/hydroshare/hydroshare/issues/4444
4. https://github.com/hydroshare/hydroshare/issues/4443
