### ISSUE TITLE
Release Checklist 1.52

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4458]
### Issues in Release
- [x] #4449 @hyi
- [x] #4450 @hyi 
- [x] #4028 @hyi 
- [x] #3261 @pkdash 
- [x] #4457 @hyi 
- [x] #4415 @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. The management command for fixing versioning issues needs to be run as follows: ```./hsctl managepy fix_resource_versioning res_version_fix.csv``` where res_version_fix.csv can be downloaded from the last comment in this [github PR](https://github.com/hydroshare/hydroshare/pull/4397). After running this management command, another management command for resource versioning fix verification can be run as ```./hsctl managepy output_wrong_versioning_resources```. If output is clean, all resources with versioning issues are fixed. There is one resource from Dave that may show up in the output which Dave will delete afterwards. This management command will be run by @hyi who will let @sblack-usu know after this is taken care of on production after the release.
2. The following management command for migrating the deprecated relation meta types needs to be run **only** after the commands as listed above are executed:
     `./hsctl managepy migrate_relation_types`
3. hsmodels needs to be released shortly after for the changes in Source metadata.
