### ISSUE TITLE
Release Checklist 1.53

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4513]
### Issues in Release
- [x] #3070 @pkdash 
- [x] #3071 @pkdash 
- [x] #4464 @hyi 
- [x] #2824 @devincowan 
- [x] #4466 @pkdash 
- [x] #3614 @devincowan 
- [x] #2895 @devincowan 
- [x] #2827 @devincowan 
- [x] #4486 @devincowan 
- [x] #4474 @devincowan 
- [x] #2910 @devincowan 
- [x] #4324 @devincowan 
- [x] #4472 @hyi
- [x] #4473 @hyi 
- [x] #4493 @devincowan 
- [x] #4475 @pkdash 
- [x] #4488 @sblack-usu 
- [x] #4264 @alvacouch 
- [x] #4363 @hyi 
- [x] #3072 @pkdash 
- [x] #3785 @devincowan 
- [x] #3608 @devincowan 
- [x] #4471 @pkdash 
- [x] #4495 @pkdash 
- [x] #3387 @sblack-usu
- [x] #4443 @devincowan 
- [x] #4500 @sblack-usu 
- [x] #4499 @sblack-usu 
- [x] #4496 @pkdash 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Need to run this management command: `migrate_ispartof_not_collection_related`
2. Need to run this management command ```fix_resource_versioning_date``` with this input file as input argment: 
[version_res_date.csv](https://github.com/hydroshare/hydroshare/files/8143297/version_res_date.csv)

**Comment by sblack-usu** [comment]
I'm still putting together this release checklist.  The PRs are currently linked and need to be updated to issues.  Sorry, lots of things in flight right now and working on this as I get the time.  Thanks for bringing those issues to my attention.
