### ISSUE TITLE
Release Checklist 1.54

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4554]
### Issues in Release
- [x] #2806 @devincowan 
- [x] #4473 @hyi 
- [x] #4535 @pkdash 
- [x] #4524 @pkdash 
- [x] #3526 @devincowan 
- [x] #4140 @devincowan 
- [x] #4374 @devincowan 
- [x] #2313 @pkdash 
- [x] #2275 @devincowan 
- [x] #4531 @pkdash 
- [x] #3073 @pkdash 
- [x] #4520 @sblack-usu 
- [x] #3053 @devincowan 
- [x] #4090 @devincowan 
- [x] #3451 @devincowan 
- [x] #2793 @devincowan 
- [x] #4541 @pkdash 
- [x] #3534 @devincowan 
- [x] #4530 @pkdash 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. The db needs to be migrated.
2. No configuration files need to be manually updated.
3. Need to run management command `migrate_script_resources`

**Comment by pkdash** [comment]
@sblack-usu Checklist item `4390 file based json api` should not be me to verify.

**Comment by devincowan** [comment]
@pkdash that was my bad, I thought it was your issue not one of @sblack-usu

**Comment by sblack-usu** [comment]
That one shouldn't even be in the release checklist, it was part of an earlier release.  It got picked up because the branch name in https://github.com/hydroshare/hydroshare/pull/4529 had a typo #4406->#4066

It is removed, sorry for the confusion.

**Comment by hydrocheck** [comment]
1. https://github.com/hydroshare/hydroshare/issues/4561
2. https://github.com/hydroshare/hydroshare/issues/4560

**Comment by pkdash** [comment]
@sblack-usu Verified and closed #4524 and #4541.
