### ISSUE TITLE
Release checklist 1.55

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4594]
### Issues in Release
- [x] #4553 @hyi 
- [x] #2280 @pkdash 
- [x] #2979 @pkdash 
- [x] #4557 @sblack-usu 
- [x] #4588 @pkdash 
- [x] #4552 @devincowan 
- [x] #4587 @devincowan 
- [x] #4559 @devincowan 
- [x] #4498 @devincowan 
- [x] #4568 @devincowan 
- [x] #4456 @devincowan 
- [x] #4484 @devincowan 
- [x] #3806 @devincowan 
- [x] #3531 @devincowan 
- [x] #3699 @devincowan 
- [x] #3464 @devincowan 
- [x] #4066 @devincowan 
- [x] #4375 @devincowan 
- [x] #3464 @devincowan 
- [x] #4597 @devincowan 

### Beta Deployment
- [X] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [X] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. RC contains [one migration](https://github.com/hydroshare/hydroshare/compare/master...develop#diff-8c1b7c2af2d234e7d086656420ece026191a6bf1f13657c31d742f77701818bc)
2. No configuration files need to be manually updated.
3. No management commands

Diff: https://github.com/hydroshare/hydroshare/compare/master...RC-1.55
