### ISSUE TITLE
Release Checklist 1.56

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4642]
### Issues in Release
- [x] #4527 @devincowan 
- [x] #4538 @pkdash 
- [x] #3429 @devincowan 
- [ ] #4571 @devincowan 
- [x] #3077 @devincowan 
- [x] #4572 @pkdash 
- [x] #4593 @pkdash
- [x] #3554 @pkdash 
- [x] #4590 @devincowan 
- [x] #4065 @devincowan 
- [x] #4611 @pkdash 
- [x] #4633 @devincowan 
- [x] #2637 @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Need to run this management command: `fix_missing_license_statement`
2. Contains several migrations
3. Beta deploy with data update resulted in 504 on active worker and _very slow_ resource creation on inactive worker--maintenance page will be needed.
4. This deploy uses a [tagged version of hsmodels](https://github.com/hydroshare/hsmodels/tree/0.5.0). After HS 1.56 is released, we need to release hsmodels 0.5.0. We should also then revert the [pip install by tag in our Dockerfile](https://github.com/hydroshare/hydroshare/blob/develop/Dockerfile#L11)
5. There are modifications to `hsctl`:
https://github.com/hydroshare/hydroshare/pull/4612/files#diff-294a3b9d97294b3341d58173646407cc9fb2936641d21a701ace731b5fbda257R121

DIFF: https://github.com/hydroshare/hydroshare/compare/master...RC-1.56

**Comment by hydrocheck** [comment]
* https://github.com/hydroshare/hydroshare/issues/4658
* https://github.com/hydroshare/hydroshare/issues/4659
* https://github.com/hydroshare/hydroshare/issues/4660
* https://github.com/hydroshare/hydroshare/issues/4661
