### ISSUE TITLE
Release Checklist 1.57.1

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4689]
### Issues in Release
- [x] #4699 @devincowan 
- [x] #4571 @devincowan 
- [x] #4626 @pkdash 
- [x] #4679 @devincowan 
- [x] #4648 @devincowan 
- [x] #4660 @devincowan 
- [x] #4676 @devincowan 
- [x] #4661 @devincowan 
- [x] #4646 @devincowan 
- [x] #4659 @devincowan 
- [x] #4565 @hyi 
- [x] #4602 @pkdash 
- [x] #4656 @pkdash 
- [x] #4640 @pkdash 
- [x] #4674 @pkdash 
- [x] #4091 @pkdash 
- [x] #4592 @pkdash 
- [x] #4650 @pkdash 
- [x] #4690 @pkdash 

DIFF: https://github.com/hydroshare/hydroshare/compare/1.56.1...rc-1.57.1

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [X] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Maps API key is correct and maps are displaying correctly
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Includes management command: [remove_missing_profile_imgs_from_db](https://github.com/hydroshare/hydroshare/blob/1.57.1/theme/management/commands/remove_missing_profile_imgs_from_db.py)
2. Contains several migrations. These should be run BEFORE the management commands
3. The following 5 management commands need to be run in the order they are listed here for migrating model resources to composite resource (@pkdash): *BUT WE WILL WAIT TO RUN THESE SOMETIME IN AUG
3.1 [hs_core/management/commands/prepare_model_instance_resources_for_migration.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/prepare_model_instance_resources_for_migration.py)
3.2 [hs_core/management/commands/migrate_model_program_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_model_program_resources.py)
3.3 [hs_core/management/commands/migrate_model_instance_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_model_instance_resources.py)
3.4 [hs_core/management/commands/migrate_modflow_instance_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_modflow_instance_resources.py)
3.5 [hs_core/management/commands/migrate_swat_model_instance_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_swat_model_instance_resources.py)

4. Running the management commands will take ~4hrs and require maint. page

## Our plan for deploy
We will deploy this release to Production but will NOT run Pabitra's management commands until August

**Comment by devincowan** [comment]
@pkdash just running 3.1-3.3 on Beta took over 2hrs 45min.  3.4 and 3.5 took an additional hour
I think it's safe to say that the management commands in this release are going to take 3-4hrs to run
We can run them as a batch so that no one has to sit and watch them run. But you said we need maintenance page up. 4hrs is a long time... not sure what that will mean for our desired deployment time. I'm thinking maybe early am East Coast

**Comment by devincowan** [comment]
@pkdash I also had the realization that we need to run the db migrations _AFTER_ we run the management scripts, don't we?

**Comment by dtarb** [comment]
I am OK with early morning ET.  I am also surprised by the length of time, but it is what it is.  4 hrs 5 am to 9 am is OK with me.

**Comment by devincowan** [comment]
## Our plan for deploy
1. We will run deploy of 1.56.1 with data_update Beta on Monday morning 7/18/22
2. We will take a snapshot of that beta deploy in v-sphere. We try to have this around "for a while" so that if issues crop up, we can compare (this is not meant to restore, this is a manual process)
3. On 7/19/22 pm ET, we will put up the maintenance page on production and snapshot production in v-sphere
4. We will run the deployment to production including migrations, then migrate the resources using management commands
5. Excessive sniff tests of production before turning off the maintenance page and running the swap

**Comment by devincowan** [comment]
```
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
cutoff=datetime.datetime.now(tz=timezone.utc) - datetime.timedelta(days=14)
User.objects.filter(last_login__gte=cutoff).values('email')

**Comment by devincowan** [comment]
### Phase II:
[ ] On Friday 7/29/2022 ~4pm EDT, edit the [copy-remote-to-local](http://ci.hydroshare.org:8080/view/03-Housekeeping/job/copy-remote-to-local/configure) unclick the “Build periodically” box and save the job config. Add it back later.
[ ] Run the copy-remote-to-local job. It should finish ~4pm on Saturday
[ ] Then run a deploy of 1.57.1 to beta _with db migration and data update_
[ ] This should finish before Monday morning
1. 1pm Monday Aug 1st, re-enable the [copy-remote-to-local](http://ci.hydroshare.org:8080/view/03-Housekeeping/job/copy-remote-to-local/configure) job. Run this management command [delete_model_aggregation_folder_from_irods](https://github.com/hydroshare/hydroshare/blob/model-migration-folder-cleanup/hs_core/management/commands/delete_model_aggregation_folder_from_irods.py) to remove empty dirs on beta irods
3. We will run deploy of 1.56.1 with data_update Beta
4. We will take a snapshot of that beta deploy in v-sphere. We try to have this around "for a while" so that if issues crop up, we can compare (this is not meant to restore, this is a manual process)
5. We will put up the maintenance page on production and snapshot production in v-sphere
6. We will migrate the resources using management commands on production
5.0 The following 5 management commands need to be run in the order they are listed here for migrating model resources to composite resource (@pkdash): *BUT WE WILL WAIT TO RUN THESE SOMETIME IN AUG
5.1 [hs_core/management/commands/prepare_model_instance_resources_for_migration.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/prepare_model_instance_resources_for_migration.py)
5.2 [hs_core/management/commands/migrate_model_program_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_model_program_resources.py)
5.3 [hs_core/management/commands/migrate_model_instance_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_model_instance_resources.py)
5.4 [hs_core/management/commands/migrate_modflow_instance_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_modflow_instance_resources.py)
5.5 [hs_core/management/commands/migrate_swat_model_instance_resources.py](https://github.com/hydroshare/hydroshare/blob/rc-1.57/hs_core/management/commands/migrate_swat_model_instance_resources.py)
7. Excessive sniff tests of production before turning off the maintenance page and running the swap
