### ISSUE TITLE
Release Checklist 1.58

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4739]
### Issues in Release
- [x] #4728 @devincowan 
- [x] #4655 @pkdash 
- [x] #4654 @pkdash 
- [x] #4220 @devincowan 
- [x] #4131 @pkdash 
- [x] #4393 @pkdash 
- [x] #2368 @devincowan 
- [x] #3067 @devincowan 
- [x] #4729 @hyi 
- [x] #4709 @hyi 
- [x] #4716 @devincowan 
- [x] #4152 @hyi 
- [x] #4721 @devincowan 
- [x] #4604 @Maurier 
- [x] #4695 @devincowan 
- [x] #4502 @devincowan 
- [x] #4596 @Maurier 
- [x] #4711 @pkdash 
- [x] #4696 @pkdash 
- [x] #4693 @pkdash 
- [x] #4653 @pkdash 
- [x] #4652 @pkdash 
- [x] #4753 @pkdash 
- [x] #4752 @hyi 
- [x] #4759 @devincowan and @hyi 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Maps API key is correct and maps are displaying correctly
- [ ] check_resource www results match pre-deployment www results
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### DIFF
https://github.com/hydroshare/hydroshare/compare/master...rc-1.58

### Notes relevant to deployment
1. The following management command needs to be executed:
`set_aggregations_dirty  --aggr_type  ModelProgramLogicalFile`
2. Contains modification to `nginx/config-files/hydroshare-ssl-nginx.conf.template` that will need to be updated manually
    - /projects/hydroshare/hsdata/zdt/beta/nginx/nginx/config-files
    - /projects/hydroshare/hsdata/zdt/prod/hs_proxy/nginx/config-files
4. `hs_core/management/commands/reorder_authors.py` management command

**Comment by hydrocheck** [comment]
* https://github.com/hydroshare/hydroshare/issues/4752

**Comment by devincowan** [comment]
@pkdash discovered an additional regression related to unzipping
* https://github.com/hydroshare/hydroshare/issues/4759
@hyi perhaps we can confer -- note that I just witnessed this issue on 20c0f8e3a01708dfb8f754e93d2774ba8dbbd86e, which includes the fixes for both issues (#4752 and #4753) that Neal mentioned above. So this needs to be addressed separately.
