### ISSUE TITLE
Release Checklist 1.59

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4780]
### Issues in Release
- [x] #4146 @pkdash 
- [x] #4763 @pkdash 
- [x] #4749 @pkdash 
- [x] #4748 @pkdash
- [x] #4714 @hyi 
- [x] #4758 @hyi 
- [x] #4773 @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

Diff: https://github.com/hydroshare/hydroshare/compare/master...rc-1.59

**Comment by martinseul** [comment]
@devincowan can this be closed?
