### ISSUE TITLE
Release Checklist 2.1

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4832]
### Issues in Release
- [x] #4726 @devincowan 
- [x] #4818 @devincowan 
- [x] #4795 @devincowan 
- [x] #4811 @devincowan 
- [x] #4837 @devincowan 
- [x] #4771 @devincowan 
- [x] #4820 @devincowan 
- [x] #4842 @devincowan 
- [x] #4815 @pkdash 
- [x] #4215 @devincowan 
- [x] #3364  @devincowan 
- [x] #4848 @pkdash 
- [x] #4830 @devincowan 
- [x] #3024 @pkdash 
- [x] #3098 @devincowan 
- [x] #4863 @devincowan
- [x] #4861 @devincowan 
- [x] #4873 @devincowan
- [x] #4793 @devincowan 
- [x] #4871 @devincowan
- [x] #2538 @pkdash 
- [x] #4894 @devincowan 
- [x] #4853 @pkdash 
- [x] #4897 @devincowan 
- [x] #3936 @pkdash 
- [x] #4808 @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Check that maint mode works
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Does require manual changes to [nginx/config-files/hydroshare-ssl-nginx.conf.template](https://github.com/hydroshare/hydroshare/pull/4875/files#diff-a2fac074197dd5212a0ea82a1dcfe964c6064fe0b33ea0507f62d0d04904d585)

    - /projects/hydroshare/hsdata/zdt/beta/nginx/nginx/config-files

1. Need to update local_settings.py on beta with `DISABLE_TASK_EMAILS=True` (/projects/hydroshare/hsdata/zdt/beta/deploy/local_settings.py)
3. on prod, should be `DISABLE_TASK_EMAILS=False`
4. Migration for HIL is non-breaking (no downtime)
5. Ensure DEFAULT_SUPPORT_EMAIL is set and that there is a matching user
6. Author order management command does not need to be run
7. We can test publication XML deposition using Crossref Sandbox by setting DEBUG=False and USE_CROSSREF_TEST = True (as well as CROSSREF_LOGIN_ID and CROSSREF_LOGIN_PWD) on Beta. Care should be taken to ensure that the email backend is set to CONSOLE and not SMTP so that users don't receive emails from beta during testing (also check DISABLE_TASK_EMAILS)
8. Geoconnex discovery PR does require running management command: `update_relations_from_geoconnex` after migrations, before swap

### DIFF
https://github.com/hydroshare/hydroshare/compare/2.0.1...rc-2.1
