### ISSUE TITLE
Release Checklist 2.0

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4833]
### Issues in Release
- [x] #4802 @devincowan 
- [x] #4738 @pkdash 
- [x] #4781 @pkdash @cbcunc 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. PG modifications to the codebase included here really only impact local development builds. For production, we plan a new VM build and install
2. Need to make updates to ZDT: https://github.com/hydroshare/hs-deployment/commit/a81aae94fd32d8939e1dd42c568cc3f44726239e
3. Need to edit prod swap jenkins job [see beta](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-swap-worker/configure)
4. Includes changes to HSCTL (need to manually update zdt/deploy)
~5. Same for hydroshare-ssl-nginx.conf.template~
~6. PG changes in docker-compose.template~

### Diff
https://github.com/hydroshare/hydroshare/compare/1.60.1...rc-2.0
