### ISSUE TITLE
Release Checklist 2.3

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4936]
### Issues in Release
- [ ] #4868 @devincowan 
- [ ] #4899 @devincowan 
- [ ] #4896 @pkdash 
- [ ] #4916 @devincowan 
- [ ] #4923 @pkdash 
- [ ] #4886 @pkdash 

### Beta Deployment
- [ ] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [ ] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [ ] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [ ] Add any management commands necessary for the deploy to the notes section
- [ ] Deployed to Beta
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issues
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [ ] Snapshot the DB and iRods VM before deploy
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

### DIFF
https://github.com/hydroshare/hydroshare/compare/2.1...rc-2.2
