### ISSUE TITLE
Release Checklist 2.4

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4966]
### Issues in Release
- [x] #4929 @devincowan 
- [x] #4235 @devincowan 
- [x] #4864 @devincowan 
- [x] #4940 @devincowan 
- [x] #4957 @devincowan 
- [x] #4946 @devincowan 
- [x] #4958 @devincowan 
- [x] #4984 @devincowan 
- [x] #4987 @devincowan 
- [x] #4630 @devincowan 
- [x] #4701 @devincowan 
- [x] #4994 @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Migration for profile phones should be "non-breaking"
2. rsync modifications made in Jenkins beta-swap need to be added in the production-swap job
3. https://github.com/hydroshare/hydroshare/pull/4985 This PR has changes to hsctl that will need update on beta and other test/dev systems. We also will update the [ROBOTS_SITEMAP_URLS](https://github.com/hydroshare/hydroshare/blob/develop/hydroshare/settings.py#L183) on production and beta local_settings.py. Currently they map to localhost:8000

### DIFF
https://github.com/hydroshare/hydroshare/compare/2.3.1...rc-2.4
