### ISSUE TITLE
Release Checklist 2.6

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5055]
### Issues in Release
- [x] #5045 by @pkdash and @devincowan 
- [x] #5065 by @devincowan 
- [x] #5022 by @devincowan
- [x] #5082 by @devincowan 
- [x] #5089 by @devincowan 
- [x] #5091 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [x] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
2. ~Run this management command [create_subject_areas_dict](https://github.com/hydroshare/hydroshare/blob/develop/hs_dictionary/management/commands/create_subject_areas_dict.py)~
4. ~Run this management command: [fix_collection_version_missing_ispartof](https://github.com/hydroshare/hydroshare/blob/develop/hs_collection_resource/management/commands/fix_collection_version_missing_ispartof.py)~
5. Contains migrations for Profile-Subject Areas that will break UI on the profile page 

7. We need to run a data update on beta, reset active to 2.5.3, and then deploy with migrations in order to ensure the Subject Areas migration is functional

Git diff:
https://github.com/hydroshare/hydroshare/compare/2.5.3...rc-2.6
