### ISSUE TITLE
Release Checklist 2.7

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5106]
### Issues in Release
- [x] #5102 by @pkdash 
- [x] #5113 by @devincowan 
- [x] #4308 by @devincowan 
- [x] #5111 by @pkdash 
- [x] #5107 by @sblack-usu 
- [x] #5017 by @sblack-usu 
- [x] #5092 by @devincowan 
- [x] #5119 by @pkdash 
- [x] #5122 by @pkdash 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
Check that `DISABLE_HAYSTACK = False` in settings.py

Git diff:
https://github.com/hydroshare/hydroshare/compare/2.6.1...rc-2.7
