### ISSUE TITLE
Release Checklist 2.9

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5160]
### Issues in Release
- [x] #4432 by @devincowan 
- [x] #5044 by @devincowan 
- [x] #5115 by @pkdash 
- [x] #5171 by @devincowan 
- [x] #5168 by @pkdash 
- [x] #5170 by @pkdash 
- [x] #5124 by @devincowan  and @pkdash 
- [x] #5182 by @pkdash 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Snapshots of db must be taken. Release contains widespread update to resourceFiles in [migration](https://github.com/hydroshare/hydroshare/pull/5154/files#diff-4fb2f42e3ab6b084208ef52f6fb31f850d12c97435b356954a49e438b5e61255)
2. [Email sending](https://github.com/hydroshare/hydroshare/pull/5164/files#diff-182216ce9ee2cc3e1f410a911873b12dc126f5e025f7b81f8d5d1ecdfe234b0bR199) should be tested on Beta, but should be done carefully so that other notifications (like Quota) aren't triggered unintentionally.

Git diff:
https://github.com/hydroshare/hydroshare/compare/2.8.1...rc-2.9
