### ISSUE TITLE
Documentation Checklist, Keycloak "Cuahsi SSO"

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#5169]
This checklist details documentation needed to prepare users for the transition to Keycloak integration or "Cuahsi Single Sign on"
To include:

- [x] A sign in banner
- [x] HydroShare Home Page Banner
- [x] Documentation first on help.hydroshare.org ,maybe on cuahsi.org eventually 
- [x] Text on account linking interface

[Text for messaging and image mockups](https://docs.google.com/document/d/19d8QijxCMkgdGEcwuP5dRxpOvM5nt0b3Myvq8vTIqcI/edit)

**Comment by ClaraCogswell** [comment]
#5157

**Comment by ClaraCogswell** [comment]
@sblack-usu @devincowan

**Comment by devincowan** [comment]
closing as complete 2.9.2 release
