### ISSUE TITLE
Release Checklist 2.9.3

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5227]
### Issues in Release
- [ ] #5218 by @sblack-usu 
- [ ] #5217 by @devincowan 
- [ ] #5126  by @pkdash 
- [ ] #5204 by @pkdash 
- [ ] #5216 by @devincowan 
- [ ] #5230 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [ ] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [ ] Deployed to Beta
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issues
- [ ] Hsclient tests pass when targeting beta
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [ ] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Metrics system need to merge https://github.com/hydroshare/docker-elk/pull/11

Git diff:
https://github.com/hydroshare/hydroshare/compare/2.9.2...2.9.3
