### ISSUE TITLE
Release Checklist 2.12

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5299]
### Issues in Release
- [x] #5225 by @pkdash and @devincowan
- [x] #5298 by @devincowan 
- [x] #5236 by @pkdash 
- [x] #5306 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] Hsclient tests pass when targeting beta
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Requires management command to re-deposit crossref records `update_crossref_deposit_all_published_resources`
  - [beta run](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-hsctl-command/489/console)
  - [2nd attempt beta run](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-hsctl-command/492/console)
3. Requires management command to get emails to notify about non-compliant funder names `check_unknown_funder_names_published_resources`
  - [beta run](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Beta%20deployment/job/beta-hsctl-command/490/console)

### Diff
https://github.com/hydroshare/hydroshare/compare/2.11.3...rc-2.12
