### ISSUE TITLE
Release Checklist 2.12.3

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5317]
### Issues in Release
- [ ] #5300 by @devincowan 
- [ ] #5319 by @pkdash 
- [ ] #5320 by @devincowan 
- [ ] #5321 by @devincowan 

### Beta Deployment
Release will not include a beta deployment or QA

### Production Deployment
- [ ] ~Snapshot the DB and iRods VM before deploy~ NA
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Requires running management command `update_crossref_deposit_all_published_resources`

### diff
https://github.com/hydroshare/hydroshare/compare/2.12.2...2.12.3
