### ISSUE TITLE
Release checklist 2.13

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5324]
### Issues in Release
- [x] #5301 by @devincowan 
- [x] #5294 by @devincowan 
- [x] #5326 by @pkdash 
- [x] #5306 by @devincowan 
---
###  [Following added after QA:](#following-added-after-qa)
- [x] #5345 by @pkdash 
- [x] #5335 by @devincowan 
- [x] #5340 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] ~Changes in hydroshare/local_settings.py need to be coordinated for manual update~
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [ ] Hsclient tests pass when targeting beta
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] ~Snapshot the DB and iRods VM before deploy (RC now contains migration)~ verified non-breaking migration on beta
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. [Enter Notes here]

### diff
https://github.com/hydroshare/hydroshare/compare/2.12.3...rc-2.13

**Comment by devincowan** [comment]
adding #5345 to the 2.13 checklist this am
