### ISSUE TITLE
Release Checklist 2.13.5

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5398]
### Issues in Release
- [x] #5391 by @pkdash 
- [x] #5339 by @devincowan 
- [x] #5400 by @devincowan 
- [x] #5411 by @devincowan 
- [x] #5415 by @sblack-usu 
- [x] #5422 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [x] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] Hsclient tests pass when targeting beta
  - https://github.com/hydroshare/hsclient/actions/runs/8382745225/job/22957106864
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [ ] ~Snapshot the DB and iRods VM before deploy~
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. ~requires changes to `local_settings`~

### diff
https://github.com/hydroshare/hydroshare/compare/2.13.4...rc-2.13.5

**Comment by pkdash** [comment]
@devincowan I did test my issue #5391 and I am still getting the OpenAPI documentation error for 2 endpoints (GET and PUT):
`/resource/{id}/json/ModelProgram/{aggregation_path}`. I will try get a fix tomorrow.

**Comment by devincowan** [comment]
Issues encountered with JupyterHub authentication during deployment of 2.13.5.

**Comment by devincowan** [comment]
2.13.5 was released but then rolled back.
2.13.6 was then released with fixes
