### ISSUE TITLE
Release Checklist 2.13.9

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5465]
### Issues in Release
- [x] #5444 by @sblack-usu 
- [x] #5354 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [ ] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [ ] Hsclient tests pass when targeting beta
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [ ] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
1. Requires modifications to hydroshare-config.yaml
  ```
### Irods Userzone Keys
HOST_PK_FOR_HS_USER_ZONE: /opt/.ssh/id_ed25519_hs
# Following should match the value set in local_settings.py
PRIVATE_KEY_FILE_FOR_HS_USER_ZONE: /hydroshare/.ssh/id_ed25519_hs
```
2. Addition of `PRIVATE_KEY_FILE_FOR_HS_USER_ZONE` to local settings
3. docker-compose.template needs update with
```
- "${HOST_PK_FOR_HS_USER_ZONE:-/opt/.ssh/id_ed25519_hs}:${PRIVATE_KEY_FILE_FOR_HS_USER_ZONE:-/hydroshare/.ssh/id_ed25519_hs}
```
4. SSH key generation and placement of public key in userzone, private key on HS workers
5. Add `KEYCLOAK_ADMIN_USERNAME` and `KEYCLOAK_ADMIN_PASSWORD` to local_settings.py

### Diff
https://github.com/hydroshare/hydroshare/compare/2.13.8...rc-2.13.9
