### ISSUE TITLE
Release Checklist 2.13.10

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5476]
### Issues in Release
- [x] #5432 by @sblack-usu 
- [x] #5421 by @devincowan 
- [x] #5473 by @pkdash 
- [ ] #5472 by @sblack-usu 
- [x] #5262 by @devincowan 

### Beta Deployment
- [x] Diff RC to master to identify and manually make changes in the following files:
  * hsctl
  * config/hydroshare-config.yaml
  * nginx/config-files/hydroshare-ssl-nginx.conf.template
  * scripts/templates/docker-compose.template
- [x] Changes in hydroshare/local_settings.py need to be coordinated for manual update
- [ ] Smoke test active worker before swap, note whether maintenance will be needed (make sure that you check the active worker AFTER the db migrations have run)
- [ ] Add any management commands necessary for the deploy to the notes section
- [ ] Deployed to Beta
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issues
- [ ] Hsclient tests pass when targeting beta
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [x] Snapshot the DB and iRods VM before deploy
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Contains migration so needs snapshots
- [x] Requires following setting be added: `IRODS_SINGLE_RESC_FOR_QUERY='hydroshareUfsResc1'`
- [x] Management commands need to be run (see below)

Also #5472 requires auth settings file to be added into zdt and modify to cp that file into /hydroshare during deploy

### Diff
https://github.com/hydroshare/hydroshare/compare/2.13.9...2.13.10

**Comment by devincowan** [comment]
### Management commands
- [x] then run a spot check `reset_file_size_system_metadata --update --resource_id 03dc01d36f0547f5945d93d2c47b48cc`
and check https://www.hydroshare.org/resource/03dc01d36f0547f5945d93d2c47b48cc/ to ensure that it updated properly (correct resource size and no 0 length file replicas)
- [ ] then run the management command
`reset_file_size_system_metadata --update --min_quota_django_model 5 --refreshed_weeks 52` https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Production-Deployment/job/prod-hsctl-command/324/console
- [ ] then reset all of the other ResourceFile sizes `ResourceFile.objects.filter(filesize_cache_updated__isnull=True).update(_size=-1)`
- [ ] followed by `reset_file_size_system_metadata --update --refreshed_weeks 52` to calculate all of the remaining fileSizes
