### ISSUE TITLE
2.15 Release checklist

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5483]
## Schedule
* July 1 3:00 pm

### HS Core application
- [x] Turn off jenkins jobs for metrics, mailchimp, etc(?)
- [x]  On the www2 run ./hsctl managepy remove_unreferenced_files --updated_since=4 --dryrun
- [x]  Run repair_resource for all resources identified as unreferenced irods files (Not likely to encounter any as this is an error state)
- [x] Sync irods (first, w/out maint page)
    * [x] As irods user on data.hydroshare.org: `irule -r irods_rule_engine_plugin-irods_rule_language-instance "migration_sync_all_files_newer_than_x_seconds(*seconds)" "*seconds=345600" null`
    * [x] `iqstat | wc -l` until it is down to "1"
- [x] Turn on HS maintenance mode
- [x]  On the www2 run ./hsctl managepy remove_unreferenced_files --updated_since=1 --dryrun
   * [x] Run repair_resource for all resources identified as unreferenced irods files (Not likely to encounter any as this is an error state)
- [x] Sync irods (second time, with maint page)
    * [x] As irods user on data.hydroshare.org: `irule -r irods_rule_engine_plugin-irods_rule_language-instance "migration_sync_all_files_newer_than_x_seconds(*seconds)" "*seconds=86400" null`
    * [x] `iqstat | wc -l` until it is down to "1"
- [x] Update the django db
   * [x] Scale defaultworker to 0
   * [x] scale the hydroshare pods to 0
    * [x] Run from the active RENCI worker (w1): 
    ```
    sudo su - hydro-service
    ssh db3-hs.edc.renci.org docker exec -u postgres postgis pg_dumpall > "/projects/hydroshare/hsdata/prod/backup/pg.hydroshare-transfer.sql"
    ls -lahtr /projects/hydroshare/hsdata/prod/backup/pg.hydroshare-transfer.sql  #ensure as expected
    exit  # use dcowan user
    kubectl cp /projects/hydroshare/hsdata/prod/backup/pg.hydroshare-transfer.sql postgis-5594cc9f8b-wjnpc:/tmp/01/pg.hydroshare-transfer.sql
    kubectl exec --stdin --tty postgis-5594cc9f8b-wjnpc -- /bin/bash
    mv -f /tmp/01/pg.hydroshare-transfer.sql /tmp/01/pg.development.sql
    su - postgres
    psql -c "REVOKE CONNECT ON DATABASE postgres FROM public;"
    psql -c "SELECT pid, pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = current_database() AND pid <> pg_backend_pid();"
    dropdb -U postgres -h postgis postgres
    createdb -U postgres -h postgis postgres
    cd /docker-entrypoint-initdb.d
    ./init-db.sh
    restart the postgis container
    ```
- [x] Update Django media files
    * [x] Run from the active RENCI worker: `gsutil -m rsync -r /home/hydro/hydroshare/hydroshare/static/media/ gs://hydroshare-prod-static-media/`
- [x] scale up the hs containers
- [x]  On hydroshare-0 run `python manage.py remove_unreferenced_files --updated_since=2`
- [x]  On hydroshare-0 run `python manage.py sync_is_public --updated_since=2`
- [x] Update hostnames in DNS

#### Core application issues remaining
- [x] ~can we reduce downtime by improving sync of irods storage into cloud?~ (Terrell working on script to federate the datazones for transfer.
- [x] [data-resource-list.log](http://ci.hydroshare.org:8080/view/03-Housekeeping/job/copy-remote-to-local/369/artifact/data-resource-list.log) looks like it maybe just contains a list of ALL resources?
- [x] ~Does HS need to be "read-only" during the ~24hrs that the [weekly data snapshot](http://ci.hydroshare.org:8080/view/03-Housekeeping/job/copy-remote-to-local/) is running? If so, that means our downtime is effectively 72hrs right now :(~ (No longer an issue as long as federation of irods datazones between renci and cloud works)
- [x] bucket backend work needs review and merge https://github.com/hydroshare/hydroshare/pull/5482
- [x] resource sizes are off in .io `[31/May/2024 14:15:15] ERROR [django_irods.storage:345] settings.IRODS_SINGLE_RESC_FOR_QUERY not set. The resulting size might not be accurate if the file is replicated.`
- [x] we should compare prod settings/local_settings.py against our chart values to make sure we haven't missed anything in the last few releases
- [x] https://github.com/hydroshare/hydroshare/pull/5503
- [x] https://github.com/hydroshare/hydroshare/pull/5502
- [x] https://github.com/hydroshare/hydroshare/pull/5499
- [x] https://github.com/hydroshare/hydroshare/pull/5505
- [x] https://github.com/CUAHSI/platform-recipes/pull/11
- [x] https://github.com/CUAHSI/platform-recipes/pull/10
- [x] https://github.com/CUAHSI/platform-recipes/pull/12
- [x] We are still running django with devserver -- we should add gunicorn back in
- [x] basic auth to API is not working
- [x] publication is broken (no records sent to crossref)
- [x] emails are not actually being sent by the system?
- [x] We aren't running flower, so have very little insight into our async tasks
- [x] RE-run hsclient tests https://github.com/hydroshare/hsclient/actions/runs/9687224124/job/26731377071
- [x] https://github.com/hydroshare/hydroshare/pull/5507
- [ ] ~We still don't have any monitoring running~
- [x] We should tag our image and publish the tag in our helm chart

##### Issues that we can address in July
- [ ] https://github.com/hydroshare/hydroshare/issues/5514
- [x] #5519
- [ ] #5516
- [ ] #5517
- [x] #5508
- [x] #5509
- [ ] #5510
- [ ] #5511
- [x] #5512
- [ ] #5515
- [ ] https://github.com/hydroshare/hydroshare/issues/5506
---

### Geoserver
We will run this on the Friday prior
- [ ] ~Irods vault in NFS share mounted on geoserver CE VM~ backtracked as of Jun3
- [ ] ~Dump the geoserver PG db~
- [ ] ~Import db to .io geoserver container~
- [x] Update local_settings in the cloud data_services `HYDROSHARE_URL` to `.org` instead of `.io`
- [x] Docker restart, make sure the settings take hold
- [x] `docker exec -it hs_data_services-gunicorn-1 python manage.py copy_res_files_from_hydroshare`
- [x] Update local_settings in the cloud data_services `PROXY_BASE_URL` to `.org` instead of `.io`
- [x] Docker restart, make sure the settings take hold and system is up
- [x] Update load balancer, replacing .io cert with .org cert
- [x] Wait for ssl warning to appear on geoserver.hydroshare.io
- [x] Modify DNS so that geoserver.hydroshare.org points at the cloud load balancer for geoserver
- [x] Re-run `docker exec -it hs_data_services-gunicorn-1 python manage.py copy_res_files_from_hydroshare`
- [x] Create a new resource in prod and ensure custom 404 page initially, then WMS/WFS
- [x] Update settings.yaml in helm `HSWS_URL` and `HSWS_GEOSERVER_URL` so that cloud.hydroshare.org points at new geoserver.hydroshare.org instead of `.io`
- [x] Test cloud.hydroshare.org by creating shapefiles etc and see that WMS links point at geoserver.hydroshare.org

#### Geoserver issues remaining
- [x] ~work out perms for nfs mount into geoserver container `{{IRODS_ACCESS_UID}} - The UID of a user on the host system with iRODS read access.` https://github.com/hydroshare/hs_data_services/blob/main/README.md?plain=1#L35~
- [x] ~also need to fstab to ensure mount survives vm restart etc~
- [x] Mount persistent disk
- [x] Complete https://github.com/hydroshare/hs_data_services/pull/6/files
- [x] Ensure that geoserver copy job doesn't duplicate file copy
- [x] Create and test job to sync (copy to cloud geoserver) existing Geospatial resources from prod onto geoserver
- [x] Latency -- we have to handle the time required to copy in the HS UI -- "give us a min to sync up!" ... just change the 404 error
- [x] Add alert or autoscaling for the persistent geoserver data disk
- [x] ~Can we use the internal DNS names so that we don't need to modify in settings.py etc?~

---
### Help pages
We will run this on the Friday prior
- [x] Shift hostnames in DNS
- [x] Remove pages.hydroshare.org DNS records
---

### THREDS

---

### TETHYS (can happen after the migration but before  june 30)
- [ ] Tethys 3.3 VM available 
- [ ] DataRds explorer redeployed 
- [ ] BYU is helping with migration apps to TETHYS 3 Aquaveo will help to migrate to tethys4 (under CIROH funding)
- 

---
### Matlab / Jupyter / CyberGIS 
- [x] Devin to test and ensure that Jupyter is working...don't anticipate any changes necessary

---
### Userzone migration
- [x] inform existing users of migration move by June 30 
- [ ] Create new userzone with 250GB size with new dns name - so we cam maintain old name for existing zone 
- [ ] Establish purge rule after 14 days
- [ ] Update documentation (cyberduck connection does not work to our cloud userzone)
- [ ] Backup entire userzone maintain for 3 month

#### Remaining userzone issues:
- [x] CyberDuck no longer connects. Use [iRods Python Client](https://github.com/irods/python-irodsclient) instead?
- [x] attempted CyberDuck connection to our .io userzone `Unable to start SSL socket. The connection attempt was rejected. The server may be down, or your network may not be properly configured.` https://hydroshare.slack.com/archives/C79R38HBQ/p1717089445576769
- [ ] because we are loading current hs db in beta.io, that instance of HS "believes" there are irods Userzone accounts in the .io userzone that don't actually exist (they exist on users.hydroshare.org)
- [ ] ~we need to remove the hard-coding of the userzone hostname within the hs codebase, or figure out the userzone host name cuttover~ (no longer an issue as the userzone hostname will remain same)

---
### Documentation 
- [ ] update documention for userzone?

---
### Jenkins is going away

- http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/
- https://new-hs-ci.hydroshare.org/view/04-Monitors/
- https://new-hs-ci.hydroshare.org/view/06-MailChimp/
- https://new-hs-ci.hydroshare.org/view/05-Analysis/

**Comment by devincowan** [comment]
discovered that uploading files > 50mb seems to reproducibly fail on beta.io

**Comment by devincowan** [comment]
discovered that, because we are loading current hs db in beta.io, that instance of HS "believes" there are irods Userzone accounts in the .io userzone that don't actually exist (they exist on users.hydroshare.org)

**Comment by devincowan** [comment]
resource sizes are off in .io
```
[31/May/2024 14:15:15] ERROR [django_irods.storage:345] settings.IRODS_SINGLE_RESC_FOR_QUERY not set. The resulting size might not be accurate if the file is replicated.
```

**Comment by devincowan** [comment]
work out perms for nfs mount into geoserver container

**Comment by devincowan** [comment]
![image (2)](https://github.com/hydroshare/hydroshare/assets/17934193/766e7a3f-c34f-4e0e-bd67-c7f6aac7d4b7)
@martinseul experienced error uploading shapefiles

**Comment by devincowan** [comment]
attempted CyberDuck connection to our .io userzone

> Unable to start SSL socket. The connection attempt was rejected. The server may be down, or your network may not be properly configured.
