### ISSUE TITLE
Release Checklist 2.15.2 and 2.15.3

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5533]
### Issues in Release
- [x] #5512 by @sblack-usu 
- [x] #5523 by @sblack-usu 
- [x] #5519 by @devincowan 

### Issues will be closed
- [x] #5104
- [x] #5061
- [x] #3915
- [x] #1930
- [x] #2585

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes relevant to deployment
2.15.1 Requires downtime for migrations
However that downtime is bypassed by releasing 2.15.1 as 2.15.2 and 2.15.3 instead.

2.15.2 should be released and once all pods are rebuilt, then 2.15.3 can be released.

Requires local setting:
https://github.com/hydroshare/hydroshare/compare/2.15...2.15.1#diff-2521ce60a97c1524722701093e6ea98b2ae1f1b819aaa8bf38068d2276e61de4L352

### DIFF
https://github.com/hydroshare/hydroshare/compare/2.15...2.15.3

**Comment by devincowan** [comment]
released
