### ISSUE TITLE
Release Checklist 2.15.5

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5561]
### Issues in Release
- [ ] #5510 by @devincowan 
- [ ] #5546 by @devincowan 
- [ ] #5556 by @devincowan 
- [ ] #3748 by @devincowan 
- [ ] #5515 by @devincowan 

### Beta Deployment
- [ ] Diff RC to master to identify and update helm chart for the following files:
  * scripts/templates/docker-compose.template
  * hydroshare/settings.py
  * hydroshare/local_settings.py
- [ ] Determine whether maintenance page will be needed (db migrations etc)
- [ ] Add any management commands necessary for the deploy to the notes section

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. Some settings to remove from helm: https://github.com/hydroshare/hydroshare/compare/2.15.4...develop#diff-06b8e463fb56c34a33b5cb67b24f74e0f763f04c1619d02962d84a8b52a1a1e1L159
2. Enable cloud logging: https://github.com/hydroshare/hydroshare/compare/2.15.4...develop#diff-2521ce60a97c1524722701093e6ea98b2ae1f1b819aaa8bf38068d2276e61de4R653-R661

### DIFF
https://github.com/hydroshare/hydroshare/compare/2.15.4...2.15.5
