### ISSUE TITLE
Release Checklist 2.15.7

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5567]
### Issues in Release
- [x] #5558 by @devincowan 
- [x] #5579  by @devincowan 
- [x] #5587 by @devincowan 

### Production Deployment
- [x] Deployed to Production
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issue

### Notes
- [x] Relies on https://github.com/CUAHSI/platform-recipes/pull/32

- [x] Need to run `set idle_in_transaction_session_timeout to 70000;` on PG after deploy

### Diff
https://github.com/hydroshare/hydroshare/compare/2.15.6...2.15.7
