### ISSUE TITLE
Release checklist 2.15.6

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5569]
### Issues in Release
- [ ] #5562 by @devincowan 

### Beta Deployment
- [ ] Diff RC to master to identify and update helm chart for the following files:
  * scripts/templates/docker-compose.template
  * hydroshare/settings.py
  * hydroshare/local_settings.py
- [ ] Determine whether maintenance page will be needed (db migrations etc)
- [ ] Add any management commands necessary for the deploy to the notes section

### Production Deployment
- [ ] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
3. Modify `init-defaultworker`: https://github.com/hydroshare/hydroshare/compare/2.15.4...develop#diff-8184d18f5e9a4104c30d068a2a8a5afce50b533a292d8be3a216b5a2eee6576eR11-R22

### DIFF
https://github.com/hydroshare/hydroshare/compare/2.15.5...2.15.6
