### ISSUE TITLE
2.15.8 Release Checklist

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5589]
### Issues in Release
- [ ] #5316 by @pkdash 

### Recipies
https://github.com/CUAHSI/platform-recipes/pull/38

### Beta Deployment
- [x] Diff RC to master to identify and update helm chart for the following files:
  * scripts/templates/docker-compose.template
  * hydroshare/settings.py
  * hydroshare/local_settings.py
- [x] Determine whether maintenance page will be needed (db migrations etc)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] [Hsclient tests pass when targeting beta](https://github.com/hydroshare/hsclient/actions/runs/11168045672)
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. The release does include [some db migrations](https://github.com/hydroshare/hydroshare/pull/5352/files#diff-77e47371a55283848c294a4b8cd079a93ec5944f4bcde6598d453633887e27d9) so technically there will be a brief period where our db is out of sync with the active pod -- just the time between when the migrations are run on the new pod and when the old pod gets cycled out. 
2. In the deploy to beta, this gap was less than a minute and I was not able to capture/witness any untoward behavior in manual testing, so I was unconcerned by it.
3. Might be worth checking on when the last cluster-level snapshot was for peace of mind in a worst case rollback scenario
