### ISSUE TITLE
Time Series: Implement Phase 2 Functionality

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#559]
The following web user interface changes and API support are needed to make Time Series Phase 2 complete. The additional tools are listed here as a placeholder until we decide whether we want to create them.

**Web User Interface Changes**
- [x] 1. Add capability to have multiple time series in a single resource by supporting multiple time series in the underlying ODM2 SQLite file (see #1220 for this issue)
- [x] 2. Fix the issue with re-extracting time series metadata from the underlying ODM2 database (see #1151 for this issue) (Pabitra: This is no more an option. Metadata is extracted upon SQLite file upload)
- [x] 3. Fix the issue with editing Method metadata (see #587 for this issue)
- [x] 4. Add ability to reflect changes to metadata made in the web user interface into the ODM2 SQLite file in which the data are stored (see #341 for this issue).
- [x] 5. Add capability to create a Time Series resource from simple CSV file upload (see issue #1221).
- [x] 6. Make sure coverage element is a point for single time series and a bounding box for multiple time series. 

**API Support**
- [x] 1. Ensure capability to upload and download time series resource files through API.  
- [ ] 2. Ensure capability to set and get time series metadata through API.

**Additional tools that would be useful for Time Series resources:**
- [ ] 1. Add capability to create a resource from advanced CSV/YODA file upload.
- [ ] 2.  Develop an external Visualization tool for time series
- [ ] 3.  Develop tools for exporting to other formats (e.g., CSV, WaterML 1.1, 2.0)
- [ ] 4. Develop tools for establishing a CUAHSI HIS compatible web service endpoint to serve time series resource content (using WaterML flavors)
- [ ] 5.  Develop a tool to import resource packages as a complete resource data model bag.  This involves a reflector function to generate the metadata in Django from the XML format metadata and will support direct exchange of this resource type with iRODS and with other clients.

**Comment by horsburgh** [comment]
Phase 1 of time series is done, so I'm closing this issue. The Phase 2 stuff has been moved to a new issue - see #1942
