### ISSUE TITLE
2.15.9 Release Checklist

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5611]
### Issues in Release
- [x] #5498 by @pkdash
- [x] #5410 by @MSDrao 
- [x] #5605 by @sblack-usu 
- [x] #4092 by @MSDrao 
- [x] #5410 by @MSDrao 
- [x] #5409 by @MSDrao 
- [x] #3460 by @MSDrao 
- [x] #5622 by @horsburgh 
- [x] #5628 by @devincowan 

### Recipies

https://github.com/CUAHSI/platform-recipes/pull/43

### Beta Deployment
- [x] Diff RC to master to identify and update helm chart for the following files:
  * scripts/templates/docker-compose.template
  * hydroshare/settings.py
  * hydroshare/local_settings.py
- [x] Determine whether maintenance page will be needed (db migrations etc)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] [Hsclient tests pass when targeting beta](https://github.com/hydroshare/hsclient/actions/runs/11541625760/job/32123844187)
- [ ] QA testing around issues
- [ ] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment
1. hydroshare help documentation on content type needs to be updated to include CSV content type

### Diff
https://github.com/hydroshare/hydroshare/compare/2.15.8...rc-2.15.9

**Comment by pkdash** [comment]
@devincowan It would be good to include a note here that the hydroshare help documentation on content type needs to be updated to include CSV content type. I have already got a draft csv content type help documentation that @ClaraCogswell can use and make necessary changes.

**Comment by ClaraCogswell** [comment]
@pkdash if you already have a draft feel free to share it and I'll modify it to the help docs.

**Comment by devincowan** [comment]
@pkdash I put this rc on beta
Found one issue: when you upload a .csv, it looks like it disables the "add files" button
<img width="312" alt="image" src="https://github.com/user-attachments/assets/17c78136-52c2-42ad-9a79-12fb1a9a4613">

https://github.com/hydroshare/hydroshare/blob/rc-2.15.9/theme/static/js/hs_file_browser.js#L519-L534

**Comment by pkdash** [comment]
@devincowan Thanks for catching this bug. I will try to fix it today.

**Comment by devincowan** [comment]
@pkdash worth making sure it is also an issue for you locally and not just on beta. I didn't verify that...

**Comment by pkdash** [comment]
@ClaraCogswell The last 2 pages of this document has my draft help documentation for the CSV content type:
https://docs.google.com/document/d/19a-Na6Xmmu5C-WYhWmpZDPvWcrQ3WcNhl5VkljiCtS0/edit
