### ISSUE TITLE
Release Checklist 2.15.11

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5657]
### Issues in Release
- [x] #5666 by @MSDrao 
- [x] #5596 by @MSDrao and @devincowan 
- [x] #5585 by @MSDrao 
- [x] #5405 by @MSDrao (partial fix, more work to be done in https://github.com/hydroshare/hydroshare/issues/5724)

### Beta Deployment
- [x] Diff RC to master to identify and update helm chart for the following files:
  * scripts/templates/docker-compose.template
  * hydroshare/settings.py
  * hydroshare/local_settings.py
- [x] Determine whether maintenance page will be needed (db migrations etc)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Dev-1
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] Hsclient tests pass when targeting dev-1 https://github.com/hydroshare/hsclient/actions/runs/12734637839
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Notes relevant to deployment

Requires running management command [crossref_to_ror](https://github.com/hydroshare/hydroshare/compare/2.15.10...rc-2.15.11#diff-9c515a2597ad8b2f8ae0d70dd92906b8da6af5b25236c40de399c613cd00845e)

### Diff
https://github.com/hydroshare/hydroshare/compare/2.15.10...rc-2.15.11

### Recipies
https://github.com/CUAHSI/platform-recipes/pull/70
