### ISSUE TITLE
Release Checklist 3.0.0

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#5675]
### Issues in Release
- [x] #5577 @sblack-usu 

### Notes relevant to deployment
- [x] Update lifecycle policies script to update buckets without an existing policy (Scott)
- [x] Setup Production S3 Server (Neal)
- [x] Create buckets
- [x] Set initial lifecycle policies
- [x] Setup lifecycle policy cron job
- [x] Deploy S3 RC candidate to beta (pointing to Production S3)
- [x] Test compatibility with THREDDS
- [x] Test compatibility with Geoserver

### Beta Deployment
- [x] Diff RC to master to identify and update helm chart for the following files:
  * scripts/templates/docker-compose.template
  * hydroshare/settings.py
  * hydroshare/local_settings.py
- [x] Determine whether maintenance page will be needed (db migrations etc)
- [x] Add any management commands necessary for the deploy to the notes section
- [x] Deployed to Beta
- [x] Review the search and discovery pages
- [x] Create a new user and update profile
- [x] Create iROD account, test connection and delete iROD account
- [x] Create a new resource, check sharing/permission settings, delete new resource
- [x] Developers test around issues
- [x] Hsclient tests pass when targeting beta
- [x] QA testing around issues
- [x] Stakeholders approval

### Production Deployment
- [x] Deployed to Production
  * Make manual changes to files identified in Beta Deployment
- [ ] Review the search and discovery pages
- [ ] Create a new user and update profile
- [ ] Create iROD account, test connection and delete iROD account
- [ ] Create a new resource, check sharing/permission settings, delete new resource
- [ ] Developers test around issue

### Diff
https://github.com/hydroshare/hydroshare/compare/2.15.12...rc-3.0.0
